setup.colours = {
  yellow: {
    isNatural: true,
    isPlant: true,
    isMineral: true,
    colour: [
      'ivory',
      'cream',
      'yellow',
      'beige',
      'peridot',
      'citrine',
      'dark yellow',
      'light yellow',
      'bright yellow',
      'pastel yellow',
      'gold',
      'lemon yellow'
    ],
    coloured: [
      'daffodil',
      'lemon',
      'dandelion',
      'straw',
      'brass',
      'banana',
      'canary',
      'corn',
      'gold',
      'cheese',
      'butter',
      'amber'
    ]
  },
  orange: {
    isNatural: true,
    isPlant: false,
    isMineral: false,
    colour: [
      'vermillion',
      'ochre',
      'orange',
      'burnt orange',
      'sherbert orange',
      'ginger',
      'amber',
      'light orange',
      'dark orange',
      'bright orange',
      'pastel orange',
      'carrot orange',
      'mahogany',
      'sunglow orange',
      'pumpkin orange'
    ],
    coloured: [
      'orangutan',
      'carrot',
      'tangerine',
      'apricot',
      'sandstone',
      'honey',
      'marmalade',
      'apricot',
      'pumpkin',
      'poppy',
      'marigold'
    ]
  },
  red: {
    isNatural: true,
    isPlant: false,
    isMineral: true,
    colour: [
      'red',
      'bright red',
      'firey red',
      'auburn',
      'crimson',
      'oxblood red',
      'vermillion',
      'maroon',
      'carmine',
      'dark red',
      'light red',
      'pale red',
      'pastel red',
      'apricot',
      'burgundy',
      'blood red',
      'cardinal',
      'coral',
      'pink',
      'mystic red',
      'rose red',
      'scarlet',
      'rust',
      'salmon'
    ],
    coloured: [
      'rose',
      'tomato',
      'blood',
      'fire',
      'rust',
      'coral',
      'apple',
      'chili',
      'raspberry',
      'watermelon',
      'fig',
      'cranberry',
      'cherry',
      'ruby',
      'cardinal'
    ]
  },
  purple: {
    isNatural: false,
    isPlant: false,
    isMineral: true,
    colour: [
      'tyrian purple',
      'royal purple',
      'electric purple',
      'purple',
      'mauve',
      'violet',
      'pale purple',
      'dark purple',
      'light purple',
      'bright purple',
      'dull purple',
      'bright violet',
      'lavendar',
      'lilac',
      'pale plum',
      'pastel purple',
      'amethyst'
    ],
    coloured: [
      'thistle',
      'orchid',
      'blackberry',
      'eggplant',
      'lilac',
      'plum',
      'grape',
      'iris',
      'lavendar',
      'amethyst'
    ]
  },
  blue: {
    isNatural: false,
    isPlant: false,
    isMineral: true,
    colour: [
      'light blue',
      'blue',
      'dark blue',
      'deep blue',
      'navy blue',
      'cerulean',
      'azure',
      'indigo',
      'turquoise',
      'periwinkle',
      'teal',
      'capri',
      'royal blue',
      'sapphire',
      'pastel blue'
    ],
    coloured: [
      'denim',
      'sapphire',
      'sea',
      'storm',
      'sky',
      'peacock',
      'topaz'
    ]
  },
  green: {
    isNatural: true,
    isPlant: true,
    isMineral: true,
    colour: [
      'green',
      'olive',
      'sage',
      'emerald',
      'lime',
      'chartreuse',
      'mint',
      'seafoam green',
      'pear green',
      'apple green',
      'bright green',
      'dark green',
      'forest green',
      'light green',
      'celadon',
      'pastel green'

    ],
    coloured: [
      'seafoam',
      'shamrock',
      'seaweed',
      'pear',
      'pickle',
      'leaf',
      'grass',
      'frog',
      'turtle',
      'moss'
    ]
  },
  brown: {
    isNatural: true,
    isPlant: true,
    isMineral: true,
    colour: [
      'brown',
      'umber',
      'chocolate',
      'caramel',
      'burnt butter',
      'mud brown',
      'tan',
      'dark brown',
      'rust brown',
      'sandy brown',
      'bronze',
      'sepia',
      'pastel brown'

    ],
    coloured: [
      'acorn',
      'almond',
      'baked bread',
      'bark',
      'beeswax',
      'coffee',
      'ale',
      'pecan',
      'mocha',
      'cork',
      'wood',
      'tea'
    ]
  },
  black: {
    isNatural: true,
    isPlant: false,
    isMineral: true,
    colour: [
      'onyx',
      'ebony',
      'charcoal',
      'licorice',
      'black',
      'slate'
    ],
    coloured: [
      'charcoal',
      'licorice',
      'iron',
      'burnt bread',
      'obsidian',
      'crow',
      'soot',
      'ink',
      'raven',
      'storm cloud'
    ]
  },
  white: {
    isNatural: true,
    isPlant: false,
    isMineral: false,
    colour: [
      'white',
      'ghost white',
      'pure white',
      'pearl white',
      'floral white',
      'vanilla',
      'seashell',
      'snow white',
      'ivory'
    ],
    coloured: [
      'cloud',
      'eggshell',
      'champagne',
      'bone',
      'snow',
      'tooth',
      'ivory',
      'cotton',
      'dandelion',
      'chalk',
      'swan',
      'milk',
      'sheep',
      'pearl',
      'lotus'
    ]
  }
}
