setup.createMagicWeapon = function () {
  var weapon = ['Club', 'Dagger', 'Greatclub', 'Handaxe', 'Javelin', 'Light Hammer', 'Mace', 'Quarterstaff', 'Sickle', 'Spear', 'Crossbow, Light', 'Dart', 'Shortbow', 'Sling', 'Battleaxe', 'Flail', 'Glaive', 'Greataxe', 'Greatsword', 'Halberd', 'Lance', 'Longsword', 'Maul', 'Morningstar', 'Pike', 'Rapier', 'Scimitar', 'Shortsword', 'Trident', 'War Pick', 'Warhammer', 'Whip', 'Blowgun', 'Crossbow, Hand', 'Crossbow, Heavy', 'Longbow', 'Net']
  var prefixWeapon = ["Abberant Slayer's", 'Adamantine', 'Acidic', 'Alien', 'Amorphous', 'Ancient', 'Anomalous', 'Antikytheran', 'Arcane', 'Arctic', "Artist's", "Assassin's", 'Autumn', 'Barbed', "Beast's", "Beast Slayer's", 'Binding', 'Blasted', 'Blessed', 'Blind', "Blind Man's", 'Blithe', 'Bloodthirsty', "Bogwalker's", 'Bonded', 'Booming', 'Braided', 'Brutal', 'Deep', 'Broken', 'Captivating', 'Capricious', 'Cardinal', 'Caustic', 'Celestial', 'Chained', 'Charged', 'Chill', 'Civilized', "Cobra's", 'Compassionate', 'Consecrated', 'Concentrated', 'Corrosive', "Courser's", 'Crashing', 'Crawling', 'Cruel', 'Dancing', 'Dark', 'Dead', 'Deceptive', 'Defensive', "Delver's", 'Desperate', 'Disguized', "Dissassembler's", 'Diplomatic', 'Dowsing', 'Draconic', 'Draining', "Dreamscribe's", "Drunkard's", "Dryad's", 'Eager', 'Earthen', 'Eastern', 'Effortless', 'Effulgent', 'Eidolic', 'Elemental', "Elementalist's", 'Enchanting', 'Enervating', 'Epistemological', 'Equanimeous', 'Etched', 'Expanding', 'Exuberant', 'Fabricated', 'Faceless', 'Fairweather', 'Fatespun', 'Favored', 'Feathered', 'Feeding', 'Feindish', "Feind-Slayer's", 'Final', 'First', 'Flickering', 'Focused', 'Focusing', 'Force', 'Forgotten', 'Friendly', 'Frozen', 'Furious', 'Ghost-Tipped', 'Ghost-Touched', "Giant Slayer's", 'Glorious', 'Goading', "Graverobber's", 'Guardian', "Halfling's", 'Halucinating', 'Harkening', 'Haunted', "Healer's", 'Healing', 'Heroic', 'Holy', 'Icy', 'Iconic', 'Illuminating', 'Imaginary', 'Impact', 'Indifferent', 'Indomitable', 'Inspired', 'Jagged', "Jester's", "Jumper's", 'Leaping', "Liar's", 'Lifting', 'Lightfooted', "Gambler's", "Mage Killer's", 'Malediction', 'Maligning', "Marquis'", 'Masked', "Master's", 'Meadowforged', 'Memorial', 'Merciful', 'Messaging', 'Mimicking', 'Mindscour', "Mind's Eye", "Monster Hunter's", 'Monster-Killing', 'Mortuary', "Mourner's", 'Murderous', 'Northern', 'Nourishing', 'Nullifying', "Ooze Hunter's", 'Painstrike', 'Paranoid', 'Parrying', 'Patient', 'Pernicious', 'Phantom', 'Pious', "Prospecter's", "Preacher's", "Pyromancer's", 'Quantum', 'Quicksilver', 'Rainbow', "Reader's", 'Refined', 'Reliable', 'Renaissance', 'Repairing', 'Resisting', 'Resonant', 'Restrained', 'Righteous', 'Rosen', 'Runic', 'Saving', 'Scarlet', 'Seige', 'Serrated', 'Shading', 'Shadow', 'Shamanic', 'Shaming', "Shieldmaden's", 'Shielding', 'Singing', 'Skyward', "Slayer's", 'Smoldering', "Smuggler's", "Sojourner's", 'Solemn', 'Soulbound', 'Southern', 'Spring', 'Staunch', 'Stepping', 'Strange', 'Strapping', 'Striding', 'Summer', "Surgeon's", 'Swift', 'Tenacious', 'Tithing', "Trailblazer's", 'Transient', 'Translucent', 'Trusty', 'Tsunami', "Twilight's", 'Unity', 'Victorious', 'Vigilant', 'Vile', 'Violent', 'Visionary', 'Vital', 'Voidstone', 'Voltaic', "War Leader's", 'Warded', 'Waterborne', 'Weave-touched', 'Western', 'Windy', 'Wild', 'Winged', 'Winter', "Woodsman's", "Wyrmling Hunter's", 'Wyrm-like', 'Zen']
  var suffixWeapon = ['of Aberration Slaying', 'of Adamantine', 'of Acid', 'of Lunacy', 'of Ooze Detection', 'of Old', 'of Abberation Detection', 'of Mechanisms', 'of Arcana', 'of Snow', 'of the Artist', 'of the Assassin', 'of Falling Leaves', 'of Barbs', 'of Beast Senses', 'of Beast Slaying', 'of Binding', 'of Detonation', 'of Parables', 'of Eyes', 'of Missing', 'of Mirth', 'of Bloodthirst', 'of Undead Detection', 'of Twins', 'of Thunder', 'of Knots', 'of Brutality', 'of the Deep', 'of Shards', 'of Saving Graces', 'of Chance', 'of the Lodestone', 'of Corrosion', 'of Celestial Detection', 'of Chains', 'of Lightning', 'of Chills', 'of the Capital', 'of Acid Spitting', 'of Compassion', 'of Consecration', 'of Concentration', 'of Dissolving', 'of the Hostler', 'of the Crashing Waves', 'of Vermin', 'of Cruelty', 'of Strings', 'of Darkness', 'of Rigor Mortis', 'of Deception', 'of Defense', 'of the Delver', 'of Desperation', 'of Many Appearances', 'of Dissassembly', 'of Diplomacy', 'of Dowsing', 'of Dragons', 'of Draining', 'of the Dreamscribe', 'of Taverns', 'of the Dryad', 'of Yearning', 'of Rooting', 'of the East', 'of Ease', 'of Light', 'of Apparitions', 'of Elemental Detection', 'of Elemental Slaying', 'of the Enchantress', 'of Inner Strength', 'of Truth', 'of Balance', 'of Allegories', 'of Expansion', 'of Expertise', 'of Construct Detection', 'of Many Identities', 'of Fairweather', 'of Intertwined Fates', 'of the Favored', 'of Feathers', 'of Food', 'of Fiend Detection', 'of Fiend Slaying', 'of Last Hope', 'of Speed', 'of Candlelight', 'of Focus', 'of Concentrating', 'of Force', 'of the Forgotten', 'of Friendship', 'of Ice', 'of Fury', 'of the Ranks', 'of Remembered Glory', 'of Giant Slaying', 'of Glory', 'of Duels', 'of Undead Slaying', 'of Protection', 'of Giant Detection', 'of Halucinations', 'of Eavesdropping', 'of Vengeful Spirits', 'of Health', 'of Healing', 'of Heroes', 'of Faith', 'of Icicles', 'of Symbols', 'of Illumination', 'of the Imagination', 'of Impact', 'of Indifference', 'of Surging Strength', 'of Inspiration', 'of Teeth', 'of Madness', 'of Jumping', 'of Leaping', 'of Lies', 'of Lifting', 'of Dodging', 'of Luck', 'of the Mage Killer', 'of Malediction', 'of Maligning', 'of the Maquis', 'of Still Winds', 'of Servants', 'of the Meadow', 'of Memories', 'of Mercy', 'of Sending', 'of Mimicry', 'of Countermeasures', "of the Mind's Eye", 'of Monstrosity Detection', 'of Monster Killing', 'of the Mortal Coil', 'of Last Words', 'of Slaughter', 'of the North', 'of Comfort', 'of Nullification', 'of Ooze Slaying', 'of Pain', 'of Paranoia', 'of Parrying', 'of Patience', 'of the Snake', 'of the Phantasm', 'of the Pious', 'of Gem Detection', 'of the Preacher', 'of Pyromancy', 'of Uncertainty', 'of Quicksilver', 'of Rainbows', 'of Literacy', 'of Quality', 'of Reliance', 'of the Renaissance', 'of Repairs', 'of Resistances', 'of Resonance', 'of Subdual', 'of Righteousness', 'of Roses', 'of Runes', 'of Saves', 'of Bleeding', 'of Sieges', 'of Serration', 'of Shade', 'of Shadows', 'of Rituals', 'of Disgrace', 'of the Targe', 'of Shielding', 'of Singes', 'of Unusual Gravity', 'of Slaying', 'of Flame', 'of Smuggling', 'of the Sojourner', 'of Solemnity', 'of Imprisonment', 'of the South', 'of Spring Rain', 'of Security', 'of Misty Step', 'of the Far Realm', 'of the Undaunted', 'of Strides', 'of the Scorching Sun', 'of the Surgeon', 'of Reflexes', 'of the Tenacious', 'of Tithes', 'of the Lost', 'of the Breaking Seal', 'of Translucence', 'of Resurgence', 'of Crashing Waves', 'of the Setting Sun', 'of Unity', 'of Victory', 'of Vigilance', 'of Villains', 'of Violence', 'of the Visionary', 'of Vitality', 'of the Void', 'of Conduits', 'of the War Leader', 'of Warding', 'of the Sea', 'of the Weave', 'of the West', 'of the Winds', 'of the Wilds', 'of Wings', 'of Winter Ice', 'of Felling', 'of Wyrmling Slaying', 'of Wyrm Detection', 'of Zen']
  var propertyWeapon = ['This weapon gains a +1 bonus to damage rolls against aberrations.',
    'This item is indestructible.',
    "As an action you can cast acid splash. You gain a +5 bonus to the spell's attack roll. You cannot use this ability again until you complete a short or long rest.",
    'Once attuned, the bearer constantly hears the ongoing, utterly insane mutterings of an alien intelligence trapped inside this weapon. Should this weapon be destroyed, the being will be released.',
    'The weapon sheds 30 feet of bright green light and another 30 feet of dim light after that whenever an ooze is within 100 feet of it.',
    'This worn weapon inscribed with ancient runes can be used as a Spellcasting Focus',
    'The weapon sheds 30 feet of bright purple light and another 30 feet of dim light after that whenever an aberration is within 100 feet of it.',
    'An ancient mechanism is housed within this weapon that never configures the same way twice. Once per long rest the bearer can spend one minute to attempt a DC 20 investigation check to configure the device. If successful, the weapon becomes a +1 weapon until the end of the next long rest.',
    'This weapon can project a spectral tome suspended in mid-air that the bearer can interact with like a physical book. This tome can be used as a spellbook and may contain some spells from its previous bearer.',
    'Icy wind and snowflakes bluster around this weapon, even in warm environments. The bearer can walk on the surface of the lightest snow, leaving no footprints.',
    'The bearer may use this weapon to make colored marks on any surface. The marks will fade away in 24 hours.',
    'The bearer may add 1d4 poison damage to all attacks made during surprise rounds.',
    "The weapon contains a resevoir of natural magic that can a sustain a cascade of falling leaves for up to 30 seconds. The bearer may use an action to plant this weapon in the ground and release this magic. While planted and undepleted, creatures within 10 feet of this weapon have half cover. A long rest restores 1d6 sconds of energy to the weapon's resevoir.",
    'After an attack roll, the bearer may use their reaction to add 1d4 to the damage roll and take 1d4 damage.',
    'While carrying this weapon you have advantage on Wisdom (Perception) checks that rely on smell.',
    'This weapon gains a +1 bonus to damage rolls against beasts.',
    'When you hit a creature with this weapon, the ground beneath binds to its feet, slowing its speed by 5 feet until the end of its next turn. This has no effect on creatures that are flying or swimming.',
    "The bearer may use a bonus action to activate destructive magic withing this weapon. It begins to glow with white-hot intensely, and at the beginning of the bearer's next turn, the weapon casts a level 1 Shatter spell (DC 12) centered on the weapon. The weapon then loses this property.",
    'Whenever the bearer of this item receives magical healing from a spell on the Cleric’s spell list, they gain an additional amount of hit points equal to their Wisdom (Religion) skill.',
    'Garrish eyes are painted on this weapon. The bearer can use an action to see/unsee through the eyes, even if their own senses are compromised.',
    'When an attack roll made with this weapon results in a miss, you gain 1 temporary hit point.',
    'The bearer is filled with inexplicable joy. All charisma skill and saving throw rolls gain a +1 bonus, but all wisdom skill and saving throw rolls gain a -1 penalty.',
    'The bearer of this weapon spend a bonus action and a hit die to turn this weapon into a +1 magic weapon for 1d4 turns.',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever an undead is within 100 feet of it.',
    'This item is part of a pair of identical items. The bearer of either knows the location of the other at all times.',
    'The bearer may choose to deal Thunder damage with this weapon and gain a +1 bonus to damage.',
    'The bearer may use their action to cause the weapon to become a 50 ft length of hemp rope at will.',
    'Critical hits made with this weapon deal 2 extra damage of the weapon’s type.',
    'The bearer can hold their breath for 5 minutes before the onset of asphyxiation.',
    'This weapon is badly damaged. It is a testament to its former power that it is still serviceable. If reforged, it might regain its former power.',
    'While the bearer is at 0 hp, they begin to hear the most beautiful music they have ever heard. The bearer has advantage on death saving throws and cannot recall details about the music if they wake.',
    'If the weapon is attuned to a Chaotic aligned character, they may roll a die after completing a long rest. If the result was an even number, treat this as a +1 magic weapon until they finish a long rest.',
    'The bearer always knows which way is north and has advantage on Wisdom (Survival) checks for land navigation.',
    'The bearer may choose to deal Acid damage with this weapon and gain a +1 bonus to damage.',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever a celestial is within 100 feet of it.',
    'The bearer can spend an action to mystically bind or unbind themselves to this weapon. While bound, the bearer can no longer be disarmed but cannot switch out or throw this weapon.',
    'The bearer may choose to deal Lightning damage with this weapon and gain a +1 bonus to damage.',
    "The air around the bearer of this weapon is always unnaturally cold. One's breath becomes visible, and frost continually forms on the surface of the bearer's hair, weapons, and armor. The bearer suffers no ill effect from being in extremely cold environments.",
    'The bearer gains +1 to intelligence saving thows.',
    'As an action you can cast poison spray (spell save DC 13). You cannot use this ability again until you complete a short or long rest.',
    'Wounds inflicted with this weapon cause no pain.',
    'Treat as a +1 magic weapon when attacking Undead. Any creature slain with this weapon cannot be raised as undead.',
    'As a action you gain advantage on your next ability check made before the end of your next turn. You cannot use this ability again until you complete a short or long rest.',
    'When the bearer hits a creature with this weapon, they may deal their proficiency bonus in acid damage to a different creature within 5 feet of the target.',
    'The bearer can placate and calm any mount not under the influence of a spell or possession.',
    'Whenever the bearer deals damage to a hostile creature, this weapon gains a charge. As a bonus action, the bearer can use any number of charges to deal that much extra lightning damage on their next attack. If a round (6 seconds) goes by and the weapon has not struck a foe, it loses all charges.',
    'The crawling things of the earth, such as insects, snakes, and vermin, are attracted to this item. When placed on the ground, such creatures will scurry toward the item like moths drawn to the flame.',
    'The bearer may re-roll damage from critical hits scored with this weapon and take the second result.',
    'The bearer may spend an action to permanently animate this weapon. Use the Flying Sword stat block from the Monster Manual p. 20. Also, the weapon retains any other magical properties. Once the animated weapon is reduced to 0 hp or unattuned, the weapon shatters like glass.',
    'The bearer may choose to deal Necrotic damage with this weapon and gain a +1 bonus to damage.',
    'If this weapon is entombed within a corpse for 8 hours, the bearer may treat it as a +1 magic weapon until the end of their next long rest',
    'When the bearer attunes this item, choose a harmless object within sight such as a tea cup, a ball of yarn, or a hairpin. If the bearer is touching the item, they may use an action to transform the weapon in or out of this form.',
    'Whenever the bearer takes a dodge or disengage action, they may move an additional 5 feet that round.',
    "While underground, the bearer of this item always knows the item's depth below the surface and the direction to the nearest path leading upward.",
    'The bearer may use an action to release divine magic within, equivalent to a level 1 Cure Wounds spell being cast on all creatures (friend or foe) within 5 feet of the bearer. The weapon is destroyed and loses all magical properties.',
    'As an action you make this weapon appear to others as a similarly shaped and sized object of your choice. Anyone interacting with the weapon instantly realizes its true nature and if you make an attack with the weapon others see it for what it truly is. With another action you can make it appear to be a weapon again.',
    'This weapon gains a +1 bonus to damage rolls against constructs.',
    'The bearer gains one language proficiency chosen by the DM.',
    'As an action you command the weapon to point in the direction of the closest source of water.',
    'Treat as a +1 weapon when attacking Dragons.',
    'When the bearer makes a successful attack with this weapon, they gain 10% of the damage as temporary hit points (round down, minimum of 1).',
    'The bearer can read books they are touching while sleeping.',
    'The bearer always knows the direction to the nearest tavern in a 60 mile radius.',
    'When the bearer is outdoors, harmless creatures such as squirrels and birds flock to them when they sing songs for a minute or longer.',
    'The bearer does not require an interaction to draw or sheath this weapon',
    'The bearer of this weapon is firmly rooted to the ground. When standing on solid earth or stone, if an effect would move the bearer against his will the distance is reduced by 5 feet.',
    'The bearer gains +1 to wisdom saving throws.',
    'This weapon takes only one minute to attune.',
    'The bearer can use this item to cast the Light cantrip on itself at will. While lit, it deals radiant damage instead of its usual damage type.',
    "Dark apparitions bound to this weapon haunt the edges of the bearer's peripheral vision, becoming hideously visible to devour the bodies of beings slain by this weapon. Once 666 bodies have been devoured, the apparitions will be released to prey upon our world and the sword becomes a permanent +3 weapon. So far, the weapon has eaten 1d6 x 100 + 3d20 bodies.",
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever an elemental is within 100 feet of it.',
    'This weapon gains a +1 bonus to damage rolls against elementals.',
    'Treat this as a +1 weapon as long as the bearer is enchanted by a spell from the enchantment school of magic.',
    "Once per long rest, the bearer may spend one minute contemplating the patterns etched on this weapon's surface and regain 1 expended ki point.",
    'The bearer has advantage on investigation checks to see through illusions. In addition the bearer can gains advantage on an Insight check to check if someone is lying and disadvantage on all Deception checks.',
    'When attuned to neutral aligned characters, this weapon has a +1 attack bonus during the day and a +1 damage bonus at night.',
    "Ancient glyphs adorn the surface of this weapon, telling a story with a moral of the player's chosing (such as 'One good turn deserves another' or 'United we stand, divided we fall'). While attuning to this weapon, the glyphs spread across the entire skin of the bearer and the moral of the story becomes a bond trait for this character.",
    'You may add 1d10 to a damage roll made with this weapon. You cannot use this ability again until you complete a long rest.',
    'As a bonus action you may gain advantage on your next attack roll made before the end of your next turn. You cannot use this ability again until you complete a long rest.',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever a construct is within 100 feet of it.',
    'As an action you can cast disguise self (spell save DC 13). You cannot use this ability again until you complete a long rest.',
    'Treat this as a +1 weapon if the bearer has more than half of their maximum hit points',
    'Once per short rest, when the bearer crits with this weapon they gain inspiration.',
    'Once per long rest, the bearer may roll a saving throw with advantage.',
    'The bearer may use their reaction to reduce fall damage by 1d6 until the end of turn. They cannot use this feature again until completing a long rest.',
    'As an action the weapon can turn a small, worthless, unattended, organic object (such as a clump of dirt) into a bland, edible substance. This substance provides enough food to feed a Small or Medium sized creature for one day. You cannot use this ability again until you complete a long rest.',
    'The weapon sheds 30 feet of bright red light and another 30 feet of dim light after that whenever a fiend is within 100 feet of it.',
    'This weapon gains a +1 bonus to damage rolls against fiends.',
    'The bearer may spend an action beseaching the spirits within this weapon. Roll a DC 20 Persuasion check or make a sufficiently impassioned plea. If successful, the spirits will sacrifice themselves so that for the next minute the next attack with this weapon will be a crit. The weapon then loses this property forever.',
    'The bearer gains a +1 bonus to initiative rolls. As long as the bearer is first in the initiative order, their speed increases by 5 feet.',
    'As an action you can make the weapon shed bright light in a 10-foot radius and dim light in another 10 feet. You can use another action to make the weapon stop shedding light.',
    'As a bonus action you gain advantage on your next ability check made before the end of your next turn. You cannot use this ability again until you complete a long rest.',
    'As a action you may gain advantage on your next attack roll made before the end of your next turn. You cannot use this ability again until you complete a short rest.',
    'The bearer may choose to deal Force damage with this weapon and gain a +1 bonus to damage.',
    'The bearer may spend an action to attempt to ignite the old magic in this weapon with a DC 13 Charisma check. If successful, treat the weapon as a +1 weapon as long as the bearer maintains concentration on this effect, maximum 10 minutes.',
    'Contains 1d4 unreplenishable charges of the Animal Friendship spell (1st level).',
    'The bearer may choose to deal Cold damage with this weapon and gain a +1 bonus to damage.',
    'Treat as a +1 magic weapon when the bearer is raging.',
    'Whenever the bearer crits with this weapon, it gains the reach property (10 ft) for 1 minute. If it already had the reach property, increase its reach by 5 ft.',
    'This weapon can be wielded by a missing limb. If so, it becomes a +1 weapon.',
    'This weapon gains a +1 bonus to damage rolls against giants.',
    'The bearer may choose to change the damage type of weapon to Radiant and its damage roll gains a +1 bonus.',
    'Once per short rest, when the bearer crits with this weapon it casts Compelled Duel on the creature it hit, DC 12.',
    'This weapon gains a +1 bonus to damage rolls against undead.',
    'When the bearer attunes this weapon they must choose a being in their mind. Henceforth, if the bearer is within 5 feet of the chosen being they may use their reaction to impose disadvantage on an attack roll against that creature. They cannot do this again until they have finished a short or long rest.',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever a giant is within 100 feet of it.',
    'As an action you can cast minor illusion (spell save DC 13). You cannot use this ability again until you complete a short or long rest.',
    'As long as it is on the same plane of existence, the bearer can hear through this weapon as if they were present.',
    'Smoke rises from this weapon revealing the apparitions that haunt it. They lash out at living targets every time the bearer scores a hit, doing an additional +2 necrotic damage.',
    'As an action you can heal 1d4+1 hit points. You cannot use this ability again until you complete a long rest.',
    'This item contains a healing node. Once per long rest the bearer can use the node and an action to heal 1d4 hit points at touch range.',
    'Ancient heroes have wielded this weapon throughout the ages, and their courage still lingers. The bearer has advantage on saving throws vs. fear effects.',
    'When the bearer of this item rolls hit dice, they can choose to re-roll them and take the second result.',
    "As an action you can cast ray of frost. You gain a +5 bonus to the spell's attack roll. You cannot use this ability again until you complete a short or long rest.",
    "The weapon is inscribed with holy symbols of the God of the DM's choice. A cleric or paladin that serves that god may use this weapon as a divine focus.",
    'As an action you can cast light. You cannot use this ability again until you complete a short or long rest.',
    "Once attuned, this weapon exists only in the bearer's imagination until held with intent to do harm. It becomes imaginary again after a short rest.",
    'Once per long rest, the bearer may spend an action to activate an ancient mechanism within the weapon. Gears turn and parts shift as the weapon reconfigures itself into a more menacing version of the original. For 1 minute, attacks made with this weapon ignore resistances (but not immunities).',
    'The bearer no longer feels emotions. They have immunity to fear effects but disadvantage on Insight and Performance checks, and cannot Rage.',
    'When the bearer is grappled by multiple targets, they may choose to break the strongest grapple. If they succeed, then all grapples are broken.',
    'The bearer gains their Constitution modifier in temporary hit points whenever they gain or use inspiration.',
    'Once hit by this weapon, the victim cannot regain hit points until the beginning of their next turn.',
    'Once per short rest, when the bearer crits with this weapon it casts Crown of Madness on the creature it hit, DC 12',
    'As an action you can cast jump on yourself. You cannot use this ability again until you complete a long rest.',
    'Contains 1d4 unreplenishable charges of the Jump spell (1st level).',
    'Contains 1d4 unreplenishable charges of the Silent Image spell (1st level).',
    'As an action you can cast mage hand. You cannot use this ability again until you complete a short or long rest.',
    'As a reaction you may gain a +1 bonus to AC which lasts until the start of your next turn. You cannot use this ability again until you complete a short or long rest.',
    'You can reroll a natural 1 rolled on a d20 for an ability check, attack roll, or saving throw. You cannot use this ability again until you complete a long rest.',
    'Ignores the AC bonuses given by spells such as Mage Armor and Shield.',
    'Contains 1d4 unreplenishable charges of the Bane spell(1st level).',
    'This weapon does an additional 1d4 damage on attacks of opportunity.',
    "Once per short rest, when you crit with this weapon it casts Command on its target with the word 'grovel', DC 12",
    'The bearer and all of their posessions are completely odorless.',
    'Contains 1d4 unreplenishable charges of the Unseen Servant spell (1st level).',
    'A gentle kaleidoscope of butterflies always accompanies this weapon. The bearer has advantage on persuasion checks with Fae creatures less than CR 3.',
    'When the bearer kills a monster with this weapon, treat this weapon as a +1 weapon whenever you fight another monster of this kind. When the weapon is unattuned, it loses its memory.',
    'As an action you can cast spare the dying. You cannot use this ability again until you complete a short or long rest.',
    'As an action you can cast message. You cannot use this ability again until you complete a short or long rest.',
    "When the bearer places this weapon beside another melee weapon for 1 minute, this weapon changes weapon type, size, and physical qualities to become an exact replica of the other weapon. It does not gain any of the other weapon's magical properties.",
    'This weapon disrupts all telepathic communication within 20 feet. Psychic attacks are not affected.',
    'The bearer may choose to deal Psychic damage with this weapon and gain a +1 bonus to damage',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever a monstrosity is within 100 feet of it.',
    'This weapon gains a +1 bonus to damage rolls against monstrosities.',
    "The bearer's vital signs, such as a pulse and breathing, are masked by this weapon and are undetectable by non-magical inspection.",
    'Contains one charge of the Speak With Dead spell. It regains the charge when the bearer dies.',
    'When the bearer reduces a creature to zero hit points they may use a bonus action to move half their movement speed towards another hostile creature.',
    'The bearer gains +1 to constitution saving throws',
    "Once per long rest, the bearer may lay this weapon beside a bowl of water. After a moment, the bowl of water will begin to boil and after a minute it will transform into a hot meal of special significance to the bearer (Their mother's noodle soup or father's elk stew). Eating this delicious meal is so satisfying that it counts as nourishment for an entire day and restores 1d4 hit points. To anyone other than the bearer, the bowl and its contents appears unchanged.",
    'Any spell of 1st level or lower that includes the bearer as a target has a 10% chance to fail, cast by both friendly and enemy spellcasters.',
    'This weapon gains a +1 bonus to damage rolls against oozes.',
    'Treat this as a +1 weapon for 1 minute if the bearer takes 13 or more damage in a single round of combat.',
    'As an action you can cast detect magic. You cannot use this ability again until you complete a long rest.',
    'The bearer may use their reaction to gain a +1 AC bonus until the end of the turn.',
    'Whenever the bearer readies an action, they have advantage on constitution saving throws to maintain concentration.',
    'The bearer may choose to deal Poison damage with this weapon and gain a +1 bonus to damage.',
    'Damage inflicted with this weapon leaves no physical sign of injury, such as cuts and bruises, and draws no blood.',
    'The bearer may spend ten minutes paying honor to the spirits that govern this weapon, shaving their head in tribute. Once the ceremony is finished, it becomes a +1 weapon until the end of the next long rest. They must wait 10 days until they have long enough hair to re-enact this ritual.',
    'As an action you command the weapon to point in the direction of the closest gem worth 50 gp or more.',
    "This weapon increases the bearer's Channel Divinity range by 5 feet.",
    'As an action you can control flames. You cannot use this ability again until you complete a short or long rest.',
    'Every time the bearer takes a long rest, this weapon changes in appearance and function. It retains this property but any other properties are lost. However, it gains a new random ability from this chart.',
    'The bearer may use a bonus action to change the form of the weapon to any other simple or martial melee weapon. It always counts as a silvered weapon no matter what form it takes.',
    'The bearer may change the damage type of a spell they cast once per long rest.',
    'As an action you can cast comprehend languages. You cannot use this ability again until you complete a long rest.',
    'This weapon is so finely constructed it never needs maintenance, cannot rust or tarnish, and gains a +1 to damage rolls.',
    'When attacking with this weapon, crit fails (rolling 1) on attack rolls do not automatically miss the target.',
    'Once per long rest, the bearer may gain +1 to any skill check.',
    'As an action you can cast mending. You cannot use this ability again until you complete a short or long rest.',
    'As an action you can gain resistance to all damage types until the end of your next turn. You cannot use this ability again until you complete a long rest.',
    'The bearer can spend an action and 1 ki point to treat this as a +1 weapon for 1 minute.',
    'This weapon only deals non-lethal damage to living targets',
    'Treat this as a +1 weapon during the day when attuned to a good aligned character.',
    'A ruby worth 30gp is the center stone in a rose-shaped setting on the weapon. If the bearer removes the ruby, the weapon grows a new one at the end of the month. The weapon always smells of roses while the ruby is in its setting.',
    'Whenever bearer casts a spell, treat this weapon as a +1 weapon until the beginning of their next turn.',
    'You gain advantage on a saving throw. You cannot use this ability again until you complete a long rest.',
    "This weapon perpetually drips the blood of a monstrous race, chosen by the DM. The bearer can speak that race's language and has advantage on intimidation checks against monsters of that race when the weapon is revealed.",
    'This weapon does maximum damage against man-made, inanimate objects.',
    'You may add 1d4 to a damage roll made with this weapon. You cannot use this ability again until you complete a short or long rest.',
    'The bearer suffers no harm or discomfort in temperatures as high as 120 degrees Fahrenheit.',
    'Treat as a +1 magic weapon when in dim light.',
    'Whenever the bearer is casting a spell as a ritual, they have advantage to maintain concentration during the ritual.',
    'Any humanoid creature hit with this weapon loses all of the hair on their head and face.',
    'As a reaction you may gain a +1d4 bonus to AC that lasts until the start of your next turn. You cannot use this ability again until you complete a long rest.',
    'This item contains 1d4 unreplenishable charges of the Shield spell.',
    "As an action you can cast fire bolt. You gain a +5 bonus to the spell's attack roll. You cannot use this ability again until you complete a short or long rest.",
    'This weapon falls up instead of down. Its weight does not contribute towards encumberance.',
    'Treat as a +1 weapon when attacking Demons and Devils.',
    'The bearer may choose to deal Fire damage with this weapon and gain a +1 bonus to damage.',
    'This weapon contains a small, secret compartment. A character must succeed on a DC 20 Wisdom (Perception) check to reveal the compartment when searching the bearer.',
    'A poem, story, or map that describes a long-forgotten treasure that will make this weapon more powerful is etched on the surface of the weapon.',
    'The bearer may spend an action to stabilize a dying creature within 5 feet. They cannot do so again until they have completed a long rest.',
    "A powerful malevolent being is bound within this weapon and it will be released upon the weapon's destruction.",
    'The bearer gains +1 to dexterity saving throws.',
    "The weapon contains a pool of healing energy that can restore up to 30 hp. The bearer may use an action to plant this weapon in the ground and release this energy. While planted and undepleted, creatures that end their turn within 10 feet of the weapon are showered in warm rain that restores 1 hp per round. A long rest restores 1d6 hp of energy to the weapon's pool.",
    "Anyone except the bearer must attempt a DC 10+x Charisma check to pick up this weapon, where x is the bearer's level. Any attack made with this weapon against the bearer has disadvantage.",
    'As an action you teleport 10 feet to a space you can see. You cannot use this ability again until you complete a long rest.',
    'Treat this as a +1 weapon when attacking Aboleths and other creatures from the Far Realm',
    'Whenever the bearer breaks a grapple, they may choose to push the grappler up to 10 feet away from them as a bonus action.',
    'Contains 1d4 unreplenishable charges of the Longstrider spell (1st level).',
    "The weapon contains a resevoir of scorching light that can deal up to 30 hp of radiant damage. The bearer may use an action to plant this weapon in the ground and release this energy. While planted and undepleted, creatures that end their turn within 10 feet of the weapon are brightly illuminated and seared for 1 radiant damage per round. A long rest restores 1d6 hp of energy to the weapon's resevoir.",
    'The bearer may use a bonus action to gain advantage to Wisdom (Medicine) checks for the rest of the turn.',
    'If the bearer is first in the initiative order, they may treat this as a +1 weapon.',
    'When the bearer takes a long rest, they gain back one additional hit die.',
    "The bearer may lay 10 gold coins along the surface of the weapon and pray to a God of their choice for 10 minutes. At the end of this ritual, the weapon becomes a +1 weapon until the next long rest and the 10 gold coins are permanently gone. This boon will be lost if the bearer acts in a way that is contradictory to that deity's teachings.",
    'As an action you can command the weapon to point in the direction of the closest settlement of humanoids with a population over 100.',
    'Over the course of a long rest, the bearer may transfer the other magic properties of this weapon to a melee weapon of their choosing. This weapon then loses those properties.',
    'The bearer gains an extra level one spell slot, which recovers only after a full moon rises.',
    'Treat this as a +1 weapon if the bearer has half their maximum hit points or less.',
    'Once per short rest, when the bearer crits with this weapon, all creatures other than the bearer within 5 feet of the target (including the target) must roll a DC 12 constitution saving throw or be knocked prone by a wave of concussive force.',
    "Once per short rest, when you crit with this weapon it casts Hex on the target. Roll a d6 to determine which of the target's attributes is weakened. The bearer cannot transfer the curse to another creature.",
    'Whenever the bearer of this weapon takes a help action in combat, the aided ally may treat their weapon as a +1 magic weapon until the end of their next turn.',
    "Whenever the bearer kills a creature with this weapon, they gain temporary hit points equal to the creature's CR (minimum of 1).",
    'The bearer gains +1 to their Passive Perception.',
    'Treat this as a +1 weapon at night when attuned to an evil aligned character.',
    'Everytime you crit with this weapon, it gains 1 charge. As a bonus action, use a charge to make this a +1 weapon for 1 minute. All charages are lost at the end of a long rest.',
    "The weapon does an additional 1 elemental damage based on the color of the bearer's eyes: (amber: lightning, black: necrotic, blue: cold, brown: acid, green: force, gray: thunder, hazel: poison, purple: psychic, red: fire, white: radiant)",
    "The bearer's maximum hit points increases by their constitution modifier while attuned to this item. These hit points are lost when the bearer unattunes the item.",
    "This weapon cannot be detected by the 'Detect Magic' spell unless the caster touches the weapon.",
    'Whenever the bearer deals damage to a creature, this weapon gains a charge. As a bonus action, the bearer can use any number of charges to deal that much extra lightning damage on their next attack. If a round (6 seconds) goes by and the weapon has not struck a foe, it loses all charges.',
    'The bearer can use an action to amplify their voice three times louder than normal.',
    'Once per long rest the bearer may draw a 20 foot line in the ground with this weapon that lasts for 1 minute. The Undead must succeed on a DC 12 wisdom saving throw to move across this line. If they fail, they cannot move again until their next turn.',
    'of Exuberance',
    "Whenever the bearer casts a spell, this weapon gains charges equal to the spell's level. The bearer can use a bonus action to remove 13 charges and make this a +1 weapon until the start of the next round. All charges are lost during a long rest.",
    'The bearer gains +1 to charisma saving throws.',
    'As an action you can cast gust (spell save DC 13). You cannot use this ability again until you complete a short or long rest.',
    'The bearer gains +1 to strength saving throws.',
    'Once per long rest, the bearer may use an action to transform this weapon into a magical raven that can deliver a message to anyone in a 50 mile radius, provided the bearer knows their name and face. When the raven returns, it reverts into its weapon form. If the bird should die en route, it reverts into weapon form and unattunes from the bearer.',
    "The weapon contains a resevoir of ice magic that can a freeze the ground for up to 30 seconds. The bearer may use an action to plant this weapon in the ground and release the ice magic within. While planted and undepleted, the ground in a 10 foot radius of this weapon becomes difficult terrain. A long rest restores 1d6 seconds of energy to the weapon's resevoir.",
    'This weapon does maximum damage against plant creatures.',
    'This weapon gains a +1 bonus to damage rolls against dragons.',
    'The weapon sheds 30 feet of bright light and another 30 feet of dim light after that whenever a dragon is within 100 feet of it.',
    'Treat this as a +1 weapon for 1 minute after meditating with it for 1 minute.'
  ]
  var prefixWeaponRoll = random(1, propertyWeapon.length)
  var suffixWeaponRoll = random(1, propertyWeapon.length)
  Object.assign(weapon, {
    type: weapon.seededrandom(),
    prefixWeapon: prefixWeapon[prefixWeaponRoll],
    suffixWeapon: suffixWeapon[suffixWeaponRoll],
    prefixProperty: propertyWeapon[prefixWeaponRoll],
    suffixProperty: propertyWeapon[suffixWeaponRoll]
  })
  weapon.description = weapon.prefixProperty + ' ' + weapon.suffixProperty
  weapon.name = weapon.prefixWeapon + ' ' + weapon.type + ' ' + weapon.suffixWeapon
  return weapon
}
