/* global setup */
setup.misc = {
  'cheese': {
    create: function () {
      var cheese = {
        colour: setup.misc.cheese.colour.random(),
        texture: setup.misc.cheese.texture.random(),
        taste: setup.misc.cheese.taste.random(),
        smell: setup.misc.cheese.smell.random(),
        cost: setup.misc.cheese.cost.random()
      }
      return cheese
    },
    colour: ['pale grey, with dark flecks', 'bright yellow', 'warm yellow', 'spotty yellow', 'pale yellow', 'light green', 'light greenish-yellow'],
    texture: ['crumbly, with a texture similar to plaster', 'rubbery, and squeaks while you eat it', 'rubbery, and squeaks rather disconcertingly while you eat it', 'crumbly, with bits going everywhere', 'somewhat rubbery', 'somewhat stringy', 'slightly stringy', 'rubbery, like a piece of leather that has been soaking in some greasy sludge', 'soft and spongey, with the occassional... crunch', 'soft, springy, and moist', 'gooey', 'moist and delicious', 'almost liquid once you bite through the rind'],
    taste: ['sharp', 'sharp and salty', 'somewhat bland', 'inoffensively mild', "salty, like a cow's salt-lick", 'rich and creamy', 'creamy, with hints of oak', 'strong, slightly salty, and extremely more-ish', 'smokey, with hints of rum', 'smokey, with hints of chili', 'salty, but immediately the spice from the peppers takes over', "bitter, with the rind tasting somewhere between a burnt log and dead bug, but the taste isn't entirely unpleasant", "a warm and smooth creaminess which envelopes your taste buds like a mother's embrace"],
    smell: ["pungent, as if it was the result of somebody's terrible diet decisions", 'somewhat sweet, with a heady aroma', 'like the ass of a cow in cheese form', "like the best parts of a farm's stable", 'like freshly baled hay', 'like freshly cut grass', 'like a lemon tree', 'like fresh cream', 'like a rotting corpse', 'like a roast duck filled with spices', 'like a delicious slice of bread toasted over a fire', 'like a slice of bread left in the fire far too long'],
    cost: [1, 2, 3, 4, 5, 6, 6, 6, 7, 7, 7, 8, 9, 10, 10, 10, 11, 11, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
  },
  'newspaper': [
    'NPC attempts to become player, ridiculed.',
    'Underground homunculi fights discovered - homunculi sales increase.',
    'Wizard house vanishes in the night, locals suspect shenanigans.',
    "Doppelganger discovered in mayor's place. Townsfolk agree he's better than the old.",
    'Tiefling, dragonborn, and hobbit visit tavern, local economy booming. (Adventures visited)',
    "Werewolf suspected to live in town, buy your silver at Jameson's general store!",
    "Goblins threaten to kill all townsfolk, distracted by 'shiny things'",
    'Dragon flies over town, local illusionist jailed.',
    'Lawyer discovered to be vampire, surprising no one.',
    'Dwarf and human proclaim love, refused wedding ceremony by cleric.',
    'Dragon rider gives birth to half dragon.',
    "Centaur's father jailed for bestially.",
    'Cultists file for rights to be called clerics.',
    "Forest gnome discovered in wood elf elementary school, been 'stealing our food for years.'",
    'Portal to elemental plane discovered, hot springs are rejuvenating says discoverer.',
    "Fey found making old man's shoes, old man to be jailed for slavery.",
    "Jack steals gold from 'giant in sky' giants pissed.",
    'Necromancer family man caught trying to raise a family.',
    'Drunken old ramblings of future discovered to be 90% accurate.',
    'Dragonborn day-care suspected to be kobold infiltration team.',
    "Local dungeon deliver finds 'artefact with a demonic presence' leaves it due to lack of modifiers.",
    'Travelling circus to visit soon.',
    'Farmer discovers wishing well works.',
    'Druid makes farm animals talk, town goes vegetarian.',
    'Druid threatens to awaken plants.',
    'House pet discovered to be archdruid.',
    "30 year old half elf sick of 'being treated like a child.'",
    'Low level adventurers causing trouble in town; seeking rat infested basement to start them on a long quest.',
    'Lost: Pet invisible stalker, if found return to Wash gust (Wizard). Poster includes a picture of the pet',
    'Small medium at large; a poster for an escaped gnomish diviner',
    'Familiars getting too familiar? Please spay or neuter your animal companions.',
    "'Blurry face of something, angel or demon? Who knows' Do you trust your sight? MADD Magicians Against Drunken Divining.",
    "St. Cuthbert's school of phrenology and trepanning",
    "'Beware of doppelgangers!'",
    "'Local wizard went missing after experimenting with a bag of holding'",
    "'You will not believe your eyes when you read what this Halfling found in a dungeon!!!'",
    "'Apprentice sorcerer blew up himself and started a forest fire'",
    "'Thieves' guild revealed to be just a rumour'",
    "'Gnome banished from town after drinking 200 potions of inappropriate yodelling'",
    "'Banshee was still alive hours before she died!'",
    "'City unsure why the sewer smells.'",
    "'City guard's raid smithy, find +1 weapons'",
    "'Goose attacked by aggressive dog, goose refused medical treatment.'",
    "'Ilitrasee an obstakul for billboards, studee finds.'",
    "'Group of adventurers mugged by a parrot.'",
    "'Guard investigation reveals suspicious gold coin to be a copper coin.'",
    "'Cows lose their jobs as milk prices drop'",
    'Seeking apprentice cook/tavern staff',
    'Seeking wizard to remove awaken from my pots and broom.',
    'Local wizard apprentice blamed for recent flood, discovered to be awakened mouse',
    "'Local merchant arrested for selling mimics disguised as furniture and appliances, scheme discovered after customer noticed his refrigerator was running.'",
    "'Rampaging beast destroys slum, townsfolk celebrate new town square.'",
    'Local instrument shop has massive blowout on Large-sized Lutes, due to a hilarious misunderstanding with local adventurers.',
    "Help! Help! I'm being held here and made to write these signs!",
    "Fourth-annual dwarf-throwing competition dissolves into chaos, bloodshed. 'We're looking forward to the fifth year!' says local dwarven merchant.",
    "Bloodknife the Deathrager, level 20 Barbarian, buys local farm. Interviewed while re-forging a sword into a ploughshare, he said 'My DM doesn't support Epic levels.'",
    "Strange ill rumours heard from those fleeing from the north. 'Probably nothing,' agrees city council.",
    "Local wizard's attempt at opening a portal to the Plane of Uncertain Outcomes has succeeded and failed.",
    "Local church erupts into violence over the usage of non-blunt weaponry among clergy. 'What's next,' cried a local priest, 'Paladins with no alignment restrictions?!'",
    'Magical cobblers continue to take heavy losses on sales of Boots of Striding and Springing. Demand continues to drop as more editions are released.',
    "Copyright permit for 11-foot pole denied by local council. 'It IS different!' cried the merchant, as he was escorted from the premises.",
    "Market share for d12 weapons at an all time low. A local blacksmith was reached for comment, 'Orcs just ain't buyin' no more.'",
    "A local village has reached a settlement to recompense a magical tailor for injury and losses sustained after the villagers ran him out of town. The elder of the village said, 'We thought t'were one of them parables! Turns out he does sell invisible cloth. We're truly sorry.'",
    "Dairy farmer to begin offering 'milk for the Khorne flakes'. In an interview, he says 'Well, I began by getting Chaotic Evil cows.'",
    "Orcs-no-eat insurance! You want not get eat, you pay us gold. Our motto are, 'Your money or you get eat.'",
    "A local scientist claims 'Humans are slowly being replaced.' He went on to state that, 'These so-called 'variant humans' look exactly like us, and it is nearly impossible to tell if someone you know is one.'",
    'The town of Westbrynn is under investigation after allegations surfaced that they are offering incentives for higher level creatures to move into the area. Authorities were tipped off after shipments of +5 weapons were intercepted on their way to the town.',
    'Steampunk genres threaten takeover. Coastal wizards decline to comment',
    'Lvl 3 familiars unionized! Necromancers at a loss for words',
    'Gravity subject to change over the next few weeks: alchemists give assurances',
    'Due to the recent rise in tectonic activity, all elemental mages are advised to avoid using materials near riverbanks and volcanoes',
    'Dragon scale market plummets as advances in metalwork create stronger materials',
    "Recent reports confirm health potions to cause loss in bone density. Heavy users of these potions argue that they usually don't live long enough to be effected",
    "Theoretical alchemists argue the universe was created in a failed transmutation event coined 'The Big Bang'",
    "'Local gangsters are putting up false notice boards to an excess.'",
    'Kobold seeks dragon wing for no particular reason.',
    'Local human scholar in need of parchment urgently.',
    'Gnome mystic requires escort to deathly swamp.',
    'Family wedding requires cooks. Will eat any one thing.',
    'The Order of the Magi requires help in procuring the whereabouts of Magus Ornathuss.',
    'Animated sword seeks better life; tired of being used in one way relationship.',
    'Half-elf Baron Faelin Merrybrook found dead at his home. An investigation is still ongoing.',
    'Finals of the annual tavern brawl to take place tomorrow!',
    'Doppelganger suffering from identity crisis trying to find purpose in life.',
    'The Wandering Troupe in town for two days only! Have the minstrels on the run from a bunch of bandits they fleeced and inadvertently involve the characters in their acts.',
    'Local farmer requires assistance. I am unable to pay you for your troubles I am afraid.',
    'Dwarf having some trouble removing a ring. The ring is actually a symbiotic ring and has fused with its new owner. It responds well to gluttony, which the dwarf is afflicted by. As the dwarf becomes more charitable, the ring loosens. If anyone wants to wear the ring, it gives 10 temporary hit points at dawn, each day.',
    'Waresloth seeking help on slow nights.',
    'Dwarf tossing championship at local tavern, bring your own dwarf.',
    'Three gnomes in long coat arrested for impersonating human.',
    "Trigeraian's Used Armour: Eh, it should serve you better than the previous wearer.",
    'Castle executioner found using illegal muscle enchantments.',
    'Local elven leader, famously against interracial breeding, found in orc brothel.',
    "Charngroc's Custom Chimeras: personalized pets for any personality.",
    "Local oracle revealed to be fraud. 'I just wanted to make a prophet' he says.",
    'A Capella singing competition finished. Winner was a buomman asking for directions.',
    "Adventurer teaches blink dog Common. 'Wow. Very language.' comments dog.",
    'Unidentified kobold mage summons sarrukh. Apocalypse scheduled for 6 PM.',
    'Evil Lich Necromancer escaped prison. Wanted dead or alive.',
    'Impersonator discovers his house is a mimic'
  ],
  'patreonCharacters': [
    {
      firstName: 'Tylien',
      lastName: 'Birchbottom',
      /* name: "Tylien Birchbottom", */
      gender: 'man',
      age: 'about twenty four',
      ageYears: 24,
      race: 'halfling',
      dndClass: 'warlock',
      height: 'rather diminuitive',
      heightRoll: 34,
      weight: 'small and light',
      idle: ['gently whispering to his petrified mouse', 'writing something in a well-worn notebook'],
      background: 'outlander',
      hairColour: 'brown',
      hairType: 'wispy',
      scar: 'lashes on his back that have scarred over',
      physicalTrait: 'lashes on his back that have scarred over',
      trait: 'constantly forgets things, and has to write things down in his journal to be able to remember them properly.',
      greeting: ['nods at you', 'welcomes you warmly', 'smiles and greets you', 'raises a hand with a wave'],
      dndClassOrigin: "I've been making a decent living hunting game, selling the pelts to the blacksmith for spare change. I'm searching for a cure to my memory decay- every day, I have to write more things down. I need to learn why these things are happening to me... To find out who or whatever the beast of shadows that stalks me is.",
      backgroundOrigin: "I was kidnapped by a cult at the age of 14. They used me in a ritual to summon an ancient being known as 'the beast of shadows'. Half-way through, guards rescued me. Things got better, and then got a lot worse- I woke speaking tongues, and found myself losing time. As my powers grew, so did my lost time, so I started to keep a journal. Nowadays I can barely remember more than a week into my past now.",
      owner: 'owner',
      calmTrait: 'unintentionally funny',
      stressTrait: 'distant',
      vocalPattern: 'speaks rather quickly',
      note: "Tylien is Patreon supporter Jasher Drake's PC."
    },
    {
      firstName: 'Galder',
      lastName: 'Fendt',
      name: 'Galder Fendt',
      gender: 'man',
      age: 'venerable',
      eyes: 'green',
      ageYears: 84,
      race: 'human',
      height: 'some five and a half feet',
      heightRoll: 66,
      weight: 'slightly pot-bellied',
      hairColour: 'brilliant white',
      scar: 'a faint cut of a Drow dagger from a long-forgotten skirmish',
      beard: 'a quite respectable beard',
      physicalTrait: 'a respectable beard',
      trait: "doesn't like to boast, and lets his enemies' perception of an unassuming old man be their downfall.",
      calmTrait: 'quiet',
      stressTrait: 'distant',
      vocalPattern: 'speaks slowly and deliberately',
      idle: [],
      dndClass: 'wizard',
      background: 'sage',
      dndClassOrigin: '',
      backgroundOrigin: '',
      note: "Galder Fendt is the wizard of /u/SomeHairyGuy, a Reddit user who suffered from advanced pelvic RMS. It's his wish that his character, Galder, be used in games around the world. #CreateAgainstCancer"
    }
  ],
  'religion': {
    holy: [
      'Airborn', 'Almighty', 'Ancient', 'Ascendant', 'Blessed', 'Blue', 'Bronze', 'Burning', 'Ceaseless', 'Celestial', 'Charming', 'Colossal', 'Consecarted', 'Crystal', 'Curing', 'Diamond', 'Emerald', 'Eminent', 'Eternal', 'Ethereal', 'Everlasting', 'Fabled', 'Famous', 'Feathered', 'Flaming', 'Floating', 'Flying', 'Forceful', 'Gentle', 'Ghostly', 'Glass', 'Glorious', 'Glowing', 'Golden', 'Granite', 'Green', 'Grey', 'Healing', 'Heavenly', 'Holiest', 'Holy', 'Illuminated', 'Inexorable', 'Invincible', 'Just', 'Learned', 'Legendary', 'Life', 'Lighted', 'Lightning', 'Lofty', 'Long Lost', 'Lost', 'Lucky', 'Medicinal', 'Mighty', 'Moonstone', 'Oaken', 'Peaceful', 'Pious', 'Platinum', 'Praising', 'Pristine', 'Radiant', 'Red', 'Reflecting', 'Regenerating', 'Restoring', 'Righteous', 'Sacred', 'Sanctified', 'Sapphire', 'Secret', 'Shielding', 'Shining', 'Silk', 'Silver', 'Singing', 'Skyborn', 'Soaring', 'Steel', 'Stone', 'Storied', 'Sunstone', 'Thundering', 'Titanic', 'Unstoppable', 'Untouchable', 'Unyielding', 'Virtuous', 'Vorpal', 'Warding', 'Watchful', 'Whistling', 'White', 'Wind', 'Winged', 'Wise', 'Wooden', 'Yellow'
    ],
    unholy: [
      'Abyssal', 'Acid', 'Ancient', 'Ashen', 'Black', 'Blackened', 'Blacksteel', 'Blasphemous', 'Bloodstone', 'Bony', 'Brass', 'Brutal', 'Burning', 'Callous', 'Chained', 'Charming', 'Clawed', 'Crawling', 'Cruel', 'Cursed', 'Dark', 'Darkstone', 'Deathly', 'Decaying', 'Desecrated', 'Diseased', 'Disentegrating', 'Dragonfang', 'Dragonscale', 'Eternal', 'Exploding', 'Fabled', 'Fallen', 'Fell', 'Flaming', 'Flying', 'Forgotten', 'Frightful', 'Ghostly', 'Ghoulish', 'Glass', 'Gloom', 'Golden', 'Grey', 'Hellborn', 'Hellish', 'Hellish', 'Howling', 'Indomitable', 'Infamous', 'Infernal', 'Iron', 'Irresistible', 'Jade', 'Jagged', 'Leathery', 'Legendary', 'Lightning', 'Lost', 'Magma', 'Mighty', 'Moonstone', 'Necrotic', 'Obsidian', 'Poisoned', 'Profane', 'Rotting', 'Ruby', 'Rusty', 'Sacred', 'Scaly', 'Secret', 'Serrated', 'Shadow', 'Silver', 'Sinking', 'Slithering', 'Sly', 'Smoky', 'Spectral', 'Spiked', 'Starborn', 'Stone', 'Thorny', 'Thundering', 'Toothy', 'Tormenting', 'Tricky', 'Tyrranical', 'Undying', 'Unholy', 'Unlucky', 'Vain', 'Vile', 'Watchful', 'Whispering', 'Wicked', 'Winged', 'Wounding', 'Yellow'
    ],
    nouns: [
      'Amulet', 'Ark', 'Arrow', 'Axe', 'Baldric', 'Barrel', 'Basin', 'Belt', 'Blade', 'Bones', 'Boots', 'Bow', 'Bowl', 'Bracers', 'Breastplate', 'Buckler', 'Candle', 'Chainmail', 'Chains', 'Chalice', 'Chest', 'Circlet', 'Claw', 'Cloak', 'Coat', 'Coffin', 'Crown', 'Cudgel', 'Cup', 'Dagger', 'Drum', 'Ear', 'Earrings', 'Epistles', 'Feather', 'Finger', 'Flail', 'Flute', 'Foot', 'Gauntlets', 'Gem', 'Globe', 'Goblet', 'Hammer', 'Hand', 'Harp', 'Helm', 'Horn', 'Kettle', 'Knife', 'Knot', 'Lantern', 'Light', 'Longsword', 'Mace', 'Mask', 'Mirror', 'Morningstar', 'Nail', 'Necklace', 'Orb', 'Pestle', 'Purse', 'Quarterstaff', 'Quill', 'Ring', 'Robe', 'Rod', 'Sandals', 'Sarcophagus', 'Scab', 'Scales', 'Scepter', 'Scroll', 'Shield', 'Shoes', 'Shortsword', 'Shroud', 'Shrubbery', 'Signet', 'Skull', 'Snout', 'Spear', 'Splinter', 'Spoon', 'Staff', 'Sword', 'Talisman', 'Toe', 'Tome', 'Tongue', 'Tooth', 'Torch', 'Tresses', 'Tunic', 'Vial', 'Wand', 'Wart', 'Whip', 'Wings'
    ],
    namedGod: [
      'Annam', 'Asmodeus', 'Auril', 'Avandra', 'Azuth', 'Bahamut', 'Bane', 'Baphomet', 'Beory', 'Bhaal', 'Boccob', 'Celestian', 'Chauntea', 'Corellon Larethian', 'Cyndor', 'Cyric', 'Daern', 'Demogorgon', 'Deneir', 'Doresain', 'Ehlonna', 'Eldath', 'Erathis', 'Erythnul', 'Fharlanghn', 'Garl Glittergold', 'Gond', 'Gruumsh', 'Halmyr', 'Heironeous', 'Helm', 'Heward', 'Hextor', 'Ilmater', 'Incabulos', 'Ioun', 'Istus', 'Iuz', 'Joramy', 'Kelanen', 'Kelemvor', 'Keoghtom', 'Khala', 'Kord', 'Kurtulmak', 'Kyuss', 'Lathander', 'Leira', 'Liliira', 'Lolth', 'Loviatar', 'Maglubiyet', 'Malar', 'Mask', 'Melora', 'Mielikki', 'Milil', 'Moradin', 'Myrkul', 'Mystra', 'Nerull', 'Obad-Hai', 'Oghma', 'Olidammara', 'Orcus', 'Pelor', 'Pholtus', 'Procan', 'Pyremius', 'Rao', 'Saint Cuthbert', 'Savras', 'Sehanine Moonbow', 'Selune', 'Shar', 'Silvanas', 'Sune', 'Talona', 'Talos', 'Tempus', 'Tharizdun', 'the Raven Queen', 'Tiamat', 'Torm', 'Torog', 'Tymora', 'Typhos', 'Tyr', 'Umberlee', 'Umberlee', 'Urbanus', 'Vaprak', 'Vecna', 'Waukeen', 'Wee Jas', 'Yeenoghu', 'Yondalla', 'Zagyg', 'Zehir', 'Zoser'
    ],
    abstractGod: [
      'Our Lady', 'Our Mother', 'the Ancient Flame', 'the Ancient Oak', 'the Autumn Singer', 'the Bat', 'the Battle-Lord', 'the Bear', 'the Beast', 'the Beast-Tamer', 'the Beast-Wife', 'the Beauty Queen', 'the Blood-Bringer', 'the Burning Man', 'the Crone', 'the Cruel King', 'the Dark Lady', 'the Dark Lord', 'the Dark Prophet', 'the Death Harbinger', 'the Doom Harbinger', 'the Doom-Maker', 'the Eagle', 'the Earth-Mother', 'the Earth-Queen', 'the Enemy', 'the Eternal Light', 'the Eternal Sage', 'the Fair Maiden', 'the Fatespinner', 'the Felled Tree', 'the Fire Dragon', 'the Forest Keeper', 'the Frog', 'the Gloom-Spider', 'the Goddess', 'the Grain-Grower', 'the Great Huntress', 'the Great Protector', 'the Great Smith', 'the Horned One', 'the Judge', 'the King Beneath the Waves', 'the Lawgiver', 'the Life-Keeper', 'the Life-Tree', "the Light's Son", 'the Magic-Maid', 'the Messenger', 'the Mighty Hunter', 'the Mighty One', 'the Mighty Warrior', 'the Mischief-Maker', 'the Moon-Witch', 'the Mountain Forger', 'the Night Queen', 'the Oathkeeper', 'the Oracle', 'the Prophet', 'the Sacred Grove', 'the Savior', 'the Scorpion', 'the Sea Dragon', 'the Sea God', 'the Sea Queen', 'the Seductress', 'the Shadow', 'the Shadowkeeper', 'the Shadow-Serpent', 'the Shield-Maiden', 'the Ship-Taker', 'the Sky Father', 'the Soothsayer', 'the Soul-Collector', 'the Soul-Eater', 'the Spider', 'the Spring Maiden', 'the Starfinder', 'the Stone Dragon', 'the Storm Dragon', 'the Storm King', 'the Storm-Bringer', 'the Summer Mistress', 'the Sunkeeper', 'the Sword-Prince', 'the Thief', 'the Tormenter', 'the Tree Spirit', 'the Undying Light', 'the Unnamed One', 'the Unyielding Tyrant', 'the Voice', 'the Wandering Rogue', 'the War-Maker', 'the Watcher', 'the Watchful Eye', 'the Wind King', 'the Winemaker', 'the Winter Lady', 'the Wolf'
    ],
    saint: [
      'Almar the Holy', 'Amaya the Seeress', 'Bahak the Preacher', 'Bahruz the Prophet', 'Lira the Flamekeeper', 'Mozar the Conqueror', 'Prince Tarunal', 'Queen Kalissa', 'Rahal the Sunsoul', 'Raham the Lightbringer', 'St. Aemilia', 'St. Albus', 'St. Anglos', 'St. Antonia', 'St. Antonus', 'St. Austyn', 'St. Bardo', 'St. Beatrix', 'St. Berta', 'St. Bettius', 'St. Bryenn', 'St. Buttercup', 'St. Carolo', 'St. Cedrick', 'St. Cordelia', 'St. Cowhan', 'St. Cumberbund', 'St. Dorys', 'St. Dreddos', 'St. Dwayn', 'St. Edwynna', 'St. Elayne', 'St. Falstyus', 'St. Farcas', 'St. Florenzo', 'St. Gabrella', 'St. Gaiorgus', 'St. Goodkynd', 'St. Hal', 'St. Halcincas', 'St. Haroldus', 'St. Hemingwar', 'St. Heraclora', 'St. Hermioninny', 'St. Hieronymus', 'St. Inigo', 'St. Jordyn', 'St. Katrynn', 'St. Lannus', 'St. Leo', 'St. Leryo', 'St. Londyn', 'St. Magio', 'St. Marius', 'St. Markuz', 'St. Martyn', 'St. Matromus', 'St. Morrsona', 'St. Morwayne', 'St. Murkel', 'St. Mychel', 'St. Nyneva', 'St. Paolo', 'St. Parrinus', 'St. Perseon', 'St. Petyr', 'St. Podryck', 'St. Polly', 'St. Pratchytt', 'St. Rawynn', 'St. Regus', 'St. Ricarddos', 'St. Roberts', 'St. Robinus', 'St. Rowhan', 'St. Rowlynna', 'St. Sansima', 'St. Sessimus', 'St. Severus', 'St. Stynebick', 'St. Symeon', 'St. Theseon', 'St. Thoryn', 'St. Tolkkyn', 'St. Twayn', 'St. Xavos', 'the Deliverer', 'the Doomcaller', 'the Doomsayer', 'the Lawgiver', 'the Oracle', 'the Prophet', 'the Savior', 'the Seeker', 'the Shadowseer', 'the Soothsayer', 'the Starwatcher', 'the Truthsayer', 'the Voice', 'Zefar the Sorcer'
    ],
    createRelic: function () {
      var adjective = [setup.miscData.religion.holy.random(), setup.miscData.religion.unholy.random()].random()
      var god = [setup.miscData.religion.namedGod.random(), setup.miscData.religion.abstractGod.random(), setup.miscData.religion.saint.random()].random()
      return 'The ' + adjective + setup.miscData.religion.noun.random() + ' of ' + god
    }
  }
}
