/* global setup */
setup.plothook = {
  'joke': [
    "A bard. Not a magic one. Just a bard. Like y'know. A minstrel or some shit he's ok I guess.",
    'Man chasing after a woman through a corn field. Distant saxophone is heard before both get eaten by a troll which chokes to death on them.',
    "The world's highest dragon lands, eats three deer, tries to fly, crashes, then just sleeps where he fell.",
    'A circus is in town. A shitty circus. Like a mobile Chuck E. Cheeses during a power outage.',
    'A village is being savaged by the most passive aggressive wizard ever.',
    'Two heavily armed fighters going at it hammer and tongs in the middle of the road, Every attack is a miss on both sides.',
    "Suddenly ninjas. They don't attack or anything, they have better things to do. But still.",
    "What looks like a sword is stabbed into a stone. Turns out it's just a hilt. Made of tin.",
    "A gnome, a halfling and a dwarf are having a 'who's the shortest' contest. It's fairly easy to resolve and they do so shortly after the party arrives.",
    "A bandit calls for the party to stand and deliver. He's not robbing them, he just really wants his package.",
    "An ugly old man offers the party some of his lunch stew. It's not bad, could use some savory herb or something though.",
    'A young child is crying for his mom. His mom is maybe 40 feet away waiting for the kid to shut up and actually look.',
    'A carrot is near the road. If disturbed a ranger yells at the party for disturbing his rabbit bait.',
    'A rabbit is caught in a trap. If disturbed a ranger yells at the party for disturbing his fox bait.',
    'A fox is caught in a trap. If disturbed a ranger yells at the party for disturbing his wolf bait.',
    'A wolf is caught in a trap. If disturbed a ranger yells at the party for disturbing his bear bait.',
    'A bear is caught in a trap. If disturbed a ranger yells at the party for disturbing his owlbear bait.',
    'An owlbear is caught in a trap. If disturbed a ranger yells at the party for disturbing his ogre bait.',
    'An ogre caught in a trap. If disturbed a ranger yells at the party for disturbing his dragon bait.',
    'A dragon is caught in a trap. If disturbed a ranger yells at the party for disturbing his tarasque bait.',
    "A local child has taken to following the smartest member of the party around asking him 'why' in the most obnoxious voice possible.",
    "A bird poops right down the back of the most wizard-like character's clothes. Haha.",
    // 'A bird poops right in the eye of the most cleric-like character. Haha.',
    // 'A bird poops right on the mouth of the most thief like character. Haha.',
    // "A branch or sign suddenly breaks it's base or chain or string and swings directly into the most wizard-like character's face.",
    // "A lady hobo is telling shitty fortunes for 3 sp a pop. She's got no takers so far.",
    // 'A group of bandits or pirates are dead drunk singing bawdily together off to one side.',
    // 'A group of guards catch and hang a thief who just ripped off the necklace of some girl and stole from a few stands.',
    // "An attractive bar wench starts flirting with the strongest looking male party member. If asked she'll gladly 'spend time' with them. Nothing else worth noting here.",
    // "Town drunk wraps an arm around a party member claiming. 'You'se gais 're al'righ'' before puking on the fanciest dressed character and passing out.",
    // 'Town drunk pukes on the fanciest dressed character and passes out.',
    // 'Worst pickpocket in the world attempts to rob from the character who would most easily notice and deal with them. Mostly he just ends up groping them and the running off.',
    // "Fake wizard claims to be a real one. When questioned he flings glitter in the party's collective face yelling 'Glitterrust!' and running before tripping on his robes and knocking himself out.",
    // 'Hobo claims to be a deposed king who will reward the party if they can return to him his seal which some other hobos stole and are hiding out under the town bridge. He just wants to sleep under the bridge after the party clears the other hobos out.',
    // "Local noble badly disguised as a commonfolk, no one care since he's got money and is a fairly decent person. Snobs if the party tries to talk to them.",
    // 'A short shower of copper bits fall from the sky. Like. 10 of them.',
    // 'A man in a nice set of robes is handing out pamphlets for the local good parish. Introduces himself as Brother Gideon.',
    // 'A man in a bad set of robes is handing out dead rats from the local evil temple. Introduces himself as Brother BabyStabber.',
    // 'A man in a decent set of robes is handing out blank pieces of paper from the local neutral temple. Introduces himself with a shrug and a sigh.',
    // 'A lovely gazebo is seen on the side of the road. It looks like a nice place for a picnic.',
    // "An adventure party passes by whining about a lack of something called 'Cheetos' and some or of Dew of a Mountain. Weirdos.",
    // "An adventure party passes by with each member spouting off silly 'Ni' noises or something about bushes. Weirdos.",
    // "An adventure party passes by with a drow sneaky fellow wearing two scimitars whinging about wanting more 'Ex-Pee' because of 'Role-playing'. Weirdo.",
    // 'An armless, legless knight has bled out near a creek. Apparently his corpse has been here for a while. His armor seems to be made of paper.',
    // "A fairy offers the party a wish if they can answer her riddles three. If they agree she just leaves laughing saying 'I didn't think someone would actually believe me on that.'. If they don't she gets mad and leaves saying 'It's not like they were THAT hard, pansies.'",
    // "A lumberjack is eating his lunch on the side of the road. If asked he'll share with one person.",
    // "A miner is eating his lunch on the side of the road. If asked he'll share a beer with one person.",
    // "A cultist is eating his lunch on the side of the road. If asked he'll share a bagel with one person.",
    // 'A perfectly serviceable wooden shield is found on the side of the road. Not masterwork or magic. Just serviceable.',
    // 'A perfectly serviceable shortsword is found on the side of the road. Not masterwork or magic. Just serviceable.',
    // "There's a huge pot hole in the road. Like HUGE, for a pothole, it's not a pit or anything. DC 3 Acrobatics check to not stumble on it. Failure means you take 1d2-1 nonlethal teasing damage and fall flat on your ungraceful face.",
    // 'A tune if heard off in the distance. Nothing in particular, just kind of a musical edge to the area. Like a light mist.',
    // 'A troop of guardsmen are patrolling the road. They ask you to clear the way and move on.',
    // 'A man is selling sausages from a decent cart. The sausages are ok.',
    // 'A man is selling sausages from a crappy cart. The sausages are good, but you start to feel bad for eating too many of them. Like you ate an entire tin of ice cream bad.',
    // "A man is selling sausages from a good cart with bread rolls. The bread is bland, and the spice in the sausage is forgettable, but it's filling.",
    // "A man is selling wiener dogs from a cart that's barking. Not to eat. He's just selling the dogs. They make good mousers he says.",
    // "A woman in armor is offering to bed any man who can beat her in an arm wrestle. She's got a 23 Strength and isn't particularly pretty, but if you're into that it's there.",
    // "A group of guards force a group of prostitutes to 'Move along then.'",
    // "A minstrel plays nearby. He's ok, but he'd be a lot better if he actually put some practice in.",
    // 'A local pubkeep offers the party a round of drinks for half off on account of them looking thirsty.',
    // 'A local inn offers the party a dinner half off on account of them looking hungry.',
    // "A man missing a leg thanks the party for the good that they've been doing.", 'A man missing an arm spits at the party for the good they missed doing.',
    // 'Two bards are utterly failing to sing a song in tune.',
    // 'Two bards are actually killing a particular song. The crowd around them is pretty into it.',
    // "A man is selling hats. He's willing to trade for skins if anyone in the party has any.",
    // 'The party sees a mild acquaintance. S/He offers to get lunch with them.',
    // 'The party sees a mild annoyance. S/He flips them the bird before wandering off.',
    // "A pie eating contest is in progress. It looks like it's down to the blacksmith's son or the cowherd's daughter.",
    // "Two teenagers are walking down the street holding hands and blushing whenever one catches the other's eye.",
    // 'The wizard steps in shit. Roll 1d4 to see what kind. 1- Cow, 2- Cow, 3- Cow, 4- Builette.',
    // 'A group of bandits charge, but petter out before combat engages because the party looks too tough to take on.',
    // "Seven men in hooded robes are fumbling around. Overhead is: 'Hey John, I think I've got your robes' 'Damnit Sev, your wife swapped our hoods again.' and 'Who's got my sash? It was the scarlet one.'",
    // "A drow is hung over on the side of the road. A three empty bottles of dwarven ale are nearby. He's waving his hands about muttering 'Turn off the sun.' Shortly after Dancing Lights twirl around his location as he lets out a groan of pain.",
    // 'A dwarf is passed out in a puddle of his own drool on the side of the road. A half empty bottle of elven wine is nearby.',
    // 'A friendly dog comes by and starts begging for treats from the most cleric-like party member.',
    // 'An unfriendly dog attempts to pee on the most wizard-like party member.',
    // 'Two old men are playing some sort of game on the side of the road talking mostly in murmurs, grunts, and chortles.',
    // 'Two old women are gossiping nearby knitting scarves longer than they are tall that are growing by the inch as you watch.',
    // 'A man is juggling torches nearby. Nothing goes amiss.', 'Two young teenagers are arguing about whether a dragon could be three owlbears if the owlbears had armor and magic wands and the dragon had a sword.',
    // 'A local noble is in town collecting his due taxes.',
    // 'The worst bandit in the world attempts to way-lay the party with a sharpened stick and a dented pot lit. If actually confronted he faints in shock.',
    // "The wizard discovers he has a sign pinned to the back of his robes reading 'Ass-zard'. It is unknown when it was placed there or how long it's been there.",
    // "A dungeon is nearby, if investigated it turns out that it's still in the process of being excavated and won't be ready for several more years.",
    // 'The thief find a socket puppet nestled amongst his belongings. It appears to be made from one of the wizards socks.',
    // 'The fighter finds a flask of good booze they had forgot about amongst their belongings.',
    'The cleric finds a bag of honeyed nuts amongst her belongings.'
  ],
  'wilderness': [
    'You see a gazebo squatting by the road. It has an arrow sticking from it.',
    'There is a hanged corpse swaying in the wind. It seems he was tortured before being hanged. A sign around his neck says "Looter of the dead".',
    'There is a badly written sign by the road saying "Tresur hier" with an arrow pointing to a dark, thick forest.',
    'You hear a boom of thunder, even though the sky is cloudless.',
    'During night, a fox skulks into the camp and tries to steal food.',
    'You happen upon an abandoned orchard heavy with lush and delicious-looking fruits.',
    "During the night, a homeless pixie has taken residence in a character's hat or boot. S/he is snoring there happily in the morning.",
    "The characters find the corpse of a great animal completely out of place in the surroundings - a polar bear in the tropic, a lion in the arctic etc. It haven't been touched by any scavengers.",
    'There is a gold coin on the road. There are two on the side of the road, three a little deeper in the underbrush, four behind the bush over there and so forth...',
    'You come across a wolf caught in a trap, it whines pitifully.',
    'A group of teenagers are headed back up the road the way you came. They carry barrels of fresh fish, and they offer to trade some for a horse.',
    "A merchant's corpse lays off the road in a ditch, riddled with arrows. The remains of his raided cart are burned nearby.",
    'A young boy begs for a ride to a nearby city. He is unarmed and clearly hungry.',
    "A party of adventurers stops you and asks for directions and healing. Some are badly injured. They transport a body with them, clearly their group's cleric, turned to stone.",
    'A tree has fallen, blocking the road.',
    'Vultures / Buzzards are circling overhead.',
    'Off in the distance, you see what is clearly a group of bandits preparing an ambush. You still have a chance to take another road.',
    'As you come to a clearing in the wood, you see an abandoned campsite, a pot of soup boiled down to scorched. They clearly left in a hurry.',
    'You find a horse dragging a body behind it. The body is dressed in rags. Inspection will reveal that he died of dehydration.',
    'You notice that all the vegetation in a 1 mile radius is inexplicably dead.',
    'A scrap of lacy cloth has been caught on a bramble, and two sets of tracks lead into the forest.',
    'You come upon an impossibly elderly dwarf, naked as the day he was born, standing in the middle of the road demanding a toll be paid. He proclaims himself to be the King of the Road.',
    'Whoever is on watch distinctly hears a whispering voice warn "Beware the black briar!" No amount of searching uncovers the whisperer.',
    'You find a lake, teeming with fish and crabs. Inspection reveals that the lake is salt water.',
    'A bloated body is on the road, a dagger still in its back. A half-elf dressed in robes with a spell component pouch hooked to her belt. An orange cat guards the corpse fiercely, and will not be scared away.',
    'A large, crudely painted sign proclaims "DETOOR THIZ WAYE", spelled incorrectly in both Common and Giant, pointing off the road and into the rocky foothills.',
    'A group of four small children, no more than eight or nine years old, proudly stops your group. They are adventuring heroes, and want to join your party. To kill nasty trolls, and slay horrible dragons, and stay up as late as they want.',
    "A heavily-guarded merchant caravan passes your party on the road at night. The mercenaries all scowl at you menacingly as they pass, and an archer perched atop a carriage has a shot aimed right at (squishy character's) head.",
    'A gnome is on the road, desperately trying to fix a hulking piece of machinery. It looks like a large two-legged dog, with a seat in the middle. Perhaps it is some mode of conveyance? If interacted with, he is only interested in fixing his contraption, and will demand a platinum piece from any who approach. If given, he will quickly melt the platinum down in a vial and pour it into a wooden mold to replace a broken piece. Once fixed, he will thank them profusely, and only then will he reimburse them an equivalent amount in gold.',
    'A group of slavers stops about 200 yards from you. They have many men, women, and children of a multitude of races bound in chains and they drive them like cattle toward their destination. The procession of slaves is watched over by 80 or so heavily-armed human and hobgoblin guards, enough to make any kind of assault guaranteed suicide. A half-elf dressed in simple clothes with a collar around his neck steps off of a carriage and approaches the group and begins an elaborate pitch, detailing  the "wares" they have for sale. If interested, you can buy a trained warrior for 250 gp, or an untrained slave for only 50gp. They are willing to negotiate on price.',
    'A patrol of royal guards is approaching. Six stout men, guarding what seems to be an iron strongbox. They are traveling quickly. They ask you to join them in transporting their incredibly valuable cargo to the King, promising a small reward for the effort. If the strongbox is opened (by killing the guards and picking a difficult lock), it contains a letter from another kingdom, a peace treaty.',
    'As you come to a river, you see the the bridge has been washed away in the recent storm. You can attempt a difficult crossing, or you can try to find another way.',
    'A lone wolf is following you. At night, when you make camp, it is always lurking just outside your firelight. If attacked, it flees, only to return. If ignored, it simply follows. If given food, it will enter camp and travel with you, but will flee at the first sign of combat.',
    'A pack of dirt-covered Dwarf miners approach from off the road, offering to trade very valuable gems for ale and food ("not trail rations, real food!"). They have just struck upon a massive gem deposit and wish to celebrate. Hope you have some with you.',
    "An archery target hangs on a nearby oak tree. The oak's leaves are just a bit greener than other trees in the area. Shooting three bull's eyes in a row will open a secret door in the tree containing several masterwork longbows with strength bonuses, and a potion of True Strike, as well as a few green feathered caps and some tights.",
    'A hunter approaches, asking for your aid. He is gaunt, obviously hungry. He says he has tracked a bear to a nearby cave, and if you can help him kill it, it will feed his family for a month.',
    'You see two dragons flying, far off in the distance. One spouts fire at the other, and is answered back with lightning. They lock together, tooth and claw, and drop out of sight behind the mountains.',
    "During the night, whomever is on watch hears someone approaching. Moments later, a 15 year old boy runs into the clearing. He drops to his knees and begs you to hide him. He doesn't give any detail, just cries and begs. If you refuse, he runs. A minute or so later, a few farmers with pitchforks and axes appear. They ask if you've seen the boy, claiming he murdered a young girl. (The truth is that he was caught in bed with one of their daughters, who was promised to be wed to a local lord.",
    'A crying baby floats down the river on a singed piece of wood.',
    'A procession of holy men of some unknown faith clad in flowing grey robes approaches. Their leader, a charismatic man wearing a purple robe, will lecture you for hours on the nature of your sin and how you should submit to him to achieve salvation.',
    'You come across a ramshackle village, full of unsavory men. They are a collection of criminals that have been exiled from the nearby towns. They eye your backpack covetously.',
    'You come upon the aftermath of a battle. Corpses litter the ground. Scavengers, both four- and two-legged, pick over the remains.',
    "You notice an elf slumped against a tree, covered in blood. He reveals that he is a courier, and was ambushed by bandits. He tells you that they didn't find the message he carries, it is hidden behind his belt buckle. He asks you to deliver the message for him to a woman named Ella Corwyn in the village of Threader's Hollow, a few days ride out of your way. If read, it is a simple message from her son, who is training in wizardry with the elves. If delivered, Ella will feed your group and offer shelter in her barn.",
    'There is a cemetery here. The graves are dug up and tomb doors are broken, seemingly from the inside. Shuffling tracks lead off into the forest.',
    'A crowd of townsfolk equipped with makeshift weapons and torches are marching towards a nearby city. They proclaim that they are going to do battle with a minor local lord because his taxes are too high. They will almost certainly be slaughtered.',
    'An old hermit appears before you on the road inviting you back to his home for dinner. If asked, he tells you that once a year, he invites a group of travelers to share a meal. If taken up on his offer, he takes you back to a secluded, sparsely furnished hut and provides a rather tasty and hearty stew of rabbit, turnips, carrots, and foraged herbs. He also challenges all comers to a game of Three Dragon Ante. He is very good.',
    "As you begin making camp for the night, you see a meteor crash to earth, no more than an hour's ride from you.",
    'A wandering bard approaches your campfire. If allowed to stay, he sings and plays a lute. He also shares his wine and asks to hear about your adventures. If the stories you tell him are good, he will write a song about you.',
    'You find a poorly-built shack off the road. If inspected, you will find it is full of corpses, all wearing grey robes, all the victims of a ritualized mass suicide, committed with obsidian daggers. At the front of the room, atop an altar, is a man in a purple robe, who drank poisoned wine.',
    "The surface of this lake is covered with the floating bodies of thousands of fish. There's no telling how or why they died, or if they'd be safe to eat. Roll % to see if they're edible.",
    "Here lie the bones of an old ship, wrecked on the reef. The strange thing is, you're miles from the nearest body of water.",
    'As you cross the desert, you come across a single tree, growing tall and strong amid the desolate waste.',
    'You notice that one of the trees in this clearing has no leaves. But its branches are bearing fruit. The fruit is unfamiliar to you, and seems to change colors in the light.',
    'A bear wearing a fine vest and hat is selling expertly-crafted musical instruments from an ox drawn cart hitched to a tree by the side of the road. Prices are high, but the craftsmanship appears to be worth it. A flamboyantly painted sign on the side of the cart in bold calligraphy reads: Musickal Innstruments of Fynest Make, Expertly Craffted by Sir Wm. Bearington III, Proprietor. Sir William Bearington III speaks no languages, but can understand and crudely scratch out replies in Common. Should you attempt to steal from him, Sir Bearington will attack without hesitation, as a Dire Bear.',
    'A small collection of bards of various races have formed an impromptu jam session in a clearing nearby. They sound great, and if asked, they attribute the sound to the quality of the instruments. Anyone with a proficiency in a musical instrument and enough gold in their purse must succeed on a DC 10 Will save, or feel compelled to buy one.',
    "A minotaur comes out of the shadows into your campfire, not making a sound as he approaches. He stands 8 feet tall, with a massive axe strapped to his back. Wordlessly, he crouches near the fire and stirs the embers with a stick. Then he speaks, trading stories of the road. He tells many stories of doing battle with Mountain Giants, and delights in hearing stories of the players' exploits. In the morning, he leaves. If asked, he will provide perfect directions to any one destination.",
    'The bodies of a human woman, a male orc, and a baby half-orc are nailed to nearby trees. A sign stuck in the soil nearby reads "Race Mixers"',
    'A trio of dirty peasants is riding past on an impossibly fancy carriage. They nervously smile and wave at your group. A DC 18 spot check will notice a smear of blood on the side of the carriage.'
  ]
}
