setup.supporters = {
  'Daniel Auchenpaugh': 10,
  "Giuseppe D'Aristotile": 1,
  'David Lawson': 5,
  'Dunkin McCloud': 5,
  'Hilmi': 5,
  'JMR1991': 15,
  'Ben': 5,
  'Elling N√∏kleby': 5,
  'Trevor Johnson': 5,
  'Faer-Anne': 5,
  'Terence Mruz': 5,
  'Fiona Gr√∂schel': 1,
  'Jofu': 2,
  'Sam': 5,
  'Grygon': 5,
  'nick brown': 5,
  'Atakan Altƒ±ner': 5,
  'Quentin Flanders': 5,
  'Michael Brown': 5,
  'Shashwat S': 1,
  'Adam Lister': 5,
  'Matthew Savoy': 10,
  'Wayne': 5,
  'Bryce Shafer': 5,
  'Edgar Diamond': 1,
  'Seren Grey': 5,
  'LunarRust': 5,
  'Zach Benes': 5,
  'Warren Fear': 5,
  'Joe Smith': 5,
  'Sam Barrie': 5,
  'Gustavo Cunha': 5,
  'Eric': 5,
  'Brad Scott': 5,
  'Carlos Ortiz': 5,
  'Viktor Bostr√∂m': 1,
  'Jake Lasky': 1,
  'James Caruso': 5,
  'Jenn Nsk': 5,
  'Daniel Quaresma': 5,
  'GadgetBoy': 2,
  'Michael Saint Gregory': 5,
  'Brian Trepanier': 5,
  'Steele': 5,
  'Jennine Cerra': 1,
  'Tales of Exalted Heroes': 5,
  'Nathan Tobin': 1,
  'Austin Elizondo': 5,
  'Josh Hawfield': 5,
  'Neroth': 5,
  'Tyziel': 5,
  'Xzallion': 5,
  'Lars Michael Norregaard': 1,
  'Connor Weston': 5,
  'James Knevitt': 1,
  'Rachel Halliday': 5,
  'Chris Covert': 5,
  'Taran': 2,
  'Simon Fraser': 2,
  'Medric Riley': 5,
  'AK_Zephyr': 5,
  'Tyrian': 1,
  'Rhys': 1,
  'Jack': 5,
  'Mortifiedonuts': 2,
  'Cooper Ratliff': 5,
  'Rhianna Ulrich': 1,
  'Pere Alonso Albaladejo': 2,
  'Waldue': 5,
  'cesarvillavi': 5,
  'robert schaefer': 1,
  'WarWizardGames': 5,
  'Jamie Chang': 5,
  'Rinzler': 5,
  'Chris': 1,
  'elzzid': 1,
  'Armand': 15,
  'Dave campbell': 5,
  'David Hatch': 1,
  'Crimson Tc': 5,
  'Kevin': 5,
  'Douglas C Ward': 1,
  'William Haber': 5,
  'Stephen': 5,
  'Phillip Liljestrand': 1,
  'Aaron Lutomski': 2,
  'Alan Gibson': 5,
  'Sandra Johnson': 5,
  'Scott Cook': 1,
  'Keith Avery': 1,
  'Matt Cherwin': 5,
  'Shane Newsom': 1,
  'Chen Zhang': 1,
  'Vanille Keks': 2,
  'Vivacia': 1,
  'Caitlin Brown': 2,
  'Morden': 2,
  'Doug Churchman': 2,
  'Braden': 5,
  'Adam Portman': 2,
  'Hayden': 5,
  'PHILIP A COFFEY': 5,
  'Catherine': 5,
  'John Senner': 5,
  'Jack Lawson': 5,
  'Mario Buehling': 1,
  'Sarah Kouklis': 5,
  'Jooshyboy': 1,
  'Runixzan': 1,
  'Brett Ritter': 1,
  'DisjointedImages': 2,
  'Carolyn': 1,
  'M Nickelson': 1,
  'Damien Pinto-Martin': 1,
  'Andrew Mullinax': 2,
  'Duncan Thomson': 1,
  'Gordon Randall': 1,
  'KroyVR': 2,
  'Lewis Kelly': 1,
  'Wendy Birb': 1
}

setup.printSupporters = () => {
  const pool = setup.supporters
  const list = []
  for (let i = 0; i < 20; i++) {
    const temp = lib.weightRandom(pool)
    if (!list.includes(temp)) {
      list.push(temp)
      delete pool[temp]
    }
  }
  return list
}
