setup.supporters = {
  'Kald Hade': 2,
  'CJLS ': 1,
  'Vivacia': 1,
  'Vanille Keks': 2,
  'Chen Zhang': 1,
  'Shane Newsom': 1,
  'Christopher Allbritton': 5,
  'Matt Cherwin': 5,
  'Joel': 5,
  'Fiordhraoi ': 5,
  'Keith Avery': 1,
  'Misha': 1,
  'Larrisunshine ': 10,
  'AWP': 2,
  'Mitchell Stevenson': 2,
  'Scott Cook': 1,
  'Sandra Johnson': 5,
  'Alan Gibson': 5,
  'Aaron Lutomski': 2,
  'Alfred Vergara': 5,
  'Phillip Liljestrand': 1,
  'Michael': 5,
  'Stephen ': 5,
  'Thodoris Econox': 5,
  'William Haber': 5,
  'Douglas C Ward': 1,
  'Kevin': 5,
  'Crimson Tc': 5,
  'David Hatch': 1,
  'Monicle': 5,
  'Dave campbell': 5,
  'The Digital DM': 1,
  'OniNoKen ': 15,
  'Armand ': 15,
  'elzzid ': 1,
  'Chris': 1,
  'Rinzler ': 5,
  'Jamie Chang': 5
}
