setup.supporters = {
  'Eurig': 5,
  'Caitlin Brown': 2,
  'Trung Le': 1,
  'Morden': 2,
  'Doug Churchman': 2,
  'Michael Lesyna': 5,
  'Nick Brown': 1,
  'Bernard Howell': 2,
  'Braden': 5,
  'Holymittens': 2,
  'Barry Moraller': 5,
  'Adam Portman': 2,
  'Hayden': 2,
  'PHILIP A COFFEY': 2,
  'Catherine': 5,
  'John Senner': 5,
  'The Bearded One': 1,
  'Bryan Holt': 2,
  'Marcus Flores': 2,
  'EarlofRaR': 10,
  'Brett Thornton': 15,
  'Phillip James Wiley': 5,
  'Mario Buehling': 1,
  'MaxOliver': 2,
  'Sarah Kouklis': 5,
  'Daniel Hodge': 5,
  'Runixzan': 1,
  'Brett Ritter': 1,
  'DisjointedImages': 2,
  'Carolyn': 1,
  'M Nickelson': 1,
  'Damien Pinto-Martin': 1,
  'Andrew Mullinax': 2,
  'Gunnar A Smits': 10,
  'Duncan Thomson': 1,
  'Gordon Randall': 1,
  'KroyVR': 2,
  'Lewis Kelly': 1,
  'Wendy Birb': 1
}
