// setup.inventory = [
//
//
//   {name: "Dagger", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Handaxe", cost: 500, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Javelin", cost: 50, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Light Hammer", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Sickle", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Spear", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//
//   {name: "Battleaxe", cost: 1000, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Flail", cost: 1000, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Glaive", cost: 2000, availabilityLocation: ['blacksmith'], availability: 3, type: "weapon"},
//   {name: "Greataxe", cost: 3000, availabilityLocation: ['blacksmith'], availability: 3, type: "weapon"},
//   {name: "Greatsword", cost: 5000, availabilityLocation: ['blacksmith'], availability: 4, type: "weapon"},
//   {name: "Halberd", cost: 2000, availabilityLocation: ['blacksmith'], availability: 4, type: "weapon"},
//   {name: "Lance", cost: 1000, availabilityLocation: ['blacksmith'], availability: 4, type: "weapon"},
//   {name: "Longsword", cost: 1500, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Maul", cost: 1000, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Morningstar", cost: 1500, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Pike", cost: 500, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Rapier", cost: 2500, availabilityLocation: ['blacksmith'], availability: 3, type: "weapon"},
//   {name: "Scimitar", cost: 2500, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//   {name: "Shortsword", cost: 1000, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Arrows (20)", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "weapon"},
//   {name: "Crossbow Bolts (20)", cost: 100, availabilityLocation: ['blacksmith'], availability: 2, type: "weapon"},
//
//   {name: "Padded Armour", cost: 500, availabilityLocation: ['general store'], availability: 2, type: "armour"},
//   {name: 'Hide Armour', cost: 500, availabilityLocation: ['general store'], availability: 1, type: 'armour'},
//   {name: "Leather Armor", cost: 2000, availabilityLocation: ['general store'], availability: 2, type: "armour"},
//   {name: "Studded Leather Armor", cost: 4500, availabilityLocation: ['blacksmith', 'general store'], availability: 3, type: "armour"},
//   {name: "Chain Shirt", cost: 5000, availabilityLocation: ['blacksmith'], availability: 1, type: "armour"},
//   {name: "Scale Mail", cost: 5000, availabilityLocation: ['blacksmith'], availability: 1, type: "armour"},
//   {name: "Breastplate", cost: 40000, availabilityLocation: ['blacksmith'], availability: 2, type: "armour"},
//   {name: "Half Plate", cost: 75000, availabilityLocation: ['blacksmith'], availability: 4, type: "armour"},
//   {name: "Ring Mail", cost: 3000, availabilityLocation: ['blacksmith'], availability: 2, type: "armour"},
//   {name: "Chain Mail", cost: 7500, availabilityLocation: ['blacksmith'], availability: 2, type: "armour"},
//   {name: "Splint", cost: 20000, availabilityLocation: ['blacksmith'], availability: 3, type: "armour"},
//   {name: "Plate", cost: 150000, availabilityLocation: ['blacksmith'], availability: 4, type: "armour"},
//   {name: "Shield", cost: 1000, availabilityLocation: ['blacksmith'], availability: 1, type: "armour"},
//
//   {name: "Ball Bearings (1000)", cost: 100, availabilityLocation: ['blacksmith'], availability: 2, type: "adventuring gear"},
//   {name: "Bell", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Block and Tackle", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Chain (10 feet)", cost: 500, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Caltrops (Bag of 20)", cost: 100, availabilityLocation: ['blacksmith'], availability: 2, type: "adventuring gear"},
//   {name: "Crowbar", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Grappling Hook", cost: 200, availabilityLocation: ['blacksmith'], availability: 3, type: "adventuring gear"},
//   {name: "Hammer", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Sledge Hammer", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Hunting Trap", cost: 500, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Lamp", cost: 50, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Lantern, Bullseye", cost: 1000, availabilityLocation: ['blacksmith'], availability: 4, type: "adventuring gear"},
//   {name: "Lantern, Hooded", cost: 500, availabilityLocation: ['blacksmith'], availability: 3, type: "adventuring gear"},
//   {name: "Lock", cost: 1000, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Manacles", cost: 200, availabilityLocation: ['blacksmith'], availability: 2, type: "adventuring gear"},
//   {name: "Mirror, Steel", cost: 500, availabilityLocation: ['blacksmith'], availability: 2, type: "adventuring gear"},
//   {name: "Pick, Miner's", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Piton", cost: 5, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Pot, Iron", cost: 200, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Ram, Portable", cost: 400, availabilityLocation: ['blacksmith'], availability: 4, type: "adventuring gear"},
//   {name: "Spikes, Iron (10)", cost: 100, availabilityLocation: ['blacksmith'], availability: 1, type: "adventuring gear"},
//   {name: "Mason's Tools", cost: 1000, availabilityLocation: ['blacksmith'], availability: 2, type: "tools"},
//   {name: "Smith's Tools", cost: 2000, availabilityLocation: ['blacksmith'], availability: 1, type: "tools"},
//   {name: "Tinker's Tools", cost: 5000, availabilityLocation: ['blacksmith'], availability: 3, type: "tools"},
//   {name: "Horn", cost: 300, availabilityLocation: ['blacksmith'], availability: 4, type: "tools"}
//
//
//
//   {name: 'Club', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//   {name: 'Dagger', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'weapon'},
//   {name: 'Greatclub', cost: 20, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//   {name: 'Handaxe', cost: 500, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'weapon'},
//
//   {name: 'Light Hammer', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'weapon'},
//   {name: 'Quarterstaff', cost: 20, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//
//   {name: 'Light Crossbow', cost: 2500, availabilityLocation: ['general store'], availability: 2, type: 'weapon'},
//   {name: 'Dart', cost: 5, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//   {name: 'Shortbow', cost: 2500, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//
//   {name: 'Sling', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//   {name: 'Whip', cost: 200, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//
//   {name: 'Hand Crossbow', cost: 7500, availabilityLocation: ['general store'], availability: 3, type: 'weapon'},
//   {name: 'Heavy Crossbow', cost: 5000, availabilityLocation: ['general store'], availability: 4, type: 'weapon'},
//   {name: 'Longbow', cost: 5000, availabilityLocation: ['general store'], availability: 1, type: 'weapon'},
//
//
//
//   {name: 'Backpack', cost: 200, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Bedroll', cost: 100, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Blanket', cost: 50, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Block and Tackle', cost: 100, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Book', cost: 2500, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: 'Bottle, Glass', cost: 200, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Bucket', cost: 5, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Candle', cost: 1, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: 'Case, Crossbow Bolt', cost: 500, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: 'Case, Map or Scroll', cost: 100, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Chain, 10 feet', cost: 500, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Chest', cost: 500, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Climbers Kit', cost: 2500, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: "Clothes, Traveler's", cost: 200, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Component Pouch', cost: 2500, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: 'Crowbar', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Fishing Tackle', cost: 100, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Flask or tankard', cost: 2, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Grappling Hook', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 2, type: 'adventuring gear'},
//   {name: 'Hammer', cost: 100, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//
//
//   {name: 'Hourglass', cost: 2500, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Hunting Trap', cost: 500, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Ink (1 ounce)', cost: 1000, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Ink Pen', cost: 2, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Ladder, 10ft.', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Lantern, Bullseye', cost: 1000, availabilityLocation: ['general store', 'blacksmith'], availability: 3, type: 'adventuring gear'},
//   {name: 'Lantern, Hooded', cost: 500, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Magnifying Glass', cost: 10000, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Manacles', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 2, type: 'adventuring gear'},
//   {name: 'Mess Kit', cost: 20, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Steel Mirror', cost: 500, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Oil, flask', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Paper (one sheet)', cost: 20, availabilityLocation: ['general store'], availability: 4, type: 'adventuring gear'},
//   {name: 'Parchment (one sheet)', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: "Miner's Pick", cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Piton', cost: 5, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Pole (10 ft.)', cost: 5, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Pot, Iron', cost: 200, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Pouch', cost: 50, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Quiver', cost: 500, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Rope, Hemp (50ft)', cost: 100, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Rope, Silk (50ft)', cost: 1000, availabilityLocation: ['general store'], availability: 4, type: 'adventuring gear'},
//   {name: 'Sack', cost: 1, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Shovel', cost: 200, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Signal whistle', cost: 5, availabilityLocation: ['general store'], availability: 3, type: 'adventuring gear'},
//   {name: 'Spikes, Iron (10)', cost: 100, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'adventuring gear'},
//   {name: 'Spyglass', cost: 100000, availabilityLocation: ['general store'], availability: 4, type: 'adventuring gear'},
//   {name: 'Two person tent', cost: 200, availabilityLocation: ['general store'], availability: 2, type: 'adventuring gear'},
//   {name: 'Tinderbox', cost: 50, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Torch', cost: 1, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Vial', cost: 100, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//   {name: 'Waterskin', cost: 20, availabilityLocation: ['general store'], availability: 1, type: 'adventuring gear'},
//
//   {name: "Cartographer's Tools", cost: 1500, availabilityLocation: ['general store'], availability: 2, type: 'tools'},
//   {name: "Tinker's Tools", cost: 5000, availabilityLocation: ['general store'], availability: 3, type: 'tools'},
//   {name: 'Herbalism Kit', cost: 500, availabilityLocation: ['general store'], availability: 2, type: 'tools'},
//   {name: "Healer's Kit", cost: 500, availabilityLocation: ['general store'], availability: 2, type: 'tools'},
//   {name: "Navigator's Tools", cost: 2500, availabilityLocation: ['general store'], availability: 1, type: 'tools'},
//   {name: "Mason's Tools", cost: 1000, availabilityLocation: ['general store', 'blacksmith'], availability: 1, type: 'tools'},
//   {name: "Painter's Supplies", cost: 1000, availabilityLocation: ['general store'], availability: 3, type: 'tools'},
//   {name: "Potter's Tools", cost: 1000, availabilityLocation: ['general store'], availability: 1, type: 'tools'},
//   {name: 'Dice Set', cost: 10, availabilityLocation: ['general store'], availability: 1, type: 'tools'},
//   {name: 'Playing Card Set', cost: 50, availabilityLocation: ['general store'], availability: 1, type: 'tools'}
// ]
