export { calcPercentage } from './src/calcPercentage'
export { clampRolls } from './src/clampRolls'
export { colours } from './src/colours'
export { findInContainer } from './src/findInContainer'
export { setRandom } from './src/random'
