setup.temple = {
  'name': {
    'wordNoun': ['temple', 'holy house', 'monastery', 'convent', 'abbey', 'cathedral', 'shrine'],
    'soleNoun': ['desire', 'restoration', 'humility', 'white', 'sorrow'],
    'adjective': ['forgiving', 'ever-loving', 'faithful', 'repentant', 'fallen', 'damned', 'stone', 'silent', 'understanding'],
    'plural': ['souls', 'men', 'sinners', 'warriors', 'wretches', 'tools', 'pawns']
  },
  'rollData': {
    'wealth': [
      [95, 'kingly'],
      [80, 'aristocratic'],
      [70, 'wealthy'],
      [60, 'comfortable'],
      [50, 'modest'],
      [25, 'poor'],
      [15, 'squalid'],
      [0, 'destitute']
    ],
    'size': [
      [95, 'cavernous'],
      [80, 'huge'],
      [70, 'quite large'],
      [60, 'large'],
      [50, 'spacious'],
      [40, 'modest'],
      [30, 'somewhat cramped'],
      [20, 'small'],
      [10, 'tiny'],
      [0, 'extremely cramped']
    ],
    'cleanliness': [
      [90, 'totally spotless (cleanliness being next to godliness)'],
      [80, 'fastidious'],
      [70, 'very tidy'],
      [60, 'tidy'],
      [50, 'reasonably tidy'],
      [40, 'somewhat messy'],
      [30, 'rather messy'],
      [20, 'very messy'],
      [10, 'extremely messy'],
      [0, 'dangerously messy']
    ],
    'bedCleanliness': [
      [80, 'perfectly prepared, with fresh sheets and a lemon scent in the air of the room'],
      [75, 'recently prepared and well cleaned'],
      [70, 'freshly cleaned and neat'],
      [60, 'tidy and neat'],
      [50, 'reasonably clean'],
      [40, 'somewhat tidy'],
      [30, 'disgusting'],
      [20, 'teeming with rats'],
      [10, 'rather filthy'],
      [0, 'festering with bugs']
    ]
  },
  'prayerSubject': [
    'one god and only one god',
    'one god primarily, but other gods occasionally or for specific petitions',
    'several gods within a pantheon, but two gods above the rest',
    'an entire pantheon, petitioning each god for specific needs',
    'one god to whom the temple was not originally dedicated',
    'several gods within a pantheon to whom the temple was not originally dedicated'
  ],
  'dedicated': [
    'the sun', 'the sky', 'craft', 'knowledge', 'death', 'evil', 'the hunt', 'the woodlands', 'love', 'beauty', 'the moon', 'the sun', 'the seas', 'the storms', 'trickery', 'war', 'the harvest', 'festivals'
  ],
  'knownFor': [
    'miraculous healers',
    'compassionate healers',
    'beautiful priestesses',
    'wonderful music',
    'accurate prophecies',
    'collected wisdom',
    'stunning architecture',
    'unusual architecture',
    'incredible collection of artwork',
    'a famous sculpture',
    'a famous painting',
    'lengthy prayer services and vigils',
    'lively prayer services and debates',
    'ostentatious gatherings',
    'condescending priests',
    'worshipping the sun',
    'having never been completed',
    'sliding down a hillside',
    'having seventeen spires',
    "running the town's militia",
    'offering free board and lodgings',
    'its sadly incompetent healers',
    // 'the ancient relic ' + setup.misc.religion.createRelic(),
    'cryptic prophecies',
    'unusual prophecies',
    'dancing monks',
    'training battle priests',
    'trance inducing music',
    'the huge painted murals on every wall',
    'claiming to house the body of a dead god',
    'a collection of relics',
    'faking miracles',
    'powerful healers',
    'the cult like influence of the high priest',
    'its enormous library of knowledge',
    'the endless labyrinth of tombs beneath it',
    'inaccurate prophecies',
    'its large bell tower',
    'the colorful robes of the priests',
    'barbarian healers',
    'worshipping false gods',
    'worshipping demons secretly',
    'worshipping devils secretly',
    'its powerful influence on the government',
    'having great wealth hidden away',
    'performing miracles',
    'dancing priests',
    'dancing priestesses',
    'reviving the dead',
    'controversial prayer services',
    'having awe inspiring stain glass windows',
    'claiming to have the finger of an ancient priest',
    'only letting in true believers into the inner rooms',
    'housing secret ceremonies',
    'having secret rituals',
    'expensive healing',
    'prophecies that are only ever half right',
    'gorgeous hidden gardens',
    'awe inspiring gardens',
    'having walls made of gold in the inner chambers not open to the public',
    'having vast tile mosaics across their floors',
    'housing powerful ancient scrolls',
    'housing fake texts from their god',
    'housing texts from their god',
    'sprawling indoor gardens',
    'colorful hanging gardens'
  ],
  'guardedBy': [
    'a sworn order of devout warriors',
    'sellswords',
    'frightening statues of monstrous beings',
    'impressive, colossal statues of warriors',
    'statues of beautiful maidens, beckoning visitors into a trap',
    'nothing; the temple welcomes all'
  ],
  'floorPlan': [
    'circular',
    'ellipsoidal',
    'triangular',
    'square',
    'rectangular',
    'pentagonal'
  ],
  'complex': [
    'simple; a large main worship chamber with a handful of functional rooms adjoining',
    'simple with a large annex; the annex contains many chambers',
    'simple with fortifications',
    'multi-layered; upper or lower layers are inaccessible to most visitors',
    'multi-winged; some wings are inaccessible to most visitors',
    'arranged in a concentric fashion; inner areas are inaccessible to most visitors',
    'labyrinthine; designed to deliberately confuse outsiders',
    'simple with an intricate complex hidden beneath the main worship chamber'
  ],
  'walls': [
    'impenetrable stone walls',
    'an intricate structure of stone arches and columns',
    'a colorful structure of painted wood and plaster',
    'a sturdy structure of finished wood',
    'a solid structure of oven-fired clay bricks'
  ],
  'interior': [
    'rough hewn stone',
    'smooth cut stone',
    'painted wood',
    'lacquered wood',
    'unfinished hardwood',
    'decorated with intricate mosaics',
    'decorated with elaborate murals',
    'decorated with relief carvings',
    'decorated with sacred texts and runes'
  ],
  'ceiling': [
    'uncomfortably close to your head',
    'connected to the floor by columns',
    'painted with mythological scenes',
    'so high its difficult to make out details',
    'vaulted',
    'domed'
  ],
  'rooms': [
    'an armory', 'a barracks',
    'a guardroom', 'a sentry post',
    'a cell for solitary prayer',
    'a cell for holding prisoners',
    'an inquisition', 'a torture chamber',
    'a priest’s office', 'an audience chamber',
    'a sanitarium', 'an infirmary',
    'a ceremonial pool', 'a fountain',
    'a morgue', 'a mortuary',
    'a crypt for a person of importance (d4): 1 well-known hero; 2 powerful high priest; 3 obscure priest; 4 wealthy noble',
    'a room dedicated for specific rituals (d4): 1 conjurations; 2 divinations; 3 funerals; 4 healing miracles',
    'a chapel', 'a shrine dedicated to a lesser deity, saint, or martyr',
    'a classroom',
    'a dormitory',
    'a library',
    'a priest’s quarters', 'a robing room',
    'a banquet room, large dining hall,', 'a small dining room',
    'a kitchen',
    'a trophy room', 'an art gallery',
    'a stable', 'a kennel',
    'a workshop for temple craftsmen'
  ],
  'features': [
    'a small altar set in an alcove in the wall',
    'the sound of bells ringing in a tower',
    'a wall sconce holding many candles',
    'tall candles on holders, taller than a man',
    'the tinkle of chimes from a nearby room',
    'a tapestry depicting a mythological scene',
    'a small fountain', 'a reflecting pool',
    'the sound of a gong from another room',
    'a large holy symbol embedded in the wall',
    'a huge book of sacred texts or prayers',
    'the scent of incense burning nearby',
    'a kneeler beneath a small statue or icon',
    'an oil lamp with colored glass panels',
    'a mosaic set into the floor of the room',
    'a wide fresco', 'a mural depicting a mythological scene',
    'the pipes of an immense organ running along the walls',
    'robes and cassocks hanging on hooks',
    'an ornamental rug',
    'a screen to hide priests from view',
    'a statue of a recognizable figure',
    'two large stone statues further down the hall',
    'a series of percussive thuds punctuated rhythmically by a groaning sound',
    'large stone stairs leading down to a pool of clear water',
    'the pillars are carved with intricate images of the heavens',
    'the floor tiles are made of red sandstone'
  ]
}
