export const templeData = {
  name: {
    wordNoun: ['temple', 'holy house', 'monastery', 'convent', 'abbey', 'cathedral', 'shrine', 'church', 'parish', 'sanctuary', 'tabernacle', 'chapel', 'chantry'],
    soleNoun: ['desire', 'restoration', 'humility', 'sorrow', 'will', 'commandment', 'love', 'divine', 'redemption', 'sacrament', 'sacrafice', 'fire', 'water', 'earth', 'nature', 'air', 'prayer', 'devotion', 'worship', 'service', 'invocation', 'grace'],
    adjective: ['forgiving', 'ever-loving', 'faithful', 'repentant', 'fallen', 'damned', 'stone', 'silent', 'understanding', 'petrified', 'holy', 'redeemed', 'golden', 'heavenly', 'graceful', 'devoted', 'sacred', 'hallowed', 'blessed', 'religious', 'consecrated', 'revered', 'humble', 'righteous', 'sublime', 'faithful'],
    plural: ['souls', 'men', 'sinners', 'warriors', 'wretches', 'pawns', 'lovers', 'priests', 'congregations', 'saints', 'slaves', 'followers', 'relics', 'angels', 'gods', 'demons', 'monks', 'nuns', 'mothers', 'fathers', 'believers'],
    colour: ['Maroon', 'Olive', 'Teal', 'Navy', 'Black', 'Black', 'Red', 'Orange', 'Yellow', 'Lime', 'Green', 'Cyan', 'Blue', 'Purple', 'Magenta', 'Gray', 'Pink', 'Lavendar', 'Golden', 'Silver', 'Emerald', 'Ruby']
  },
  prayerSubject: [
    // They pray to
    'one god and only one god',
    'one god primarily, but other gods occasionally or for specific petitions',
    'several gods within a pantheon, but two gods above the rest',
    'an entire pantheon, petitioning each god for specific needs',
    'one god, but not the one the temple was originally dedicated to',
    'several gods within a pantheon to whom the temple was not originally dedicated'
  ],
  dedicated: [
    // the temple is dedicated to
    'the sun',
    'the sky',
    'craft',
    'knowledge',
    'death',
    'evil',
    'the hunt',
    'the woodlands',
    'love',
    'beauty',
    'the moon',
    'the sun',
    'the seas',
    'the storms',
    'trickery',
    'war',
    'the harvest',
    'festivals',
    'wealth and prosperity',
    'record keeping',
    'true peace',
    'friendship and community',
    'law and order'

  ],
  knownFor: [
    // and is known for _
    'miraculous healers',
    'compassionate healers',
    'beautiful priestesses',
    'wonderful music',
    'accurate prophecies',
    'collected wisdom',
    'stunning architecture',
    'unusual architecture',
    'incredible collection of artwork',
    'a famous sculpture',
    'a famous painting',
    'lengthy prayer services and vigils',
    'lively prayer services and debates',
    'ostentatious gatherings',
    'condescending priests',
    'worshipping the sun',
    'having never been completed',
    'sliding down a hillside',
    'having seventeen spires',
    "running the town's militia",
    'offering free board and lodgings',
    'its sadly incompetent healers',
    // 'the ancient relic ' + setup.misc.religion.createRelic(),
    'cryptic prophecies',
    'unusual prophecies',
    'dancing monks',
    'training battle priests',
    'trance inducing music',
    'the huge painted murals on every wall',
    'claiming to house the body of a dead god',
    'a collection of relics',
    'faking miracles',
    'powerful healers',
    'the cult like influence of the high priest',
    'its enormous library of knowledge',
    'the endless labyrinth of tombs beneath it',
    'inaccurate prophecies',
    'its large bell tower',
    'the colorful robes of the priests',
    'barbarian healers',
    'worshipping false gods',
    'worshipping demons secretly',
    'worshipping devils secretly',
    'its powerful influence on the government',
    'having great wealth hidden away',
    'performing miracles',
    'dancing priests',
    'dancing priestesses',
    'reviving the dead',
    'controversial prayer services',
    'having awe inspiring stain glass windows',
    'claiming to have the finger of an ancient priest',
    'only letting in true believers into the inner rooms',
    'housing secret ceremonies',
    'having secret rituals',
    'expensive healing',
    'prophecies that are only ever half right',
    'gorgeous hidden gardens',
    'awe inspiring gardens',
    'having walls made of gold in the inner chambers not open to the public',
    'having vast tile mosaics across their floors',
    'housing powerful ancient scrolls',
    'housing fake texts from their god',
    'housing texts from their god',
    'sprawling indoor gardens',
    'colorful hanging gardens'
  ],
  // The temple is protected by
  guardedBy: [
    'a sworn order of devout warriors',
    'sellswords',
    'frightening statues of monstrous beings',
    'impressive, colossal statues of warriors',
    'statues of beautiful maidens, beckoning visitors into a trap',
    'nothing; the temple welcomes all',
    'a small group of warrior monks',
    'a small militia of untrained clergymen',
    'rusted metal statues'
  ],
  // The main room is __ in shape
  floorPlan: [
    'circular',
    'ellipsoidal',
    'triangular',
    'square',
    'rectangular',
    'pentagonal',
    'octagonal'
  ],
  // The temple was designed by __
  architect: [
    'the local priest',
    'a poor local farmer who was mistaken for the architect',
    "a local architect; he's not the best",
    'a nearby noble who wanted to get right with the gods',
    'a noble who wanted to show how holy he was',
    'a famed priest doing his duty for the gods',
    'a famous architect on a very generous commission',
    'a lesser known, rather eccentric architect',
    'a nearby king for his priestly brother',
    'a local scholar who had read some books on churches',
    'a renowned theologian of the clergy',
    'the local bricklayer',
    'a mysterious architect whom no one got the name of',
    'the son of the local priest',
    'a very confused local who was grabbed of the street',
    'the father of the local priest',
    'the local priest`s wife'
  ],
  // and it is __.
  complex: [
    'simple; with only a large main worship chamber and a handful of functional rooms adjoining',
    'simple with a large annex; the annex contains many chambers',
    'simple with fortifications',
    'multi-layered; the upper or lower layers are inaccessible to most visitors',
    'multi-winged; some wings are inaccessible to most visitors',
    'arranged in a concentric fashion; the inner areas are inaccessible to most visitors',
    'labyrinthine; it is designed to deliberately confuse outsiders',
    'simple with an intricate complex hidden beneath the main worship chamber'
  ],
  // The walls of the temple are
  walls: [
    'impenetrable stone walls',
    'an intricate structure of stone arches and columns',
    'a colorful structure of painted wood and plaster',
    'a sturdy structure of finished wood',
    'a solid structure of oven-fired clay bricks',
    'finished with oak planks',
    'finished with oiled mahogany planks',
    'powdery white gypsum',
    'supported by thin stone columns',
    'held up by thick wooden timbers',
    'adorned in intricate wooden carvings',
    'made of well crafted bricks',
    'made of rough hewn stone blocks',
    'made of poorly molded bricks',
    'made of rocks and mud',
    'made of sawn logs',
    'made of crudely cut tree trunks',
    'actually the hollowed husk of an enormous tree',
    'beautifully painted wood',
    'made of smooth cut stone',
    'made of unfinished hardwood',
    'covered in intricate murals',
    'adorned with relief carvings',
    'covered in sacred texts and runes',
    'made up almost entirely of intricate stained glass windows'
  ],
  // the ceiling is __
  ceiling: [
    'uncomfortably close to your head',
    'connected to the floor by columns',
    'painted with mythological scenes',
    'an enormous glass dome',
    'so high its difficult to make out details',
    'vaulted',
    'domed',
    'beautifully vaulted'
  ],
  rooms: [
    'an armory', 'a barracks',
    'a guardroom', 'a sentry post',
    'a cell for solitary prayer',
    'a cell for holding prisoners',
    'an inquisition', 'a torture chamber',
    'a priest’s office', 'an audience chamber',
    'a sanitarium', 'an infirmary',
    'a ceremonial pool', 'a fountain',
    'a morgue', 'a mortuary',
    'a crypt for a person of importance (d4): 1 well-known hero; 2 powerful high priest; 3 obscure priest; 4 wealthy noble',
    'a room dedicated for specific rituals (d4): 1 conjurations; 2 divinations; 3 funerals; 4 healing miracles',
    'a chapel', 'a shrine dedicated to a lesser deity, saint, or martyr',
    'a classroom',
    'a dormitory',
    'a library',
    'a priest’s quarters', 'a robing room',
    'a banquet room, large dining hall,', 'a small dining room',
    'a kitchen',
    'a trophy room', 'an art gallery',
    'a stable', 'a kennel',
    'a workshop for temple craftsmen'
  ],
  // You enter the temple and notice __
  features: [
    'a small altar set in an alcove in the wall',
    'the sound of bells ringing in a tower',
    'a wall sconce holding many candles',
    'tall candles on holders, taller than a man',
    'the tinkle of chimes from a nearby room',
    'a tapestry depicting a mythological scene',
    'a small fountain',
    'a reflecting pool',
    'the sound of a gong from another room',
    'a large holy symbol embedded in the wall',
    'a huge book of sacred texts or prayers',
    'the scent of incense burning nearby',
    'a kneeler beneath a small statue or icon',
    'an oil lamp with colored glass panels',
    'a mosaic set into the floor of the room',
    "a wide fresco depicting a scene from the temple's religious texts",
    'a mural depicting a mythological scene',
    'the pipes of an immense organ running along the walls',
    'robes and cassocks hanging on hooks',
    'an ornamental rug',
    'a screen to hide priests from view',
    'a statue of a recognizable figure',
    'two large stone statues further down the hall',
    'a series of percussive thuds punctuated rhythmically by a groaning sound',
    'large stone stairs leading down to a pool of clear water',
    'pillars carved with intricate images of the heavens',
    'floor tiles made of red sandstone',
    'an ornately carved wooden confessions booth with beautiful satin curtains',
    'a crude wooden confession booth with ragged cloth dividers',
    'small, crowded looking pews',
    'long pews made of roughly carved logs',
    'incredibly ornate pews running through the main hall in orderly columns',
    'a gnarled and shriveled hand inside of a glass box on a pedestal',
    'a large urn with mythological paintings going all around it',
    'a small beat up organ pushed to one corner of the room',
    'a large harp sitting near the front of the room',
    'a deep earthy smell coming from some nearby incense',
    'a lovely, flowery smell wafting over from a nearby incense burner',
    'a long table near the entrance that is covered in burning candles and melted wax',
    'a large and ornate chandelier hanging from the ceiling',
    'a rather dingy chandelier just barely hanging from the ceiling',
    "a large shield with temple's symbol emblazoned upon it hanging from one wall"
  ],
  priestChat: [
    // The priest ___
    'says there are beds in a backroom that you all can use for a night if you need',
    'tells you they are holding mass soon and you are welcome to join',
    'says you can light a candle to honor a fallen soul for only 5 copper',
    'softly says you are free to confess your sins here',
    'informs you the temple has confessionals open if you wish to confess',
    'tells you donations are always welcome if you feel generous',
    'says you all can stay as long as you please in this holy house',
    'says that the temple will bless you for a small price',
    'says that $associatedNPC.heshe will bless your weapons for a small price, but you must not tell anyone',
    'tells you the church must close at dark but you can stay until then',
    'asks you if you have come to see the holy relic',
    'asks what the church can do for you today',
    'asks that you stay very quiet while visiting today',
    'slyly brings a donation basket when $associatedNPC.heshe comes to chat',
    'tells you the main priest is gone today, but that $associatedNPC.heshe can also give blessings',
    'says that there is a free meal being offered to all who enter, and offers you some soup',
    'asks you to remove your shoes and place them by the door',
    'hands you hand-made pamphlets about the religion of the temple',
    'says you can not stay long here today as mass is starting soon',
    'says you must leave soon as a ritual is beginning',
    'offers for you all to join in on a ritual that is happening in the temple soon',
    'requests that you change into sets of white robes if you are going to remain here for long',
    'warns you that holy spirits reside in this temple, and if you do not respect them you will anger them',
    'tells you there are beds in a room below the temple and you are welcome to them',
    'offers you a cracker from a small wicker basker',
    'asks if you are need of any excorcisms on this visit',
    'claims $associatedNPC.heshe has minor relics that can be sold to you',
    'offers you each a candle to light for your prayer to be heard',
    'says your weapons must be left in a chest by the door',
    'tells you not to touch any of the holy items in the temple',
    'asks if you have come for a blessing of some kind'
  ],
  priestLook: [
    // A temple priest is ___
    'currently placing some nice smelling incense in <<print ["an old looking", "an ornate", "a cheap looking", "an animal shaped", "a wooden", "a stone", "a golden", "a bronze", "a dirty looking", "a holy"].random()>> incense holder',
    'kneeling in front of a <<print ["small wooden statue", "small stone statue", "small basin of water", "large basin of water", "large wooden statue", "large group of melting candles", "blazing fire", "picture of the temple god", "holy book of the temple", "row of pews"].random()>> and murmuring a prayer of some kind',
    'dusting off one of the temple pews with a small fathered brush',
    'blessing a small basin of water at the front of the temple',
    'lighting a candle and placing it among a large row of candles',
    'sitting in one of the pews whispering a prayer',
    'wearing a large flowing cloak over $associatedNPC.hisher clothes',
    'talking with one of the temple followers',
    'running through $associatedNPC.hisher lines for an upcoming mass',
    'coming out from a door at the back of the temple',
    'ringing a small bell and humming quietly',
    'pouring some sort of liquid into a large number of small cups on a table at the front of the temple',
    'doing some kind of work on the temple organ',
    'wearing a large and elaborate headpiece',
    'standing on a plinth with $associatedNPC.hisher hands raised towards the sky',
    'reading out of a musty looking tome',
    'starting to doze off in one of the pews',
    'placing hymnals on every pew of the temple',
    'relighting the torches that are scattered around the temple',
    'polishing a pair of tall brass candlestick holders at the front of the temple',
    'seemingly talking to the open air as no one is around $associatedNPC.himher'
  ],
  blessingConvey: [
    'The priest raises $associatedNPC.hisher hand above you and mumbles some words in a language you do not understand',
    '$associatedNPC.firstName touches $associatedNPC.hisher finger to your head and whispers something quietly',
    'The priest walks in circles around your holding an incense lamp and chanting something quietly',
    '$associatedNPC.firstName pours water over your face from a small wooden basin while chanting a holy verse',
    '$associatedNPC.firstName pours water over your body from a large stone goblet while whispering an ancient blessing',
    'The priest takes a small cup of paint and draws lines across your face while whispering something in a holy language',
    'The priest has you drink a liquid out of a wooden cup while murmuring some sort of prayer',
    '$associatedNPC.firstName draws a holy symbol around you on the ground in chalk while chanting loudly',
    'The priest paints holy symbols on your palms and then holds your hands while murmuring a prayer',
    'The priest places you in front of a window that has light streaming through it and recites and ancient holy phrase',
    '$associatedNPC.firstName has you kneel, and then walks around you throwing a chalky powder into the air while chanting softly',
    'A temple priest whispers a prayer over a glass of wine and then has you drink it',
    'The priest dunks you backwards into a large vat of water, completely submerging your head, while reciting an ancient blessing',
    '$associatedNPC.firstName takes your hand and slits it open with a silver knife. $associatedNPC.heshe takes your bleeding palm and spill a few drops into a vat of water while chanting in an unknown language',
    'The priest has you hold a small holy statue while $associatedNPC.heshe mumbles a holy blessing'
  ],
  blessingGift: [
    'Afterwards, the priest tells you that you have been blessed with <<print ["holy sight", "holy strength", "holy movement", "holy skill", "holy power", "holy light", "a holy spirit", "true sight", "a pure heart", "holy luck", "a new outlook", "wisdom beyond yourself", "a holy enlightenment"].random()>>, but does not explain what that means',
    'The priest tells you that you were gifted <<print ["underwater breathing", "pure luck", "perfect aim", "silent steps", "strength above strength", "a link with the temple god", "an angelic glow"].random()>> for the next few hours',
    'Afterwards, $associatedNPC.firstName apologizes and says the blessing failed',
    'As the priest chants you can feel something change within you, but neither the priest nor you know what the blessing you recieved was',
    'After the ritual the $associatedNPC.firstName tells you that the blessing succeeded, but they do not know what the blessing is',
    'After all that the priest tells you that <<print ["your body has become heat resistant", "your body will feel no cold", "you can now sense evil", "you can now see in the dark", "your fighting skills will be better", "you will feel true empathy"].random()>> for the next day or so',
    "You're told that the temple patron will now be watching over you, but it's unclear what that really means",
    'You are told by the priest that you are now blessed <<print ["with a better future than the one you were headed towards before", "with a depth of feeling that was locked deep within you", "with an appreciation for the colors of the world you had never known", "with a powerful love for all the animals of the earth, and in return their love towards you", "with a new sense of longing", "with a feeling of inner peace"].random()>>',
    'You have now been blessed with <<print ["a healthy body", "an ever healing body for the next few hours", "a feeling of weightlessness", "a clear mind", "a protective aura", "a hardy body", "a new perspective", "swift fingers", "a new knowledge", "a secret of the gods"].random()>> according to the temple priest'
  ]
}
