setup.createMagicArmour = () => {
  const armours = ['Padded Armour', 'Leather Armour', 'Studded leather Armour', 'Hide Armour', 'Chain shirt', 'Scale mail', 'Breastplate', 'Half plate', 'Ring mail', 'Chain mail', 'Splint Armour', 'Plate Armour', 'Shield']
  const prefixArmours = ["Acolyte's", 'Amethyst', 'Arboreal', 'Arid', 'Astute', 'Arctic', "Artisan's", "Barbarian's", "Bard's", 'Blessed', 'Bloodthirsty', "Burglar's", 'Cavernous', 'Cardinal', 'Cerulean', 'Channelling', 'Charitable', 'Civilized', "Climber's", 'Concealing', 'Consecrated', 'Crystalline', "Dancer's", 'Dazzling', "Debtor's", 'Defensive', 'Deflecting', "Delver's", 'Diplomatic', "Druid's", 'Ephemeral', 'Evasive', 'Fair-weather', 'Lying', 'Favored', 'Feinting', 'Fen', 'Flanked', 'First', 'Fresh', 'Forgotten', 'Furious', 'Garnet', 'Glass', 'Granite', 'Grim', 'Harmonious', 'Heroic', 'Histrionic', 'Holy', "Inquisitor's", 'Inspired', 'Invisible', 'Lightweight', 'Loquacious', "Mage Killer's", 'Malachite', 'Masquarading', "Medic's", 'Moonlit', "Mortals'", 'Mournful', 'Obsidian', 'Opal', 'Pious', 'Prairie', "Preacher's", 'Precipice', 'Primeval', 'Reflexive', 'Renaissance', 'Resonant', 'Righteous', 'Regal', 'Runic', 'Sacred', 'Sagacious', "Sage's", "Sailor's", "Scribe's", 'Shading', 'Shadow', "Shepherd's", 'Shifting', 'Silent', 'Solar', 'Spiked', 'Spiritual', 'Subtle', "Surgeon's", 'Tenacious', "Tracker's", 'Trusty', 'Turquoise', 'Twilight', "Undertaker's", 'Unyielding', 'Vanguard', 'Veiled', 'Victorious', 'Vigilant', 'Vile', 'Violent', "War Leader's", 'Warded', "Watcher's", 'Waterborne', 'Winged', "Wizard's", 'Zen', 'Zircon', 'Abyssal', 'Alarming', 'Arborean', 'Arcadian', 'Astral', 'Beastial', "Beastspeaker's", 'Benedictine', 'Blasted', 'Bold', 'Bountiful', 'Bytopian', 'Carcerian', 'Cartographic', 'Chill', 'Clockwork', 'Cloy', 'Compassionate', 'Concordant', "Conjurer's", 'Corrosive', 'Crawling', "Drunkard's", 'Elysian', 'Etherbound', 'Exalting', 'Expeditious', 'Fathoming', 'Feathered', 'Feybound', 'Forgiven', "Fortune Teller's", 'Friendly', 'Gehennan', 'Gracious', 'Hadean', 'Healing', 'Hellish', 'Desperate', 'Leaping', "Liar's", 'Limbo', 'Locating', 'Malediction', 'Manipulating', "Master's", 'Maverick', 'Messenger', 'Meteoric', 'Miraculous', 'Mocking', 'Natural', 'Neutralizing', 'Nourishing', 'Pandemonium', 'Projecting', 'Protective', 'Revealing', 'Riutal', "Sailor's", 'Secret', 'Shadowbound', 'Shielding', "Smith's", 'Sparkling', 'Striding', 'Translucent', "Trickster's", 'Accurate', 'Verdant', 'Windborne', 'Wrathful', 'Thunderous', 'Chained', "Spider's", 'Heliacal', 'Crippling', 'Lunar', "Fatespinner's", 'Rooting', 'Mirrored', 'Vulpine', 'Submerged', 'Comforting', "Brawler's", 'Eagle-eye', 'Lupine', 'Chiropteran', 'Black']
  const suffixArmours = ['of the Acolyte', 'of Amethyst', 'of the Woodlands', 'of the Wastelands', 'of the Astute', 'of the North', 'of the Artisan', 'of the Barbarian', 'of the Bard', 'of Blessings', 'of Bloodthirst', 'of the Burglar', 'of the Underdark', 'of the Lodestone', 'of Storms', 'of Channelling', 'of Charity', 'of the Hearth', 'of the Climber', 'of Concealment', 'of Consecration', 'of Crystal', 'of the Dancer', 'of Dazzling', 'of Debts', 'of Defence', 'of Deflection', 'of the Delver', 'of Diplomacy', 'of the Druid', 'of Transience', 'of Evasion', 'of Fair-weather', 'of Falsehoods', 'of the Favored', 'of Feinting', 'of the Glade', 'of the Flanked', 'of Reflexes', 'of Cleansing', 'of the Forgotten', 'of Fury', 'of Garnet', 'of Glass', 'of the Mountain', 'of Coercion', 'of Harmony', 'of Heroes', 'of Histrionics', 'of Faith', 'of the Inquisitor', 'of Inspiration', 'of Invisibility', 'of Mobility', 'of the Silver Tongue', 'of the Mage Killer', 'of Malachite', 'of the Masquarade', 'of the Caduceus', 'of the Moon', 'of Mortals', 'of Sorrow', 'of Obsidian', 'of Opal', 'of the Pious', 'of the Plains', 'of the Preacher', 'of the Crags', 'of the Jungle', 'of Reflexes', 'of the Renaissance', 'of Resonance', 'of Righteousness', 'of Royalty', 'of Runes', 'of the Sacred', 'of Acumen', 'of the Sage', 'of the Sea', 'of the Scribe', 'of Shade', 'of Shadows', 'of the Shepherd', 'of Shifting', 'of the Night', 'of the Sun', 'of Teeth', 'of the Divine', 'of Subtleties', 'of the Surgeon', 'of the Tenacious', 'of the Tracker', 'of Resurgence', 'of Turquoise', 'of Twilight', 'of the Undertaker', 'of the Unyielding', 'of the Vanguard', 'of the Veil', 'of Victory', 'of Vigilance', 'of Villains', 'of Violence', 'of the War Leader', 'of Wards', 'of the Watcher', 'of the Sea', 'of Wings', 'of the Wizard', 'of Zen', 'of Zircon', 'of the Abyss', 'of Alarms', 'of Arborea', 'of Arcadia', 'of the Astral Sea', 'of the Beastlands', 'of Beastspeakers', 'of Benediction', 'of Blasting', 'of Boldness', 'of Bounty', 'of Bytopia', 'of Carceri', 'of Cartography', 'of Chills', 'of Gears', 'of Cloying', 'of Compassion', 'of Concordance', 'of the Conjurer', 'of Dissolving', 'of Vermin', 'of Taverns', 'of Elysium', 'of Ethereal Shores', 'of Exaltation', 'of Expedience', 'of Tongues', 'of Feathers', 'of the Fey', 'of Forgiveness', 'of the Fortune Teller', 'of Friendship', 'of Gehenna', 'of Grace', 'of Hades', 'of Healing', 'of the Nine Hells', 'of Last Chances', 'of Leaping', 'of Lies', 'of Limbo', 'of Locating', 'of Malediction', 'of Manipulation', 'of Servants', 'of the Maverick', 'of Messages', 'of Falling Stars', 'of Miracles', 'of Mockery', 'of Nature', 'of Neutrality', 'of Nourishment', 'of Pandemonium', 'of Projection', 'of Protection', 'of Revelation', 'of Rituals', 'of the Sea', 'of Secrets', 'of the Shadowfell', 'of Shielding', 'of Reparations', 'of Lights', 'of Strides', 'of Translucence', 'of Trickery', 'of Truth', 'of Druidcraft', 'of the Labyrinth Wind', 'of Ysgard', 'of the Rolling Thunder', 'of Chains', 'of the Spider', 'of the Sun', 'of Crippling', 'of the Moon', 'of the Fates', 'of Roots', 'of Mirrors', 'of the Fox', 'of the Depths', 'of Comfort', 'of Brawling', 'of the Eagle', 'of the Wolf', 'of the Bat', 'of Darkness']
  const propertyArmours = [
    'The bearer gains a +1 bonus to Wisdom (Religion) checks',
    'Reduces psychic damage to the bearer by 2',
    'Treat as a +1 armor after the bearer has taken a long rest in a forest. If the bearer leaves the forest, this property becomes temporarily inert',
    'Treat as a +1 armor after the bearer has taken a long rest in a desert. If the bearer leaves the desert, this property becomes temporarily inert',
    'It takes half the time to don or doff this armor than a normal armor of this type',
    'The bearer suffers no harm in temperature as cold as -20 degrees Fahrenheit',
    "This armor is a swiss army knife of enchanted appendages that can take the form of any artisan's tools, from Alchemist's and Brewer's supplies to Weaver's and Woodcarver's tools (see p. 154 of the PHB for a complete set of artisan's tools)",
    'The bearer gains a +1 bonus to Strength (Athletics) checks',
    'The bearer gains +1 to Charisma (Performance) checks',
    'Whenever bearer of this item receives divine healing, they gain an additional 1d4 hit points',
    'The bearer can expend a hit die to turn this into a +1 armor for 1d4 turns',
    'The bearer gains +1 to Dexterity (Sleight of Hand) checks',
    'Treat as a +1 armor after the bearer has taken a long rest in a cave. If the bearer leaves the cave, this property becomes temporarily inert',
    'The wielder can use an action to learn which way is north',
    'Reduces lightning damage to the bearer by 2',
    'Once per day, the bearer may ignore the Verbal and/or Somatic components of a spell they are casting',
    'If the bearer donates 100gp or more to a temple of a goodly deity, this becomes a +1 armor for the next 24 hours. If they go longer than a month without making any such donations, they gain a -1 AC penalty until a suitable donation is made',
    'Treat as a +1 armor after the bearer has taken a long rest in an living urban environment. If the bearer leaves the city, this property becomes temporarily inert',
    'This armor is suited with harnesses, rope, and other climbing tools are readily in reach. The bearer may treat this armor as a climbing kit',
    'The bearer may spend one action assembling components of this armor into a dagger. A person searching the bearer for weapons must make a DC 20 Intelligence (Investigation) check to discover this property',
    'Treat this as a +1 armor when the bearer is being attacked by Undead',
    'Treat as +1 armor until the bearer takes a critical hit, at which point it then loses this property',
    'The bearer gains a +1 bonus to Dexterity (Acrobatics) checks',
    'Once per day, the bearer may spend an action to ignite the magic in this armor, causing it to flare brilliantly. Any creature within a 10 foot radius must use their reaction to shield their eyes or be blinded until the end of their next turn',
    'The first 1 bludgeoning, piercing, or slashing damage from any source is negated. However, the total amount of damage prevented from that day acts as a negative modifier on death saving throws. So, if the armor prevented 5 points of damage that day, the bearer has a -5 penalty on death saving throws',
    'Whenever the bearer takes a dodge action, they may move an additional 5 feet',
    'The bearer may spend their reaction to treat this as +1 armor vs. ranged weapon attacks until the beginning of their next turn',
    "While underground, the bearer of this item always knows the item's depth below the surface and the direction to the nearest staircase, ramp, or other path leading upward",
    "The bearer gains proficiency in a language of the DM's choice",
    'The bearer gains a +1 bonus to Intelligence (Nature) checks',
    'Once per day, the bearer may spend their reaction to gain their Wisdom modifier to their AC until the beginning of their next turn',
    'Whenever the wearer takes a dodge action, they gain +1 AC until the end of the turn',
    'The bearer may treat this as +1 armor if the bearer has more than half of their maximum hit points',
    'The bearer gains a +1 bonus to Charisma (Deception) checks',
    'Once per day, the bearer may roll a saving throw with advantage',
    'Whenever the bearer uses the help action in combat, they may treat this as a +1 armor until the beginning of their next turn',
    'Treat as a +1 armor after the bearer has taken a long rest in a swamp. If the bearer leaves the swamp, this property becomes temporarily inert',
    'The wearer may treat this as +1 armor if two or more enemies are adjacent to them',
    'The bearer gain a +1 bonus to initiative rolls',
    'This armor never gets dirty and remains odorless, even in the most filthy dungeon',
    'The bearer may spend an action to attempt to ignite the old magic in this armor with a DC 13 Charisma check. If successful, treat this as a +1 armor as long as the bearer maintains concentration on this effect, maximum 10 minutes',
    'Treat as a +1 armor when the bearer is raging',
    'Reduces fire damage to the bearer by 2',
    'The bearer may treat this as +1 armor as long as the bearer is at full health',
    'Any effect that would move the bearer against their will is reduced in distance by 5 feet',
    'The bearer gains a +1 bonus to Charisma (Intimidation) checks if their armor is visible',
    'Attuning to this item takes only 1 minute',
    'The bearer has advantage on saving throws vs. fear',
    'the bearer gains +1 to Charisma (Performance) checks',
    'When the bearer of this item rolls hit dice, they can choose to re-roll them and take the second result',
    'The bearer gains a +1 bonus to Intelligence (Investigation) checks',
    'The bearer regains their Constitution modifier in temporary hit points whenever they gain or use inspiration',
    'Once worn, this armor turns invisible (although not the wearer)',
    'This armor is 10% lighter than normal armor of this type. If it has a Strength requirement to use, it is reduced by 1',
    'The bearer gains +1 to Charisma (Persuasion) checks',
    'The bearer may spend their reaction to treat this as +1 armor vs. spell attacks until the beginning of their next turn',
    'Reduces poison damage to the bearer by 2',
    'The bearer has advantage on skill checks involving disguise kits',
    "Lined with pockets and compartments and stocked with medical supplies, the bearer may treat this armor as a healer's kit",
    'The bearer may treat this as +1 armor when moonlight is shining directly on this armor',
    'At the end of a turn where the bearer failed a death saving throw, the magic within this armor will attempt to stabilize the bearer. It rolls a Wisdom (Medicine) check with a +3 modifier',
    'When an ally falls unconscious in battle, the bearer gains a +1 AC bonus for the next 10 minutes. If that ally stabilizes or awakens, the bearer loses this bonus',
    'Reduces acid damage to the bearer by 2',
    'Reduces cold damage to the bearer by 2',
    'Whenever the bearer shaves their head, treat this as a +1 armor until the end of the day. They must wait a week until they have long enough hair to re-enact this ritual',
    'Treat as a +1 armor after the bearer has taken a long rest in a grassland. If the bearer leaves the grassland, this property becomes temporarily inert',
    'The bearer may extend the range of their Channel Divinity by 5 feet',
    'Treat as a +1 armor after the bearer has taken a long rest in the mountains. If the bearer leaves the mountain, this property becomes temporarily inert',
    'Treat as a +1 armor after the bearer has taken a long rest in a jungle. If the bearer leaves the jungle, this property becomes temporarily inert',
    'If the bearer is first in initiative order, treat this as +1 armor for 1 minute',
    'Once per day, the bearer may gain +1 to any skill check',
    'The bearer can spend an action and 1 ki point to treat this as +1 armor for 1 minute',
    'Treat this as +1 armor during the day when attuned to a good aligned character',
    'This armor is richly decorated and fashionable. Although it retains a hint of the ruggedness of a military garment, it could function as well in a ballroom as the battlefield. To the outside observer, you appear to be keeping an Aristocratic lifestyle expense',
    'Whenever bearer casts a spell, treat this as +1 armor until the beginning of their next turn',
    'The bearer may increase their Lay on Hands hit point pool by 5',
    'The bearer gains +1 to Wisdom (Insight) checks',
    'The bearer gains a +1 bonus to Intelligence (History) checks',
    'Treat as a +1 armor after the bearer has taken a long rest on the high seas. If the bearer leaves the ocean, this property becomes temporarily inert',
    "This armor unfolds to reveal animated appendages that are equipped with writing implements, magnifying glasses, and book stands. The armor aids the bearer in transcription tasks: it knows 3 languages of the DM's choice and halves the amount of time it takes the bearer to copy any text, including spells into spellbooks",
    'The bearer suffers no harm in temperatures as high as 120 degrees Fahrenheit',
    'Treat as a +1 armor when in dim light',
    'The bearer gains a +1 bonus to (Wisdom) Animal Handling checks',
    'The bearer may change minor aspects of the physical appearance of this item',
    'If this armor imposed disadvantage to stealth, it no longer does. Otherwise, the bearer gains a +1 bonus to Dexterity (Stealth) checks',
    'The bearer may treat this as +1 armor when in direct sunlight',
    'Whenever a creature begins their turn grappling or being grappled by the bearer, they take 1d4 piercing damage',
    "This armor is naught but a prayer written on a scrap of vellum, decorated with religious motifs of a particular god. Once per day, the bearer may spend 1 minute to read the prayer out loud, and at the end this armor will manifest and encase the bearer. The armor disappears if you act in any way that is not in accordance to the god's teachings",
    "The bearer gains proficiency in Thieves' Cant",
    'The bearer gains a +1 bonus to Wisdom (Medicine) checks',
    'When the bearer takes a long rest, they gain back one additional hit die',
    'The bearer gains a +1 to Wisdom (Survival) checks',
    'Treat this as +1 armor if the bearer has half their maximum hit points or less',
    'Reduces thunder damage to the bearer by 2',
    'Within 1 hour before or after the rising and setting of the sun, or during a solar eclipse, the armor comes alive with magic and the bearer may treat this as +1 armor',
    'Once deceased, the body wearing this armor cannot be animated or raised from the dead',
    'The bearer may treat this as +1 armor if they have taken damage since the beginning of their last turn. This effect ends at the beginning of their next turn',
    'The bearer may spend their reaction to gain a +1 AC bonus vs. melee weapon attacks until the beginning of their next turn',
    'The wearer gains a +1 bonus to Dexterity (Stealth) checks when taking a hide action',
    "Whenever the bearer kills a creature while wearing this amror, they gain temporary hit points equal to the creature's CR",
    'The bearer gains +2 to their Passive Perception',
    'Treat this as +1 armor at night when attuned to an evil aligned character',
    'The bearer may choose to treat the heavy metal gauntlets of this armor as a Mace',
    'The bearer can use an action to amplify their voice so that it clearly carries for up to 300 feet',
    'The wearer cannot be possessed while wearing this armor',
    'Treat as +1 armor during surprise rounds',
    'The item floats on water or other liquids. Its bearer has advantage on Strength (Athletics) checks to swim',
    'The bearer gains +5 speed',
    'The bearer gains a +1 to Intelligence (Arcana) checks',
    'Treat this as +1 armor for one minute after meditating with it for one minute',
    'Reduces force damage to the bearer by 2',
    'When on the plane of the Abyss, the bearer has advantage on saving throws against Abyssal Corruption. (DMG p. 62)',
    'Contains 1d4 unreplenishable charges of the Alarm spell (1st level)',
    'When on the plane of Arborea, the bearer has advantage on saving throws against the effects of Intense Yearning. (DMG p. 61)',
    'When on the plane of Arcardia, the bearer is unaffected by Planar Vitality (DMG p. 67)',
    'When travelling the Astral Sea, it takes half the number of hours to locate a Color Pool to a specific plane. You have advantage on saving throws vs. the effects of Psychic Wind (DMG p. 47-48)',
    'When on the plane of The Beastlands, the bearer has advantage on saving throws vs. Beast Transformation (DMG p. 60)',
    'Contains 1d4 unreplenishable charges of the Speak with Animals spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Healing Word spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Fire Bolt spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Heroism spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Goodberry spell (1st level)',
    'When on the plane of Bytopia, the bearer has advantage on saving throws against Pervasive Goodwill. (DMG p. 59-60)',
    'When on the plane of Carceri, the bearer knows the direction to the closest secret exit from this prison plane. (DMG p. 63)',
    'On its own volition, the item records a map of the environments that the bearer is exploring, and can magically project it for the bearer to see',
    'Contains 1d4 unreplenishable charges of the Ray of Frost spell (1st level)',
    'When on the plane of Mechanus, the bearer has advantage on saving throws against Imposing Order (DMG p. 66)',
    'The bearer may cast Friends once per day',
    'Contains 1d4 unreplenishable charges of the Cure Wounds spell (1st level)',
    'The bearer has advantage on saving throws vs. Psychic Dissonance when travelling the Outer Planes. (DMG p. 59)',
    'The bearer may cast Prestidigitation once per day',
    'Contains 1d4 unreplenishable charges of the Acid Splash spell (1st level)',
    'The crawling things of the earth, such as insects, snakes, and vermin, are attracted to this item. When placed on the ground, such creatures will scurry toward the item like moths drawn to the flame',
    'The bearer always knows the direction to the closest alcoholic beverage',
    'When on the plane of Elysium, the bearer has advantage on saving throws against the effects of Overwhelming Joy (DMG p. 60)',
    "The bearer can see creatures in the Border Ethereal that overlap with their plane as clearly as if they were fully in the bearer's plane. Such creatures appear as apparitions or ghosts",
    'Contains 1d4 unreplenishable charges of the Bless spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Expeditious Retreat spell',
    'Contains 1d4 unreplenishable charges of the Comprehend Languages spell',
    'Contains 1d4 unreplenishable charges of the Feather Fall spell (1st level)',
    'The bearer knows the general direction to the closest Fey Crossing within a 60 mile radius. (DMG p. 50)',
    'When on the plane of Mount Celestia, the bearer of this item can receive the benefits of Blessed Beneficence regardless of their alignment',
    'Every time you hit by a monster, you glimpse a random image of its future or past',
    'Contains 1d4 unreplenishable charges of the Animal Friendship spell (1st level)',
    'When on the plane of Gehenna, the bearer has advantage on saving throws against Cruel Hindrance. (DMG p. 63)',
    'The bearer may cast Spare the Dying once per day',
    'When on the plane of Hades, the bearer has advantage on saving throws against Vile Transformation. (DMG p. 63)',
    'This item contains 4 weak healing nodes. As an action, a character can use one node to heal 1d4 hit points at touch range. The item regains 1d4 charges at sunrise',
    'When in the Nine Hells, the bearer has advantage on saving throws against Pervasive Evil. (DMG p. 64)',
    'The bearer has advantage on perception checks when searching for items long lost in the the Swamp of Oblivion on the Plane of Earth. (DMG p. 54)',
    'Contains 1d4 unreplenishable charges of the Jump spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Silent Image spell (1st level)',
    'When on the plane of Limbo, the bearer has advantage to Intelligence checks to alter or move non-magical objects within the plane. (DMG p. 61-62)',
    'Once attuned, the bearer always knows the exact location of this item',
    'Contains 1d4 unreplenishable charges of the Bane spell(1st level)',
    'The bearer may cast Mage Hand once per day',
    'Contains 1d4 unreplenishable charges of the Unseen Servant spell (1st level)',
    'The bearer has a +1 bonus to any skill check involving gambling and games of chance (Insight, Sleight of Hand, Investigation, etc)',
    'The bearer may cast Message once per day',
    'Contains 1 unreplenishable charge of Scorching Ray cast at 2nd level',
    'The bearer may cast Thaumaturgy once per day',
    'The bearer may cast Vicious Mockery once per day',
    'Contains 1d4 unreplenishable charges of the Locate Animals or Plants spell (1st level)',
    'Contains 1d4 unreplenishable charges of the Protection from Good and Evil spell (1st level)',
    'The bearer rarely feels hungry, and only needs to consume one-fifth the usual amount of food',
    'When on the plane of Pandemonium, the bearer has advantage on saving throws against the Mad Winds. (DMG p. 62)',
    'The bearer can send messages mentally to willing characters within 30 feet. This communication is one-way only',
    'The bearer may cast Blade Ward once per day',
    'Contains 1d4 unreplenishable charges of the Detect Magic spell (1st level)',
    'Whenever the bearer is casting a spell as a ritual, they have advantage to maintain concentration during the ritual',
    'Treat as a +1 weapon after the bearer has taken a long rest at sea. If the bearer steps on dry land, this property becomes temporarily inert',
    'Contains 1d4 unreplenishable charges of the Illusory Script spell (1st level)',
    'The bearer knows the general direction to the closest Shadow Crossing within a 60 mile radius. They have advantage on saving throws vs. Shadowfell Dispair (DMG p. 51-52)',
    'This item contains 1d4 unreplenishable charges of the Shield spell',
    'The bearer may cast Mending once per day',
    'The bearer may cast Dancing Lights once per day',
    'Contains 1d4 unreplenishable charges of the Longstrider spell (1st level)',
    'The bearer gains an extra level one spell slot, which recovers only after a full moon rises',
    'The bearer may cast Minor Illusion once per day',
    'The bearer may cast True Strike once per day',
    'The bearer may cast Druidcraft once per day',
    'When in the Plane of Air, the bearer can navigate the Labyrinth Wind intuitively, and knows the path to the nearest Earth Mote within 60 miles',
    'When on the plane of Ysgard, the bearer is unaffected by Immortal Wrath. (DMG p. 61)',
    'Contains 1 unreplenishable charge of Shatter cast at 2nd level',
    'Contains 1 unreplenishable charge of Hold Person cast at 2nd level',
    'Contains 1 unreplenishable charge of Web cast at 2nd level',
    'Contains 1 unreplenishable charge of Flaming Sphere cast at 2nd level',
    'Contains 1 unreplenishable charge of Ray of Enfeeblement cast at 2nd level',
    'Contains 1 unreplenishable charge of Moonbeam cast at 2nd level',
    'Contains 1 unreplenishable charge of Augury cast at 2nd level',
    'Contains 1 unreplenishable charge of Entanglement cast at 2nd level',
    'Contains 1 unreplenishable charge of Mirror Image cast at 2nd level',
    'Characters trying to track the bearer have a -1 penalty to their skill checks',
    'Treat as a +1 armor when completely submerged in water',
    'Treat as a +1 armor if the bearer has any levels of exhaustion',
    "Whenever a bearer makes an attack with an improvised weapon, treat as a +1 armor until the beginning of the bearer's next turn",
    'The bearer can clearly see twice as far and gains advantage on Wisdom (perception) checks that use sight',
    'The bearer can detect and distinguish scents like a wolf and gains advantage on Wisdom (Perception) checks that use smell',
    'The bearer can hear a pin drop in a crowded room and gains advantage on Wisdom (Perception) checks that use hearing',
    'Contains 1 unreplenishable charge of Darkness cast at 2nd level.'
  ]

  const type = armours.random()

  const prefixArmourRoll = random(1, propertyArmours.length)
  const suffixArmourRoll = random(1, propertyArmours.length)

  const prefixProperty = propertyArmours[prefixArmourRoll]
  const suffixProperty = propertyArmours[suffixArmourRoll]

  const description = `${prefixProperty}. ${suffixProperty}`

  const prefixArmour = prefixArmours[prefixArmourRoll]
  const suffixArmour = suffixArmours[suffixArmourRoll]

  const name = `${prefixArmour} ${type} ${suffixArmour}`

  return {
    type,
    name,
    prefixArmour,
    suffixArmour,
    prefixProperty,
    suffixProperty,
    description
  }
}
