
setup.plothook = {
  'joke': [
    "A bard. Not a magic one. Just a bard. Like y'know. A minstrel or some shit he's ok I guess.",
    'Man chasing after a woman through a corn field. Distant saxophone is heard before both get eaten by a troll which chokes to death on them.',
    "The world's highest dragon lands, eats three deer, tries to fly, crashes, then just sleeps where he fell.",
    'A circus is in town. A shitty circus. Like a mobile Chuck E. Cheeses during a power outage.',
    'A village is being savaged by the most passive aggressive wizard ever.',
    'Two heavily armed fighters going at it hammer and tongs in the middle of the road, Every attack is a miss on both sides.',
    "Suddenly ninjas. They don't attack or anything, they have better things to do. But still.",
    "What looks like a sword is stabbed into a stone. Turns out it's just a hilt. Made of tin.",
    "A gnome, a halfling and a dwarf are having a 'who's the shortest' contest. It's fairly easy to resolve and they do so shortly after the party arrives.",
    "A bandit calls for the party to stand and deliver. He's not robbing them, he just really wants his package.",
    "An ugly old man offers the party some of his lunch stew. It's not bad, could use some savory herb or something though.",
    'A young child is crying for his mom. His mom is maybe 40 feet away waiting for the kid to shut up and actually look.',
    'A carrot is near the road. If disturbed a ranger yells at the party for disturbing his rabbit bait.',
    'A rabbit is caught in a trap. If disturbed a ranger yells at the party for disturbing his fox bait.',
    'A fox is caught in a trap. If disturbed a ranger yells at the party for disturbing his wolf bait.',
    'A wolf is caught in a trap. If disturbed a ranger yells at the party for disturbing his bear bait.',
    'A bear is caught in a trap. If disturbed a ranger yells at the party for disturbing his owlbear bait.',
    'An owlbear is caught in a trap. If disturbed a ranger yells at the party for disturbing his ogre bait.',
    'An ogre caught in a trap. If disturbed a ranger yells at the party for disturbing his dragon bait.',
    'A dragon is caught in a trap. If disturbed a ranger yells at the party for disturbing his tarasque bait.',
    "A local child has taken to following the smartest member of the party around asking him 'why' in the most obnoxious voice possible.",
    "A bird poops right down the back of the most wizard-like character's clothes. Haha.",
    'A bird poops right in the eye of the most cleric-like character. Haha.',
    'A bird poops right on the mouth of the most thief like character. Haha.',
    "A branch or sign suddenly breaks it's base or chain or string and swings directly into the most wizard-like character's face.",
    "A lady hobo is telling shitty fortunes for 3 sp a pop. She's got no takers so far.",
    'A group of bandits or pirates are dead drunk singing bawdily together off to one side.',
    'A group of guards catch and hang a thief who just ripped off the necklace of some girl and stole from a few stands.',
    "An attractive bar wench starts flirting with the strongest looking male party member. If asked she'll gladly 'spend time' with them. Nothing else worth noting here.",
    "Town drunk wraps an arm around a party member claiming. 'You'se gais 're al'righ'' before puking on the fanciest dressed character and passing out.",
    'Town drunk pukes on the fanciest dressed character and passes out.',
    'Worst pickpocket in the world attempts to rob from the character who would most easily notice and deal with them. Mostly he just ends up groping them and the running off.',
    "Fake wizard claims to be a real one. When questioned he flings glitter in the party's collective face yelling 'Glitterrust!' and running before tripping on his robes and knocking himself out.",
    'Hobo claims to be a deposed king who will reward the party if they can return to him his seal which some other hobos stole and are hiding out under the town bridge. He just wants to sleep under the bridge after the party clears the other hobos out.',
    "Local noble badly disguised as a commonfolk, no one care since he's got money and is a fairly decent person. Snobs if the party tries to talk to them.",
    'A short shower of copper bits fall from the sky. Like. 10 of them.',
    'A man in a nice set of robes is handing out pamphlets for the local good parish. Introduces himself as Brother Gideon.',
    'A man in a bad set of robes is handing out dead rats from the local evil temple. Introduces himself as Brother BabyStabber.',
    'A man in a decent set of robes is handing out blank pieces of paper from the local neutral temple. Introduces himself with a shrug and a sigh.',
    'A lovely gazebo is seen on the side of the road. It looks like a nice place for a picnic.',
    "An adventure party passes by whining about a lack of something called 'Cheetos' and some or of Dew of a Mountain. Weirdos.",
    "An adventure party passes by with each member spouting off silly 'Ni' noises or something about bushes. Weirdos.",
    "An adventure party passes by with a drow sneaky fellow wearing two scimitars whinging about wanting more 'Ex-Pee' because of 'Role-playing'. Weirdo.",
    'An armless, legless knight has bled out near a creek. Apparently his corpse has been here for a while. His armor seems to be made of paper.',
    "A fairy offers the party a wish if they can answer her riddles three. If they agree she just leaves laughing saying 'I didn't think someone would actually believe me on that.'. If they don't she gets mad and leaves saying 'It's not like they were THAT hard, pansies.'",
    "A lumberjack is eating his lunch on the side of the road. If asked he'll share with one person.",
    "A miner is eating his lunch on the side of the road. If asked he'll share a beer with one person.",
    "A cultist is eating his lunch on the side of the road. If asked he'll share a bagel with one person.",
    'A perfectly serviceable wooden shield is found on the side of the road. Not masterwork or magic. Just serviceable.',
    'A perfectly serviceable shortsword is found on the side of the road. Not masterwork or magic. Just serviceable.',
    "There's a huge pot hole in the road. Like HUGE, for a pothole, it's not a pit or anything. DC 3 Acrobatics check to not stumble on it. Failure means you take 1d2-1 nonlethal teasing damage and fall flat on your ungraceful face.",
    'A tune if heard off in the distance. Nothing in particular, just kind of a musical edge to the area. Like a light mist.',
    'A troop of guardsmen are patrolling the road. They ask you to clear the way and move on.',
    'A man is selling sausages from a decent cart. The sausages are ok.',
    'A man is selling sausages from a crappy cart. The sausages are good, but you start to feel bad for eating too many of them. Like you ate an entire tin of ice cream bad.',
    "A man is selling sausages from a good cart with bread rolls. The bread is bland, and the spice in the sausage is forgettable, but it's filling.",
    "A man is selling wiener dogs from a cart that's barking. Not to eat. He's just selling the dogs. They make good mousers he says.",
    "A woman in armor is offering to bed any man who can beat her in an arm wrestle. She's got a 23 Strength and isn't particularly pretty, but if you're into that it's there.",
    "A group of guards force a group of prostitutes to 'Move along then.'",
    "A minstrel plays nearby. He's ok, but he'd be a lot better if he actually put some practice in.",
    'A local pubkeep offers the party a round of drinks for half off on account of them looking thirsty.',
    'A local inn offers the party a dinner half off on account of them looking hungry.',
    "A man missing a leg thanks the party for the good that they've been doing.", 'A man missing an arm spits at the party for the good they missed doing.',
    'Two bards are utterly failing to sing a song in tune.',
    'Two bards are actually killing a particular song. The crowd around them is pretty into it.',
    "A man is selling hats. He's willing to trade for skins if anyone in the party has any.",
    'The party sees a mild acquaintance. S/He offers to get lunch with them.',
    'The party sees a mild annoyance. S/He flips them the bird before wandering off.',
    "A pie eating contest is in progress. It looks like it's down to the blacksmith's son or the cowherd's daughter.",
    "Two teenagers are walking down the street holding hands and blushing whenever one catches the other's eye.",
    'The wizard steps in shit. Roll 1d4 to see what kind. 1- Cow, 2- Cow, 3- Cow, 4- Builette.',
    'A group of bandits charge, but petter out before combat engages because the party looks too tough to take on.',
    "Seven men in hooded robes are fumbling around. Overhead is: 'Hey John, I think I've got your robes' 'Damnit Sev, your wife swapped our hoods again.' and 'Who's got my sash? It was the scarlet one.'",
    "A drow is hung over on the side of the road. A three empty bottles of dwarven ale are nearby. He's waving his hands about muttering 'Turn off the sun.' Shortly after Dancing Lights twirl around his location as he lets out a groan of pain.",
    'A dwarf is passed out in a puddle of his own drool on the side of the road. A half empty bottle of elven wine is nearby.',
    'A friendly dog comes by and starts begging for treats from the most cleric-like party member.',
    'An unfriendly dog attempts to pee on the most wizard-like party member.',
    'Two old men are playing some sort of game on the side of the road talking mostly in murmurs, grunts, and chortles.',
    'Two old women are gossiping nearby knitting scarves longer than they are tall that are growing by the inch as you watch.',
    'A man is juggling torches nearby. Nothing goes amiss.', 'Two young teenagers are arguing about whether a dragon could be three owlbears if the owlbears had armor and magic wands and the dragon had a sword.',
    'A local noble is in town collecting his due taxes.',
    'The worst bandit in the world attempts to way-lay the party with a sharpened stick and a dented pot lit. If actually confronted he faints in shock.',
    "The wizard discovers he has a sign pinned to the back of his robes reading 'Ass-zard'. It is unknown when it was placed there or how long it's been there.",
    "A dungeon is nearby, if investigated it turns out that it's still in the process of being excavated and won't be ready for several more years.",
    'The thief find a socket puppet nestled amongst his belongings. It appears to be made from one of the wizards socks.',
    'The fighter finds a flask of good booze they had forgot about amongst their belongings.',
    'The cleric finds a bag of honeyed nuts amongst her belongings.'
  ],
  'wilderness': [
    'You see a gazebo by the side of the road. It has an arrow sticking from it.',
    'There is a hanged corpse swaying in the wind. It seems he was tortured before being hanged. A sign around his neck says "Looter of the dead".',
    'There is a badly written sign by the road saying "Tresur hier" with an arrow pointing to a dark, thick forest.',
    'You hear a boom of thunder, even though the sky is cloudless.',
    'During night, a fox skulks into the camp and tries to steal food.',
    'You happen upon an abandoned orchard heavy with lush and delicious-looking fruits.',
    "During the night, a homeless pixie has taken residence in a character's hat or boot. S/he is snoring there happily in the morning.",
    "The characters find the corpse of a great animal completely out of place in the surroundings - a polar bear in the tropic, a lion in the arctic etc. It haven't been touched by any scavengers.",
    'There is a gold coin on the road. There are two on the side of the road, three a little deeper in the underbrush, four behind the bush over there and so forth...',
    'You come across a wolf caught in a trap, it whines pitifully.',
    'A group of teenagers are headed back up the road the way you came. They carry barrels of fresh fish, and they offer to trade some for a horse.',
    "A merchant's corpse lays off the road in a ditch, riddled with arrows. The remains of his raided cart are burned nearby.",
    'A young boy begs for a ride to a nearby city. He is unarmed and clearly hungry.',
    "A party of adventurers stops you and asks for directions and healing. Some are badly injured. They transport a body with them, clearly their group's cleric, turned to stone.",
    'A tree has fallen, blocking the road.',
    'Vultures / Buzzards are circling overhead.',
    'Off in the distance, you see what is clearly a group of bandits preparing an ambush. You still have a chance to take another road.',
    'As you come to a clearing in the wood, you see an abandoned campsite, a pot of soup boiled down to scorched. They clearly left in a hurry.',
    'You find a horse dragging a body behind it. The body is dressed in rags. Inspection will reveal that he died of dehydration.',
    'You notice that all the vegetation in a 1 mile radius is inexplicably dead.',
    'A scrap of lacy cloth has been caught on a bramble, and two sets of tracks lead into the forest.',
    'You come upon an impossibly elderly dwarf, naked as the day he was born, standing in the middle of the road demanding a toll be paid. He proclaims himself to be the King of the Road.',
    'Whoever is on watch distinctly hears a whispering voice warn "Beware the black briar!" No amount of searching uncovers the whisperer.',
    'You find a lake, teeming with fish and crabs. Inspection reveals that the lake is salt water.',
    'A bloated body is on the road, a dagger still in its back. A half-elf dressed in robes with a spell component pouch hooked to her belt. An orange cat guards the corpse fiercely, and will not be scared away.',
    'A large, crudely painted sign proclaims "DETOOR THIZ WAYE", spelled incorrectly in both Common and Giant, pointing off the road and into the rocky foothills.',
    'A group of four small children, no more than eight or nine years old, proudly stops your group. They are adventuring heroes, and want to join your party. To kill nasty trolls, and slay horrible dragons, and stay up as late as they want.',
    "A heavily-guarded merchant caravan passes your party on the road at night. The mercenaries all scowl at you menacingly as they pass, and an archer perched atop a carriage has a shot aimed right at (squishy character's) head.",
    'A gnome is on the road, desperately trying to fix a hulking piece of machinery. It looks like a large two-legged dog, with a seat in the middle. Perhaps it is some mode of conveyance? If interacted with, he is only interested in fixing his contraption, and will demand a platinum piece from any who approach. If given, he will quickly melt the platinum down in a vial and pour it into a wooden mold to replace a broken piece. Once fixed, he will thank them profusely, and only then will he reimburse them an equivalent amount in gold.',
    'A group of slavers stops about 200 yards from you. They have many men, women, and children of a multitude of races bound in chains and they drive them like cattle toward their destination. The procession of slaves is watched over by 80 or so heavily-armed human and hobgoblin guards, enough to make any kind of assault guaranteed suicide. A half-elf dressed in simple clothes with a collar around his neck steps off of a carriage and approaches the group and begins an elaborate pitch, detailing  the "wares" they have for sale. If interested, you can buy a trained warrior for 250 gp, or an untrained slave for only 50gp. They are willing to negotiate on price.',
    'A patrol of royal guards is approaching. Six stout men, guarding what seems to be an iron strongbox. They are traveling quickly. They ask you to join them in transporting their incredibly valuable cargo to the King, promising a small reward for the effort. If the strongbox is opened (by killing the guards and picking a difficult lock), it contains a letter from another kingdom, a peace treaty.',
    'As you come to a river, you see the the bridge has been washed away in the recent storm. You can attempt a difficult crossing, or you can try to find another way.',
    'A lone wolf is following you. At night, when you make camp, it is always lurking just outside your firelight. If attacked, it flees, only to return. If ignored, it simply follows. If given food, it will enter camp and travel with you, but will flee at the first sign of combat.',
    'A pack of dirt-covered Dwarf miners approach from off the road, offering to trade very valuable gems for ale and food ("not trail rations, real food!"). They have just struck upon a massive gem deposit and wish to celebrate. Hope you have some with you.',
    "An archery target hangs on a nearby oak tree. The oak's leaves are just a bit greener than other trees in the area. Shooting three bull's eyes in a row will open a secret door in the tree containing several masterwork longbows with strength bonuses, and a potion of True Strike, as well as a few green feathered caps and some tights.",
    'A hunter approaches, asking for your aid. He is gaunt, obviously hungry. He says he has tracked a bear to a nearby cave, and if you can help him kill it, it will feed his family for a month.',
    'You see two dragons flying, far off in the distance. One spouts fire at the other, and is answered back with lightning. They lock together, tooth and claw, and drop out of sight behind the mountains.',
    "During the night, whomever is on watch hears someone approaching. Moments later, a 15 year old boy runs into the clearing. He drops to his knees and begs you to hide him. He doesn't give any detail, just cries and begs. If you refuse, he runs. A minute or so later, a few farmers with pitchforks and axes appear. They ask if you've seen the boy, claiming he murdered a young girl. (The truth is that he was caught in bed with one of their daughters, who was promised to be wed to a local lord.",
    'A crying baby floats down the river on a singed piece of wood.',
    'A procession of holy men of some unknown faith clad in flowing grey robes approaches. Their leader, a charismatic man wearing a purple robe, will lecture you for hours on the nature of your sin and how you should submit to him to achieve salvation.',
    'You come across a ramshackle village, full of unsavory men. They are a collection of criminals that have been exiled from the nearby towns. They eye your backpack covetously.',
    'You come upon the aftermath of a battle. Corpses litter the ground. Scavengers, both four- and two-legged, pick over the remains.',
    "You notice an elf slumped against a tree, covered in blood. He reveals that he is a courier, and was ambushed by bandits. He tells you that they didn't find the message he carries, it is hidden behind his belt buckle. He asks you to deliver the message for him to a woman named Ella Corwyn in the village of Threader's Hollow, a few days ride out of your way. If read, it is a simple message from her son, who is training in wizardry with the elves. If delivered, Ella will feed your group and offer shelter in her barn.",
    'There is a cemetery here. The graves are dug up and tomb doors are broken, seemingly from the inside. Shuffling tracks lead off into the forest.',
    'A crowd of townsfolk equipped with makeshift weapons and torches are marching towards a nearby city. They proclaim that they are going to do battle with a minor local lord because his taxes are too high. They will almost certainly be slaughtered.',
    'An old hermit appears before you on the road inviting you back to his home for dinner. If asked, he tells you that once a year, he invites a group of travelers to share a meal. If taken up on his offer, he takes you back to a secluded, sparsely furnished hut and provides a rather tasty and hearty stew of rabbit, turnips, carrots, and foraged herbs. He also challenges all comers to a game of Three Dragon Ante. He is very good.',
    "As you begin making camp for the night, you see a meteor crash to earth, no more than an hour's ride from you.",
    'A wandering bard approaches your campfire. If allowed to stay, he sings and plays a lute. He also shares his wine and asks to hear about your adventures. If the stories you tell him are good, he will write a song about you.',
    'You find a poorly-built shack off the road. If inspected, you will find it is full of corpses, all wearing grey robes, all the victims of a ritualized mass suicide, committed with obsidian daggers. At the front of the room, atop an altar, is a man in a purple robe, who drank poisoned wine.',
    "The surface of this lake is covered with the floating bodies of thousands of fish. There's no telling how or why they died, or if they'd be safe to eat. Roll % to see if they're edible.",
    "Here lie the bones of an old ship, wrecked on the reef. The strange thing is, you're miles from the nearest body of water.",
    'As you cross the desert, you come across a single tree, growing tall and strong amid the desolate waste.',
    'You notice that one of the trees in this clearing has no leaves. But its branches are bearing fruit. The fruit is unfamiliar to you, and seems to change colors in the light.',
    'A bear wearing a fine vest and hat is selling expertly-crafted musical instruments from an ox drawn cart hitched to a tree by the side of the road. Prices are high, but the craftsmanship appears to be worth it. A flamboyantly painted sign on the side of the cart in bold calligraphy reads: Musickal Innstruments of Fynest Make, Expertly Craffted by Sir Wm. Bearington III, Proprietor. Sir William Bearington III speaks no languages, but can understand and crudely scratch out replies in Common. Should you attempt to steal from him, Sir Bearington will attack without hesitation, as a Dire Bear.',
    'A small collection of bards of various races have formed an impromptu jam session in a clearing nearby. They sound great, and if asked, they attribute the sound to the quality of the instruments. Anyone with a proficiency in a musical instrument and enough gold in their purse must succeed on a DC 10 Will save, or feel compelled to buy one.',
    "A minotaur comes out of the shadows into your campfire, not making a sound as he approaches. He stands 8 feet tall, with a massive axe strapped to his back. Wordlessly, he crouches near the fire and stirs the embers with a stick. Then he speaks, trading stories of the road. He tells many stories of doing battle with Mountain Giants, and delights in hearing stories of the players' exploits. In the morning, he leaves. If asked, he will provide perfect directions to any one destination.",
    'The bodies of a human woman, a male orc, and a baby half-orc are nailed to nearby trees. A sign stuck in the soil nearby reads "Race Mixers"',
    'A trio of dirty peasants is riding past on an impossibly fancy carriage. They nervously smile and wave at your group. A DC 18 spot check will notice a smear of blood on the side of the carriage.',
    'The light of a large fire winks through the branches to your left, and you can distinctly smell smoke.',
    'You come upon a huge pile of stone rubble. As you look at it, you can see pieces of gear, tapestries, and splintered pieces of wood beneath the pile of stones.',
    'Almost out of nowhere, an incredibly small humanoid creature flies out of the woods and straight at your party. Once she gets close enough to see her tiny face, it is obvious that she is terrified.',
    'A stone basin stands on a plinth in the middle of the road. It seems to be full of water, but when you reach toward it the water drains out of the basin.',
    'A huge cave opens up 30 feet to your left. In front of the entrance is a huge ogre wearing the pelt of a dire bear. He has not noticed you yet.',
    'You come upon a small pond that smells distinctly of low tide. The pond seems to be salt water, and anyone who has lived in a coastal city recognizes some distinctly ocean dwelling fish in the small pond.',
    'A broken down tower pokes out above the trees about 600 yards away. Even from this distance, you can see flashes of blue and green light coming from the topmost windows.',
    'A massive stag comes up to you as you are settling down to sleep. It does not attack, and simply walks up to the fire and lays down. It sits there calmly and stares into the fire. Anyone watching the deer immediately at daybreak sees it slowly dissolve into smoke.',
    'A rumble in the earth is the first indication; soon your party can see the herd of buffalo-like creatures stampeding down the plain directly toward you!'
  ],
  'city': [
    'The PCs witness a break-in at a shop. If they intervene, then right at the end of the encounter the shop owner shows up and accuses the PCs of breaking in and causing damage in his shop. He immediately calls for the guard.',
    "The party runs over or mortally injures a shepherd's goat by accident. After apologizing, the shepherd starts demanding money equivalent to three or four times what the goat's value is. Then, as things settle down, another shepherd comes up and displays another goat injured. City guards start to show an interest in the event as well...",
    'A merchant discovers the PCs are buying something and comes to give them a more expensive offer for something of lesser quality. However, the merchant insists this is a good deal as his cousin works for the town hall and will cause great grief to the party if they refuse his offer.',
    "Townspeople come up to the party and blame them for the local infestation of evil. If the PCs weren't there, so the argument goes, the evil would go elsewhere. A crowd gathers in support of their fellow citizens.",
    "Young lovers have taken the PCs' room as refuge to meet in. They are sought after by families that do not approve.",
    'Injustice breaks out as revolution against a tyrant. The PCs are there to see the first flames, and may play a pivotal role in either supporting or crushing the uprising.',
    'One or more PCs are short-changed by a merchant who considers himself untouchable. Whether he truly is...',
    'The appearance of the PCs breaks the balance of a cold war between two rival mages. Each wishes their support to destroy the other, and fears that the other is successful in recruiting the PCs.',
    "A string of building construction accidents has occurred lately throughout the city. Fortunately, no one's been seriously hurt, but the accidents are increasing in size and damage. The local guild has put up flyers asking for help in solving their problem.",
    'As the PCs walk across a bridge over the river that cuts through town, they notice a couple of young boys standing near the edge of the bridge. They each have a large rock in their hands, and are watching one of the approaching river boats with smiles on their faces. As the boat gets closer, one of the boys raises his rock as if he is going to drop it.',
    "While travelling down by the docks, a ship captain waves the PCs over to talk. He's in a bind, he explains, saying that some of his dock workers didn't show up for work and he has a lot of cargo to load onto his ship so he can make the tide. The captain and crew look disreputable, and nervous, but he is willing to pay well for the work.",
    "The PCs come upon a sobbing woman holding a teenage boy who looks to have been severely beaten. If the PCs ask the woman if they can help, she explains her youngest son was beaten up by a gang of toughs. Of more immediate danger though, is that her oldest son has gone off to exact revenge on them, and she's afraid of what they will do to him.",
    "Down the dimly lit alley, two guards can be seen beating a kneeling man. One rips a coin purse from the kneeling man's belt and says, 'Don't be late next month, old man.'",
    'Storm clouds hang heavy, and thick cold rain pounds down as it has for hours. Gutters gurgle, and the sewers moan as if carrying some great weight. From a drain, a swarm of thousands of black rats burst out and charge the PCs.',
    'The PCs are hired as security for the auction of a mysterious artifact. While stopping repeated theft and auction-rigging attempts, they eventually learn of its evil nature and have to debate breaking their contract and destroying the thing while getting away with it.',
    'A small animal brushes past the PCs as they walk along a dock. After it jumps into the water, a group of sailors rushes onto the dock, firing crossbows and flinging harpoons at the ripples the animal left in the water. While the sailors curse and fire the last few missiles they have, one of the PCs notices the animal left a muddy gem on the top of her shoe.',
    'A local farmer asks the party to either scare off or kill a pack of wolves that have been terrorizing his cattle periodically. (u/Joemac-)',
    'Two opposing tailors each have half of the finest pair of pants ever created. You have been hired to repair the pants and reunite the halves. (u/ANEPICLIE)',
    'A local dancer complains of screaming at odd hours of the morning. (u/Naxura)',
    'The library has been infested with small mimics disguised as books. Exterminate them. (u/SheogorathGaming)',
    'Rumor has it that the local librarian is secretly a dangerous lich/vampire. Investigate. (u/SheogorathGaming)',
    'A bard has been found dead in an alleyway. Investigate. (u/SheogorathGaming)',
    'A young boy has a small pouch of copper stolen from him by teenage thugs. (u/SheogorathGaming)',
    'Through less-than-reputable channels, the party hears about a plan to hunt a small roving group of purple worms. The local crime syndicate wants the precious and hard to obtain organs and blood from the worms. The local city guard wants the location of the nest discovered and reported and nothing more. (u/SSV-Kearsarge)',
    'A noble requests that the party deliver a small package. Around ten minutes after the package is delivered, someone approaches the party and asks where their package is, providing valid identification. (u/U-THNK-IM-HOT-DONT-U)',
    "A city watchman requests the party's help in setting up a sting. If the party agrees, the operation begins, but when the target arrives, at least one member of the party recognizes the target and believes them to be innocent. (u/U-THNK-IM-HOT-DONT-U)",
    "The owner of an herbalist shop hires the party to descend into the city's sewers and gather ingredients, including an organ belonging to a creature that should not rightly be living in the sewer. (u/U-THNK-IM-HOT-DONT-U)",
    "A wizard/scholar shows the party some maps detailing the locations of lightning strikes in the city in the past few years/months/days. There is a strangely perfect circle of lightning strikes around a small, inconspicuous area. An orphan is attempting to learn magic, and the spell he's attempting is much too powerful for him. (u/U-THNK-IM-HOT-DONT-U)",
    'A local organisation ask for your help to find and eliminate cult influence from a variety of districts. (u/bluesoulblaze)',
    'The mayor asks you to help them with a zombie problem. (u/redfighter04)',
    'A rash of political assassinations has sweapt the city council. The only other connecting thread is the same calio cat being seen at the scene. (u/four-art-thou)',
    'A massive sinkhole has collapsed the market square into the sewers. The local urchines claim seeing a shadowy tower and a glowing rainbow mist rise from the hole in the middle of the night. (u/four-art-thou)',
    'A grandly dressed man or woman of significant weight shouts at the adventurers to stop a young thief that ran off with a basket of hers. (u/Billybaf)',
    'A local bard has been abducting local pets and harvesting their tendons for lute strings. A young orphan approaches the party and asks them to rescue his cat, as it is the closest thing he has to a family. (u/Habacoa)',
    'The party is approached by a hunched man with an awful, hacking cough. His face is obscured somewhat by a hood, but he asks the group for some medicine or healing, preferably in his own home. (u/AlDaruma)',
    'A townsman claims to have seen starved, pale humans dragging others away, and the players see that exact man get dragged away moments later if they dismiss it. (u/thunder-runner)',
    'An increasing amount of people are being found dead in their bed with bite marks in the neck. Rumours of vampires are going around, however the bite marks of the victims correspond to their own arrangement of teeth. (u/koekeritis)',
    'It has remained mysteriously cloudy above the city for the last couple of weeks and dead birds keep dropping out of the sky at night. (u/koekeritis)',
    'One day the players find that their favourite tavern is just straight up gone. It has been replaced with a normal living house or two. Nobody in town, not even the people who visited the tavern regularly, can remember the tavern. (u/koekeritis)',
    'A small child asks you to help their father who has been injured in an alley, but when you arrive, nothing is there. The child sits crying and hugging nothing but air. (u/The-Incredible-Thulk)',
    'All of the Clergymen in the town have fallen deathly ill. The town elder asked the party to investigate this phenomenon. (u/Send-Me--Corgi-Gifs)',
    'A young child approaches the party and asks that they find his missing siblings. Their last known location was the decrepit chapel where the city outskirts meets the forest. (u/BardToTheBone)',
    'A sweet old lady stops the party in the street and asks if they can go and buy things on her shopping list for her. She hands the party a bag of gold and the list. Upon closer inspection, the items seem to be ingredients for a deadly mass ritual. (u/ven-resing)',
    'A mad alchemist set up shop next to your favorite tavern. The whole establishment reeks of foul eggs and other unpleasant things. The tavern owner asks you to help convincing the alchemist to stop his work or leave. (u/Scriptorian)',
    'A plague of rats has struck the poorest streets of the city. They seem unusually focused and vicious. Seek out and quash the infestation. (u/Shonen-JUMP)',
    'A tavern has burned to the ground with thirteen people inside, and inside was found the bodies of ten dopplegangers. (u/Silverdragon701)',
    'A local smuggling gang has recently begun battling against a tribe of Grung in the sewers- they have appealed to the city guard for help, and frogs have been seen in concerning numbers after recent rainfalls. (u/Silverdragon701)',
    'Rumors abound that the local magistrate is a devil in disguise- but in fact, they are a polymorphed dragon. (u/Silverdragon701)',
    "An ancient fey ruin has been discovered beneath the city, and green-eyed deer and wolves have begun running through the streets at night, howling and hunting down those who don't get inside fast enough. (u/Silverdragon701)",
    "A child has fallen ill and the local herbalist needs some very specific ingredients but can't leave the child unattended, the herbalist requests your party to get them. (u/Glaedr304)",
    "A string of missing children have been happening in a sector with constant reports of a 'dragon' in the sewers. The local guild council asks the party to investigate. (u/cornho1eo99)",
    'A large tiger is running loose in the market. If the party kills it, the noblewoman it belongs to emerges from the crowd and demands immediate compensation. (u/Kami-Kahzy)',
    'A bit of food sold to the party (cake, pie, soup, etc.) suddenly has a humanoid pinky finger found within it. (u/Kami-Kahzy)',
    'A string of young noblemen have turned up missing, and the only connection is that they all visited the same brothel. (u/Kami-Kahzy)',
    'A magnificent circus has arrived in town, but during the last night of the festivities the castle will be robbed. (u/Kami-Kahzy)',
    "An old ship thought to be lost at sea for many years suddenly returns to port, seemingly no worse for wear. The crew and passengers are completely unscathed, and no one has any idea how long they've actually been gone. (u/Kami-Kahzy)",
    'The poorest and youngest citizens start to drown on dry land and in open places, skin soaked and slimey. There is an aboleth somewhere infecting the oldest, deepest, well of the city with its slime. (u/NeoBlue42)',
    "Somebody is 'kidnapping' all the bronze statues in the city. Its either a military faction building a massive hidden cannon, a were-rust monster, or a mad mage perfecting an animate object spell. (u/NeoBlue42)",
    'The Guild of Actors and Musicians has challenged both the Illusionest Guild and Bard College to a contest of pomp and pagency for the next festival. They need the party to sabotage the competition. (u/NeoBlue42)',
    'The city guard has lost two female members undercover in the brothel district. Not missing but giving up law and order in favor of vice and hedonism There may be a succubi flipping all of the agents being sent. (u/NeoBlue42)',
    "The local brewer's latest batch of high end whiskey has been sabotaged/cursed by fae. The five barrels already sold need reclaimed quickly and quietly less the brewery's reputation suffers. (u/NeoBlue42)",
    'Half the city has become overgrown with dense vegetation overnight. The city watch is busy defending the rest of the city from wild animal incursions from the newly-formed woods, so the Captain of the Guard asks the party to investigate the root of the matter. (u/UristMcRandom)',
    'An infection seems to spreading in the slums. City officials deny any proof of it and guards no longer keep watch close to the slums at night. You are beckoned into an alleyway by a hooded figure who implores you to find out the fate their loved one who went into the slums to heal the sick. (u/ApertureJunkieZA)',
    'A local sports team have gotten inexplicably unstoppable in a very short time. Rumours of something amiss range from dark bargains, to an amazing halfling herbalist (and everything in between). Collect clues, follow up leads, and get to the bottom of it! (u/EchoIndia)',
    'The water in one district has suddenly become highly flammable. The local government want to find out why, and want it stopped. Players find that a group of anti-establishment rabble employee a pyromancer to make this easy to hide accelerant, but something went wrong. (u/EchoIndia)',
    'The entire upper class are loosing their hair and want you to get to the bottom of it. (u/Patergia)',
    "It's election time for the new city Mayor. To everyone's surprise, the Kobolds that live in the city sewers have put forward a candidate for the job... (u/CasparGlass)",
    "A local cult of demon worshippers have recently been seen helping the community, feeding the homeless, and housing the poor. The city guard is SURE they're up to no good, but can't PROVE it. (u/CasparGlass)",
    "The village drunkard is stuck in a Groundhog day loop, and uses his knowledge to mess with the party for 24 hours, as it's the most fun way to spend repeating eternity. (u/CasparGlass)",
    "A distressed-looking housewife implores the party to kill the giant rats living in her basement. Once down there, however, the party finds hallucinogenic mushroom spores that cause them to see their greatest fears. It's otherwise a perfectly ordinary basement. (u/CasparGlass)",
    'A peddler with a cart selling odd wares, such as jugs that transform water into oil and pots that heat up without fire, has been seen wandering the streets at night. However, the items he sells often malfunction or explode. (u/davechua)',
    "A talking rat has been hustling the three shell game in dark alleys, cheating locals of their gold. It's rumoured it wears a hat. (u/davechua)",
    'Every full moon, the cats of town gather inside a deserted house. What are they planning? (u/davechua)',
    "A local merchant asks the party to deliver a note across the city. When they return for payment the merchant doesn't remember the party. An investigation will show that his left ring finger is now missing. (u/bigfootbob)",
    'The party sees a local elderly woman attacked by a large half-orc man. He steals a small pouch filled with the leaves of an exotic plant. If the party returns the plant to the woman, she rewards them with a dozen cookies made from the plant they returned to her. After consuming the cookies the adventurers find out that the plant is this worlds equivalent to marijuana. (u/z4ch4ry27)',
    'An Ooze that was planted in the sewers to clean them and deal with the rat problem has grown ginormous and started to split into more Oozes. (u/GreenUnlogic)',
    'The party hears about a man getting murdered last night. The perpetrator is a spirit and there were plenty of witnesses, but only about half saw the spirit. Every night another victim is taken until the group can unravel the secret. (u/Tyreal01)',
    'A man is confronted by a mob for not being able to control his sorcery. (u/Tyreal01)',
    'The local Thief Guild is fighting a Feud with the local Gypsy family for the drugdealing control of a district. The governor/s, know this and get money for looking the other side, a lot of money, but their feud might recall unwanted attention over the city and his pocket, he ask your help in the matter. (u/caciuccoecostine)',
    "A brewer of the second best ale in town believes the most popular brewer has made a pact with a demon to enhance her wares. If the party investigates, they find that all the brewers in town have unknowingly made deals with the same demon, which has plans to adulterate all their wares and take control of the townsfolks' minds. (u/KNHaw)",
    'Workmen are sledgehammering tombstones from the local cemetery for material to repair the cobblestone streets. The dead are not happy about this. (u/KNHaw)',
    "A statue in the town square has disappeared overnight and footprints (apparently from the statue) are found leading to the Magicians' quarter. It could be a prank or something more sinister. (u/KNHaw)",
    "A drunkard begins to screaming at the party, claiming they robbed him. When searched by watchmen, the man's purse turns up in their pockets. (u/KNHaw)",
    'Bodies have begun appearing at the exits of the sewers with bite marks on them. Rumors of cannibal cults, lycanthropes, and other such things have begun flying around. You are hired to investigate the matter. (u/Cybercancer)',
    'A seemingly mad doomsayer is yelling in the streets that the sewers are a gateway to the Abyss. Every day this is ignored, d8 demons of a challenge rating of 1 or lower will crawl out of the sewers at night. Every week this is ignored, the challenge rating increases by 1. (u/BeastlyDecks)',
    'In the big garden of a powerful family, the party notices several woodland critters acting strange. Upon further inspection, they appear almost human in their mannerisms. If the party inquires about the family, they learn that they are rather known for being proficient in charming and polymorphing... (u/BeastlyDecks)',
    'A single member of the party notices a young boy in an alleyway with a third eye in his forehead. The boy telepathically tells the member to come find him in the graveyard. (u/BeastlyDecks)',
    'The party is stopped by a traveling salesman, that frantically insists on handing a spherical object wrapped in cloth to the party. (u/BeastlyDecks)',
    "Eleanor, an heiress to a wealthy baron's estate, is found murdered in the old meatpacking district. Gretchen, her identical twin, plasters the city in posters offering a bountiful purse for the head of her sister's killer. Meanwhile, a woman claiming to be Eleanor swears that it was her sister Gretchen that was killed, and is offering a matching reward to anyone who can uncover the truth. (u/MrKHackworth)",
    'A beloved statue has disappeared from the center of town. An alderman asks the party to find it, but the more they investigate, the more people insist that the statue never existed. (u/MrKHackworth)',
    'Animate slimes and oozes are seeping out of the sewers. (u/Patergia)',
    "A long line of ill townfolks are waiting impatiently outside the apothecary's house, they been there all day and either the apothecary or her assistant are answering the door. The thing is that the apothecary kept some creatures caged to farm their poison and somehow, they were freed. (u/rhockman)",
    'The party encounters a burning building and must rescue several commoners trapped inside. Later, they discover that this is one in a string of arsons. (u/Pawthorn)',
    'The party must earn the respect of a local group of toughs by competing in a bracket-style fighting tournament. However, some competitors have been meeting with unfortunate accidents... (u/Pawthorn)',
    'Several locals have committed uncharacteristic, violent acts. Each claims to have been commanded to do so by a benevolent deity in their dreams. (u/Pawthorn)',
    'A talking cat follows the party, promising to take them to a magical place where wine flows like water and gold litters the ground. (u/Okami-G)',
    'The building of a new road has earned the city the ire of the local druids. (u/Okami-G)',
    "The local miners have gone on strike, demanding higher wages and better equipment. The Boss wants your to remind them who's in charge. (u/Okami-G)",
    'A portal to hell/the abyss opens in the town square, but nobody else seems to notice or care. Demons are now shopping in the market. (u/Gllithid)',
    'When the local innkeeper is rebuilding his hearth, a removed section of a wall reveals a human skeleton embedded in the masonry, covered in strangle carvings. (u/k1bsTV)',
    'The group sees a Drow named Vicepenny with a red balloon trying to lure a child into the sewers from a sewer drain. (u/Hwga-lurker-tw)',
    'A monkey steals and runs off with one of their hats. Will return for a piece of fruit. (u/Hwga-lurker-tw)',
    'An employee in a lumberjack costume offers the party free samples of jerky from a nearby tavern counting as one daily ration. (u/Hwga-lurker-tw)',
    'A group of mean geese begin chasing any dwarves or gnomes in the group. Geese are protected under the city rulers. (u/Hwga-lurker-tw)',
    "A peaceful Hill Giant sells his intricate lace patterns. People wonder how he does it. Upon interrogation he reveals he does most of the work himself but his two Pixie roommates are always waiting for him to go to sleep. The lace over your face lets you get a good night's rest no matter where you are. (u/Hwga-lurker-tw)",
    'A hippy elf sells a single dragon scale necklace with your name on it for 1d6x10GP. (u/Hwga-lurker-tw)',
    "The party gets a coupon for one free lesson 'For You & A Friend' at the local Fighting Pit. They have to pay for their own uniforms. (u/Hwga-lurker-tw)",
    "Ever since the ascension of the new baron/burgher, criminals have been taken into the keep and never seen again. The captain of the guard knows that the keep should have run out of room in the dungeons long ago, but he hasn't been allowed inside to see them. (u/crunkDealer)",
    'A public execution is taking place in the town square, the town is split on whether the accused is actually guilty. (u/crunkDealer)',
    'A house/shop in the middle of town has vanished entirely, as if it were just erased from creation. A strange scent and magical residue permeates the premises. (u/crunkDealer)',
    "A very belligerent (and often drunk) old man is causing problems in town. The hangup: it is the burgher's dearly beloved uncle who remains an extremely proficient fighter in his advanced age. The guard can't apprehend him without serious injury to the man. (u/crunkDealer)",
    'A dog and a large lizard are fighting each other in the center of town, surrounded by a crowd of onlookers. If asked, any of the bystanders will tell the party that these are two local druids who put on these shows in exchange for donations.',
    'A well dressed elf runs up to the party, desperately shouting something about a painting and a demon.',
    'A huge crack has recently appeared in the center of the town square. The town guard are keeping everyone away from the fissure, especially since it smells of sulfur and green fumes will occasionally puff out of it.',
    'Ten sailors come up to the party, laughing drunkenly. They seem interested in buying the party drinks, and are more than happy to chat and joke with anyone who seems jovial. If any PCs accept their offer of drinks, they will wake up to find themselves press-ganged into service on a pirate ship.'
  ],
  papers: {
  },
  'paper': [
    "The piece of paper bears large block letters, stating 'WANTED', with an illustration underneath- the faces below bear a remarkable similarity to your own...",
    "The paper states 'WANTED: DEAD OR ALIVE', with the fine print reading 'For the crimes of theft, robbery, burglary, and arson, the $town.name Bandit is wanted dead or alive.' You ask _bartender.firstName about what the crimes entailed, and apparently there's been a huge rash of thefts of food in $town.name recently, resulting in food shortages. The $town.type's council has hired bounty hunters to catch the criminal.",
    "The paper has the headline 'HENS STOPPED LAYING, EGGS COST 2 SILVER! Apparently, all hens in the area have stopped laying eggs, and has driven the price of eggs sky high.",
    '‘Wanted Dead or Alive – Bonecrusher, Orc Chieftain to the south! Warning: very heavily armed and dangerous. Has many henchmen. Reward: 1,000gp’',
    '‘Missing: a large turtle named Hubert who has escaped from the Caster’s School of Polymorphing. Please return if found!’',
    'Chicken Wrangler Needed! Some jerks smashed my coop and now 100 chickens are loose. 1GP/chicken to return them, no questions asked.’ (Poster is True Neutral witch in old haunted forest; all the chickens have been enlarged.)',
    'Need men to form a small honour garrison for the banquet I am holding in my manor. Important people are involved, so discretion is mandatory. 200GP per person, payed upfront. No questions asked. (All the guests are vampires.)',
    'The book store has a shipment of rare books coming in and needs people to help unload them. Will pay 100gold per person and not responsible for any injuries incurred on the job. (Caution: dangerous magic and pet books around.)',
    'Exterminator needed: I’ve got a mess of rats in my basement. Bring me 10 rat tails in return for payment. (Listed address has no basement and owner has no rat problem. The advert has a typo and should point to a house further down the way.)',
    'Exterminator needed: There’s a bunch of noise coming from the attic. Like chains or moaning or something. It’s probably those damn raccoons again. I would have my husband look into it, but the lazy oaf up and died on me. Payment dependant on work done. (Listed address has no attic, but does have a basement with a rat problem. Murdered husband is haunting the house, bring proton pack.)',
    'Strong Swimmer Needed! My simpleton apprentice left my ore cart unattended on the bridge and the blasted thing tumbled into the river! Hopefully the ore is still in there somewhere, I’ll pay gold to anyone who can get me my ore!',
    'Sick Grandmother: My grandmother is sick and needs a shipment of medicine. Our normal courier has gone missing, so we desperately need it delivered. Expedited fee available with a bonus upon delivery (Grandma makes a mean elven bread.)',
    'Squirrel Hunting: A squirrel has been seen in town stealing jewelry from citizens. We think there may be more than one squirrel involved — they always head west after the theft. They need to be captured or killed; a bonus available if stolen items are returned.',
    'Earrings Stolen: My wagon was robbed by bandits in the eastern forest. Among the items taken where heirloom earrings that were given to me by my mother. Please find them. Reward available.',
    'TEST SUBJECT NEEDED! We at the Barrington Bakery are looking for subjects to test out our new magical breads. We infuse magic into the mixing process for a, hopefully, tasteful bread. You will need to taste each bread, and have our scholar review the side effects. You will be paid per day.',
    'Lost Arrow: While practicing with a bow, my son lost a trophy arrow (he was not supposed to use). He was practicing in the Northern plains and thinks the arrow went into the forbidden forest. Please retrieve this arrow. As an alchemist, I will pay in healing potions.',
    'Goblin encampment: A goblin encampment has appeared in the Southern part of town across the ravine. They’ve been there for days and don’t seem to be aggressive, but we can’t be so sure. Find out what they’re doing — if they’re a threat, please dispatch with them.',
    'Wandering Skeleton: Wandering Skeleton seen on the outskirts of town. It appears armed with a sword, shield and horned helmet. Dispatch this skeleton and we’ll offer you 10% off anything in town.',
    'Help! Local bard needs assistance creating a list of 100 dirty jobs no one wants to do. A small payment will be available as well as your name as a contributing author in the book I’m writing.',
    'Kobold Flour: Local baker seeks Kobold Flour for the upcoming Monster festival. This specialty item can only be found in Kobold encampments. Will pay 10gp per pound (maximum of 100 pounds).',
    'The (Insert bar or inn name here) is looking for a bard to entertain the crowds on Thursday Nights (mug for a copper night).',
    'Merchants looking for armed security to escort us to (Insert town or city name here).',
    'Our beloved mushroom forager, has not returned from the forest. He was last seen four days ago. Need help finding him(her?)!',
    'Lost mail! Important documents might have been intercepted. The currier I’ve been expecting has not arrived. Please inquire at the City Hall.',
    'The town of (insert neighboring town) has challenged us to our annual match of Shinty (or similar sport). Let’s show them who’s best, and get that trophy back where it belongs!',
    'Lady Clarissa will read your future in the cards. I know you will show up. Where am I? Don’t worry, dear. Fate will guide you.',
    'The Imperial Army needs your skills! Join us to fight the good fight!',
    'Koboliam Ore Needed: A local blacksmith needs Koboliam Ore, which is only found in the Myriad caves to the North. Once a Kobold stronghold, this abandoned cave is full of traps and possibly other dangers — will pay top gold for each block of Ore.',
    'Burial Escort needed: Our recently deceased father needs to be buried in the family lot, six miles north through the badlands. A small party escort is required in case of trouble.',
    'Bandit Kidnappers! Our beloved daughter has been captured by Bandits! They have not made any demands, but we want her back. They were last seen Northwest of the old tower — a reward for our daughter (alive), plus a bonus for the head of each bandit.',
    'Family Bandits! My son and his two friends have left the village to become bandits. Find them and teach them the error of their ways. Reward if they return — must be alive.',
    'Kubo’s Strings: Local bard Kubo lost his musical strings during an encounter with a small dragon. The dragon has the magical strings attached to it’s teeth. Please retrieve the strings and you will be rewarded with a +1 AC enchantment to your armor!',
    'Flying Monkeys: During a recent storm, Flying Monkeys came and took our poor family dog. They live in the Julliad mountains. Please bring back our precious dog — our children are lost without them. We don’t have much in money, but as farmers we can reward you with rations for all your travels.',
    'Magnificent Seven: Our villagers overheard bandits who plan on raiding our town in one week’s town. We seek seven or more strong warriors who will help defend us.',
    'Troupe of traveling bards need a few strong individuals to help schlep and set up our equipment on our world tour. Can pay in booze and lodging.',
    'Detail-oriented individuals needed to go door-to-door to market my magical floor-sucker-cleaner. Commission based.',
    'Need young fit person to shovel snow from my walkway (if high summer. In winter substitute with ‘mow grass’ or something else appropriate. Employer is an elderly individual from a far-off land who has enchanted their property to be more like their home country.)',
    'Book keepers needed! Not really. Bandit-wizards have been trying to steal from my personal library of arcane books. Need tough, preferably illiterate, bodies to defend collection until I can secure safer storage.',
    'Tower Demolition Sought: The four story bell tower has been deemed by the city council as a stain on the communities reputation, as it was built with ‘ill-gotten’ funds by the rencently disgraced and now former mayor, Cornul Glassen. The council is offering 500 gold to anyone who can reduce the bell tower, which was dedicated in his honor, to rubble without loss of life or other property in the town square. Plans must be approved by council before work can begin.',
    'Come join us for the first annual bucket festival! Bring a bucket and you favourite drinks to join in the festivities. Meet out back the delapited house on the edge of town at any time. You know the one, you’ve seen it in your dreams.',
    'Needed bartender. Looking to employ a bartender for my inn, The crooked arrow. Must be able to listen to political rants on the slower days. NO GOBLINS',
    'The well water has started tasting funny, someone should look into that.',
    'LOST Young boy named James, he has been missing for over a week and was last seen going of to play by the river. Reward if found.',
    'Local spell caster looking for lab ‘assistant.’ Intelligence not required, but a high resistance to pain appreciated.',
    'Mole Dispatch – a group of unusually large moles wreck our fields! We are in dire need of a someone who is getting rid of those pests. Payment in gold or products from our farmers market.',
    'Sheep Numbers Dwindling – We don’t know who, or what, is killing our sheep, but we cant ignore it any longer. Over the last three months, we found several mother sheep and their newborns dead. We offer 10 gold coins for whoever finds out what has happened to our lifestock and ends this from happening again. (A were-sheep has been killing the other sheep, can be found out when the heard is observed, all sheep go away when this particular one comes close to them, or when the transformation happens during a clear moonlit night.)',
    'A notice to those on hard times that the mines are hiring, the tag line on the bottom says ‘We’ve cleared out the danger that once struck our mine and threatened the safety of the miners, we are confident that resuming our operations shall be fruitful and safe for all.’ (Underneath that is a hand written note directly under the text, ‘So much for your confidence.’)',
    'Deal of a lifetime! I’m willing to trade a lovely tin pot, painted with cornflowers and lilies (and showing a few holes, true, but that’s a plus, for you can add a few more and look at that, you’ve got a colander) for a cart. The cart needn’t be big, can even be tiny, in fact, just so that two, or better four, people could fit in it, with ample room for bags and sacks, if possible. Could be old, long as it rides well and has new wheels, and strong axles, so actually probably nothing made longer than a year or two ago would do. Leave a message with Bohddie.',
    'MINIONS NEEDED – Local Lich Looking for Less than Lawful Lackeys. References not required, no paladins. Full training and benefits given.',
    'Looking for adventure? Ready to leave this crummy town? Want to earn lots of gold? Ask for Captain Delwyn at the docks.',
    'Lost: pet rabbit named Fluffy. Reward: 2 gold.',
    'WANTED DEAD OR ALIVE: The assassin Reudelard (see attached picture).',
    'Fire and brimstone! Eternal torture and damnation! That is what awaits those who reject our lady of mercy!',
    'Looking for willing test subjects. 200 gold per experiment. 400 gold if you lose a limb.',
    'Help! Looking for druid to help persuade nature spirit to get out of my well. Water is poisoned.',
    'REPENT SINNERS - Temple of the Lady of Spring',
    'Attend the public execution of: Johnny "Two Heads" McGee, Kevin "The Fireball Kid" Laristan, and "Bob".'
  ],
  'people': [
    "I overheard from two servants that they plan to poison the Lord of $town.name! I've tried to get in to his grounds, but the doorguard won't listen to me because I'm just a nobody... Please, save him!",
    "There's a tournament coming up, not far from here. We need strong, trustworthy people as the Lord of $town.name's security detail.",
    "I know that you are not likely to believe me, but... I am the messenger for the Duke's brother- yes, he had a brother, who has been in exile for some time. I've been charged to deliver this letter to the Duke, but I fear that I'm being followed and may meet my fate soon; the exact details are better left unknown, lest you make yourself a permanent target for holding the knowledge that I do. You must get this message to him. But do not open it, as the Duke will not touch it if the wax seal has been broken.",
    "I'm looking for some guards to help me deliver some cargo some weeks' way away from $town.name; I can't promise that it's going to be easy, but if you keep me and my cargo safe, I can promise rewards well worth your time.",
    "I've been hearing strange rattling and moans coming from the abandoned house next door. Would you mind checking it out for me?"
  ]
}
